import { CursoBase, QuizActiveRecall } from '../../tipos';

function leccion(
  id: string,
  titulo: string,
  duracion: number,
  intuicion: string,
  analogia: string,
  pasos: string[],
  definicion: string,
  formula: string | undefined,
  ejemplos: string[],
  errores: string[],
  aplicaciones: string[],
  retoEnunciado: string,
  retoTipo: 'problema_resuelto' | 'ejercicio_contextualizado' | 'simulacion',
  retoPistas: string[],
  retoSolucion: { paso: number; descripcion: string; formulaUsada?: string; resultadoParcial?: string }[],
  retoVerificacion: string,
  palabrasClave: string[],
  quiz: QuizActiveRecall[]
) {
  return {
    id,
    titulo,
    duracionAproximada: duracion,
    explicacionFeynman: {
      intuicionInicial: intuicion,
      analogiaSimple: analogia,
      pasoAPasoIntuitivo: pasos,
    },
    conceptoTecnico: {
      definicionFormal: definicion,
      formulaMatematica: formula,
      ejemplos,
      erroresComunes: errores,
      conexionAplicaciones: aplicaciones,
    },
    retoPractico: {
      tipo: retoTipo,
      enunciado: retoEnunciado,
      pistas: retoPistas,
      solucionPasoAPaso: retoSolucion,
      verificacionActiveRecall: retoVerificacion,
    },
    palabrasClave,
    quizActiveRecall: quiz,
  };
}

export const InglesCurso: CursoBase = {
  id: 'ingles-neuro',
  nombre: 'Inglés Natural: A2 a C2 con Input Comprensible',
  descripcion: 'Curso de Inglés para Secundaria que evita gramática tradicional, usando input comprensible, shadowing y contextos reales. Progresión A2-B1-B2-C1.',
  nivelEducativo: 'Secundaria',
  competencias: [
    'Comprender y producir mensajes orales y escritos en inglés',
    'Usar el idioma de forma natural y automática',
    'Desarrollar fluidez y precisión fonética',
    'Participar en interacciones comunicativas significativas',
    'Aprender de forma autónoma y autoconocida',
  ],
  duracionEstimada: '18 meses',
  metodologia: {
    metodoFeynman: true,
    activeRecall: true,
    spacedRepetition: true,
    intuicionAntesFormula: true,
    estrategiasTransversales: [
      'Input comprensible antes de gramática explícita',
      'Shadowing diario para automatización fonética',
      'Cajas de contexto (Daily Life, Business, Entertainment, Academic)',
      'Autoevaluación con grabación y escucha',
      'Uso de sentidos para retención (gestos, imágenes, sonidos)',
    ],
  },
  modulos: [
    {
      id: 'daily-life-a2',
      titulo: 'A2: Daily Life English - Tu Mundo en Inglés',
      orden: 1,
      spacedReviewSchedule: ['día 1', 'día 2', 'día 4', 'día 7'],
      lecciones: [
        leccion(
          'presentaciones-a2',
          'Presentaciones Básicas: Who Are You?',
          15,
          'Imagina que llegas a un nuevo colegio y todos hablan otro idioma. Primero escuchas cómo te presentan a ti, luego repites. Sin pensar en reglas, solo imitas.',
          'Aprender a presentarte es como aprender a decir "hola" al perro del vecino. No necesitas saber gramática, solo suena igual.',
          [
            'Escucha cómo se dice: "Hi, my name is..."',
            'Repite en voz alta: "Hi, my name is..."',
            'Cambia el nombre: "Hi, my name is..."',
            'Practica con diferentes emociones: feliz, cansado, emocionado',
          ],
          'Las presentaciones básicas incluyen funciones comunicativas para identificación personal, preferencias e intereses iniciales.',
          '',
          [
            '"Hi, my name is Ana"',
            '"I like pizza and music"',
            '"I am 12 years old"',
            '"Nice to meet you"',
          ],
          [
            'Traducir directamente del español ("Yo soy")',
            'Olvidar artículos (a, an, the)',
            'No imitar acento natural del sonido',
          ],
          [
            'Hacer amigos en intercambios culturales',
            'Viajes internacionales',
            'Redes sociales globales',
          ],
          'Graba 30 segundos presentándote en inglés. Usa: nombre, edad, algo que te guste.',
          'ejercicio_contextualizado',
          [
            'Escucha modelo: "Hi, my name is..."',
            'Habla después de escuchar 3 veces',
            'Verifica con IA si sonó natural',
          ],
          [
            { paso: 1, descripcion: 'Escoge palabras simples: nombre, edad, hobby favorito', resultadoParcial: 'Estructura clara' },
            { paso: 2, descripcion: 'Habla despacio imitando ritmo inglés', resultadoParcial: 'Pronunciación natural' },
            { paso: 3, descripcion: 'Revisa con feedback IA coach', resultadoParcial: 'Mejora continua' },
          ],
          '¿Qué frase usarías para responder "How are you?"?',
          ['name', 'age', 'like', 'hello', 'nice to meet'],
          [
            { pregunta: '¿Cómo dices "Me llamo Ana" en inglés?', respuestaCorrecta: 'My name is Ana / Hi, my name is Ana', explicacion: 'Las presentaciones usan "my name is" para identificación.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué respuesta usas para "How are you?"?', respuestaCorrecta: 'I am fine, thank you / Good thanks', explicacion: 'Respuesta común para saludos informales.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué es mala idea traducir directamente del español?', respuestaCorrecta: 'Suena forzado y no natural', explicacion: 'El inglés y español tienen estructuras diferentes.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'present-simple-a2',
          'Present Simple: Routine and Habits',
          18,
          'Imagina que cuentas tu día típico: te levantas, comes, trabajas. El Present Simple es como un reloj: marca las rutinas que se repiten cada día.',
          'El Present Simple es como el patrón de tu vida: si cada mañana corres, es porque "I run" cada día.',
          [
            'Se usa para rutinas y hábitos: "I wake up at 7"',
            'Se usa para hechos generales: "Water boils at 100°C"',
            'Con frecuencias: always, usually, sometimes, never',
            'No cambia con personas: I/you/we/they = he/she = s',
          ],
          'El Present Simple describe rutinas, hábitos y hechos generales. Se forma con el verbo base (to be: am/is/are).',
          'I/You/We/They + verb | He/She/It + verb-s',
          [
            '"I eat breakfast at 8 AM" (rutina)',
            '"She works in a bank" (hábito)',
            '"Water freezes at 0°C" (hecho)',
          ],
          [
            'Olvidar la -s en 3ra persona',
            'Usar present para rutinas en lugar de "used to"',
            'No incluir frecuencias para contexto',
          ],
          [
            'Descripción de rutinas diarias',
            'Conversaciones cotidianas',
            'Narración de hábitos personales',
          ],
          'Describe tu rutina típica del lunes usando Present Simple. Incluye 4 actividades.',
          'ejercicio_contextualizado',
          ['Lista actividades diarias', 'Usa conectores: first, then, after', 'Practica con shadowing'],
          [
            { paso: 1, descripcion: 'Oración 1: "I wake up at 7 AM"', resultadoParcial: 'Actividad de rutina' },
            { paso: 2, descripcion: 'Oración 2: "I usually eat breakfast"', resultadoParcial: 'Frecuencia incluida' },
            { paso: 3, descripcion: '"I go to school by bus"' },
            { paso: 4, descripcion: 'Oración 4: "I study English after school"', resultadoParcial: 'Rutina completa' },
          ],
          '¿Qué diferencia hay entre "I" y "He/She" en present simple?',
          ['present simple', 'routine', 'habit', 'frequency', 'verb'],
          [
            { pregunta: '¿Para qué se usa el Present Simple?', respuestaCorrecta: 'Rutinas, hábitos y hechos generales', explicacion: 'Describe acciones repetidas.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo se forma la 3ra persona del verbo "to eat"?', respuestaCorrecta: 'eats', explicacion: 'He/She/It + s.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué conectores usarías para describir una rutina?', respuestaCorrecta: 'First, then, after, finally', explicacion: 'Secuencia temporal.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'going-to',
          'Going to: Planes y Predicciones',
          16,
          'Imagina que ya decidiste algo: vas a viajar mañana. El "going to" es como una promesa que ya hiciste. No es un sueño, es un plan.',
          'El "going to" es como un boleto de avión: ya lo compraste (decisión), no es solo un deseo.',
          [
            'Para planes/preparaciones: "I am going to visit Lima"',
            'Para predicciones con evidencia: "Look at the clouds, it\'s going to rain"',
            'Se forma: be (am/is/are) + going to + infinitivo',
            'La negación: "I am not going to..."',
          ],
          'El "going to" se usa para expresar planes, intenciones y predicciones basadas en evidencia actual. Se forma con el verbo "to be" + "going to" + infinitivo.',
          'am/is/are + going to + verb',
          [
            '"I am going to be a doctor" (plan)',
            '"It is going to rain" (predicción con evidencia)',
            '"Are they going to come?" (pregunta de plan)',
          ],
          [
            'Confundir con "will" para planes',
            'No usar "look" para predicciones con evidencia',
            'Olvidar el verbo "to be" antes de "going to"',
          ],
          [
            'Conversaciones de planes futuros',
            'Pronósticos en contextos sociales',
            'Negociación de actividades futuras',
          ],
          '¿Qué planes tienes para el fin de semana? Expresalos usando "going to".',
          'problema_resuelto',
          ['Identifica planes concretos', 'Usa estructura correcta', 'Practica pronunciación'],
          [
            { paso: 1, descripcion: 'Plan: "I am going to visit my grandmother"', resultadoParcial: 'Decisión expresada' },
            { paso: 2, descripcion: 'Plan: "I am going to watch a movie"', resultadoParcial: 'Estructura am + going to' },
            { paso: 3, descripcion: 'Pronostico: "It looks cloudy, it\'s going to rain"', resultadoParcial: 'Predicción con evidencia' },
          ],
          '¿Qué diferencia hay entre "going to" y "will"?',
          ['going to', 'plan', 'prediction', 'will', 'decision'],
          [
            { pregunta: '¿Qué expresas con "going to"?', respuestaCorrecta: 'Planes y predicciones con evidencia', explicacion: 'Decisión ya tomada.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo formas "going to" con "they"?', respuestaCorrecta: 'They are going to', explicacion: 'be = are para they.', tipoMemoria: 'factual' },
            { pregunta: '¿Cuándo usarías "It\'s going to rain"?', respuestaCorrecta: 'Cuando ves nubes oscuras ahora', explicacion: 'Predicción basada en evidencia actual.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'there-is-there-are-a2',
          'There is / There are: Describiendo lo que Existe',
          14,
          'Imagina entrar a una habitación y contar lo que ves. "There is" para algo singular, "There are" para cosas en plural. Es como un inventario hablado.',
          'Hay/There is/There are es como hacer una lista mental: un gato = there is; tres gatos = there are.',
          [
            'There is: algo singular/existencia única',
            'There are: cosas en plural/múltiples',
            'There isn\'t / There aren\'t: negación',
            'Is there? / Are there?: preguntas',
          ],
          'There is/There are se usa para indicar existencia de algo en un lugar específico. There is para singular, there are para plural.',
          'There is + singular | There are + plural',
          [
            '"There is a book on the table" (singular)',
            '"There are three chairs" (plural)',
            '"There isn\'t any water" (negación)',
          ],
          [
            'Confundir is/are con there is/are',
            'Olvidar singular/plural después de "there"',
            'Usar mal la negación corta',
          ],
          [
            'Descripciones de lugares',
            'Inventarios en conversaciones',
            'Preguntas sobre existencias en tiendas',
          ],
          'Describe tu habitación usando "there is/there are". Incluye al menos 5 objetos.',
          'ejercicio_contextualizado',
          ['Lista objetos', 'Usa singular/plural correcto', 'Añade detalles'],
          [
            { paso: 1, descripcion: 'There is a bed next to the window', resultadoParcial: 'Singular' },
            { paso: 2, descripcion: 'There are two chairs and a desk', resultadoParcial: 'Mixto plural' },
            { paso: 3, descripcion: 'There is a poster on the wall', resultadoParcial: 'Singular con posición'},
            { paso: 4, descripcion: 'There are no plants (negación)', resultadoParcial: 'Negación correcta' },
            { paso: 5, descripcion: 'Are there any books? (pregunta)', resultadoParcial: 'Interrogación' }
          ],
          '¿Cómo dirías "No hay agua"?',
          ['there is', 'there are', 'is there', 'are there', 'there isn\'t'],
          [
            { pregunta: '¿Cuál es la negación de "there is"?', respuestaCorrecta: 'There isn\'t / There is not', explicacion: 'Negación en singular.', tipoMemoria: 'factual' },
            { pregunta: '¿Usas "there is" o "there are" con "cats"?', respuestaCorrecta: 'There are', explicacion: 'Plural.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo formas una pregunta con "there are"?', respuestaCorrecta: 'Are there + sustantivo?', explicacion: 'Invirtiendo el orden.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'preposiciones-lugar',
          'Preposiciones de Lugar: In, On, At, Under, Next to',
          17,
          'Imagina que describes dónde está un juguete: está en la mesa, al lado del sillón, debajo del sofá. Las preposiciones son como mapas miniatura de ubicación.',
          'Las preposiciones son como instrucciones de GPS: "in" = dentro, "on" = encima de, "under" = debajo de, "next to" = al lado.',
          [
            'In: dentro de un espacio (in the box)',
            'On: encima de una superficie (on the table)',
            'At: en un punto específico (at the door)',
            'Under: debajo de algo (under the chair)',
            'Next to: al lado de algo (next to the window)',
          ],
          'Las preposiciones de lugar indican la posición de algo en relación a otro. Se usan con "there is/are" y con el verbo "to be".',
          'n/a',
          [
            '"The book is on the table"',
            '"The cat is under the chair"',
            '"The keys are next to the door"',
            '"The vase is in the middle of the room"',
          ],
          [
            'Confundir in/on/at según contexto',
            'Omitir preposición y sonar truncado',
            'No usar en descriptivos espaciales',
          ],
          [
            'Descripciones geográficas',
            'Instrucciones y direcciones',
            'Narración de escenas y ambientaciones',
          ],
          'Coloca 5 objetos diferentes en tu habitación y describe dónde están usando preposiciones.',
          'ejercicio_contextualizado',
          ['Observa tu habitación', 'Describe posición de cada objeto', 'Usa distintas preposiciones'],
          [
            { paso: 1, descripcion: 'The pen is on the desk (encima de superficie)', resultadoParcial: 'on' },
            { paso: 2, descripcion: 'The bag is under the bed (debajo de)', resultadoParcial: 'under' },
            { paso: 3, descripcion: 'The lamp is next to the chair (al lado de)', resultadoParcial: 'next to' },
            { paso: 4, descripcion: 'The cup is in the box (dentro de)', resultadoParcial: 'in' },
            { paso: 5, descripcion: 'The picture is on the wall (sobre superficie)', resultadoParcial: 'on' }
          ],
          '¿Qué preposición usarías para "La mesa está en la cocina"?',
          ['preposition', 'in', 'on', 'at', 'under', 'next to'],
          [
            { pregunta: '¿Qué preposición usas para algo dentro de una caja?', respuestaCorrecta: 'in', explicacion: 'Dentro de un espacio cerrado.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué preposición usas para algo encima de una mesa?', respuestaCorrecta: 'on', explicacion: 'Superficie.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué preposición usas para estar al lado de alguien?', respuestaCorrecta: 'next to', explicacion: 'Proximidad.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'adjetivos-descripcion',
          'Adjetivos Descriptivos: Color, Tamaño y Forma',
          16,
          'Imagina pintar un cuadro con palabras: "La casa grande roja". Los adjetivos añaden color, tamaño y forma a tus frases. Sin ellos, todo es gris.',
          'Los adjetivos son como colores de crayones: "big" = crayón grande, "small" = crayón pequeño, "red" = crayón rojo.',
          [
            'Adjetivos describen: color, tamaño, forma, temperatura, personalidad',
            'Van después del verbo "to be": "The house is big"',
            'Orden: opinión-tamaño-edad-forma-color-material',
            'Comparativos: "bigger" y superlativos: "biggest"',
          ],
          'Los adjetivos son palabras que describen características de sustantivos. Se colocan después del verbo "to be" o antes del sustantivo.',
          'The + noun + is + adjective',
          [
            '"The house is big and red"',
            '"The car is small but fast"',
            '"My dog is friendly and black"',
          ],
          [
            'Creer que los adjetivos van antes del sustantivo en inglés',
            'No ordenar múltiples adjetivos correctamente',
            'Confundir adjetivos con adverbios',
          ],
          [
            'Descripciones en conversaciones',
            'Redacción creativa y narrativa',
            'Compras y comparación de productos',
          ],
          'Describe tu mascota o un animal favorito usando al menos 3 adjetivos. Incluye tamaño, color y forma.',
          'ejercicio_contextualizado',
          ['Piensa en características del animal', 'Ordena adjetivos correctamente', 'Practica con shadowing'],
          [
            { paso: 1, descripcion: 'My cat is small (tamaño)', resultadoParcial: 'Adjetivo básico' },
            { paso: 2, descripcion: 'She is black with white spots (color)', resultadoParcial: 'Color descriptivo' },
            { paso: 3, descripcion: 'She is fluffy and round (forma/textura)', resultadoParcial: 'Forma y textura' },
            { paso: 4, descripcion: 'Putting together: "My cat is small, black and fluffy"', resultadoParcial: 'Frase completa' },
            { paso: 5, descripcion: 'Compare with comparative: "bigger than my neighbor\'s cat"', resultadoParcial: 'Comparativo' },
          ],
          '¿Dónde van los adjetivos en inglés?',
          ['adjective', 'big', 'small', 'red', 'beautiful'],
          [
            { pregunta: '¿Dónde van los adjetivos en "The house is big"?', respuestaCorrecta: 'Después del verbo "to be"', explicacion: 'Inglés usa "to be" + adjetivo.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo dirías "La casa es más grande"?', respuestaCorrecta: 'The house is bigger', explicacion: 'Comparativo: -er.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué tipo de palabras describen un sustantivo?', respuestaCorrecta: 'Adjetivos', explicacion: 'Adjetivos = descripción.', tipoMemoria: 'factual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: '¿Cómo dirías "Me llamo Carlos" en inglés?', respuestaCorrecta: 'Hi, my name is Carlos / My name is Carlos', explicacion: 'Presentación básica con "my name is".', tipoMemoria: 'factual' },
        { pregunta: '¿Qué diferencia hay entre "there is" y "there are"?', respuestaCorrecta: 'There is para singular, there are para plural', explicacion: 'Concordancia con número.', tipoMemoria: 'factual' },
        { pregunta: '¿Qué preposición usarías para "el libro está sobre la mesa"?', respuestaCorrecta: 'on', explicacion: '"On" indica encima de una superficie.', tipoMemoria: 'factual' },
      ],
    },
    {
      id: 'business-english-b1',
      titulo: 'B1: Business English - Tu Trabajo en Inglés',
      orden: 2,
      spacedReviewSchedule: ['día 3', 'día 5', 'día 10', 'día 18'],
      lecciones: [
        leccion(
          'presentacion-profesional',
          'Presentación Profesional: Your Work in English',
          20,
          'Imagina que trabajas en una empresa internacional. Necesitas decir qué haces sin usar palabras difíciles. Usa ejemplos que cualquiera entienda.',
          'Hablar de trabajo en inglés es como explicarle tu hobby a un amigo nuevo: empieza simple, construye confianza, luego detalla.',
          [
            'Di qué haces: "I am a student"',
            'Explica brevemente: "I study mathematics"',
            'Agrega interés personal: "I like problem solving"',
            'Siempre termina con pregunta: "What about you?"',
          ],
          'Business English incluye vocabulario profesional esencial, expresiones de cortesía y estructuras para describir roles laborales.',
          '',
          [
            '"I work in marketing"',
            '"My job is to help clients"',
            '"I am responsible for..."',
            '"Can I help you with...?"',
          ],
          [
            'Usar demasiado jargon técnico',
            'No preguntar después de hablar',
            'Sonar demasiado formal al principio',
          ],
          [
            'Entrevistas de trabajo',
            'Negocios internacionales',
            'Colaboraciones multiculturales',
          ],
          'Graba cómo presentarías tu proyecto escolar favorito en una feria internacional.',
          'problema_resuelto',
          [
            'Empieza con "This project is about..."',
            'Di por qué te gusta: "I like it because..."',
            'Usa vocabulario simple y seguro',
          ],
          [
            { paso: 1, descripcion: 'Presenta el tema claramente', resultadoParcial: 'This project is about climate change' },
            { paso: 2, descripcion: 'Explica relevancia brevemente', resultadoParcial: 'I like it because it helps our planet' },
            { paso: 3, descripcion: 'Invita a participar', resultadoParcial: 'Would you like to know more?' },
          ],
          '¿Qué expresión usarías para iniciar una conversación profesional?',
          ['job', 'work', 'project', 'presentation', 'help'],
          [
            { pregunta: '¿Cómo dirías "Trabajo en marketing"?', respuestaCorrecta: 'I work in marketing', explicacion: 'Estructura simple para describir profesión.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué forma se usa para ofrecer ayuda?', respuestaCorrecta: 'Can I help you with...?', explicacion: 'Expresión común en contextos profesionales.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué evitar el jargon al principio?', respuestaCorrecta: 'Porque suena forzado y genera inseguridad', explicacion: 'El input comprensible prioriza claridad sobre complejidad.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'present-continuous-b1',
          'Present Continuous: What are You Doing?',
          19,
          'Imagina que entras a una cocina y todo el mundo está cocinando, hablando, moviéndose. El Present Continuous captura esa acción en marcha AHORA.',
          'El Present Continuous es como un video: ves algo que está pasando en este momento, no algo que pasa cada día.',
          [
            'Se usa para acciones que ocurren AHORA: "I am cooking"',
            'También para planes futuros con horarios: "I am meeting John at 3"',
            'Se forma: am/is/are + verb-ing',
            'La negación añade "not": "I am not eating"',
          ],
          'El Present Continuous (am/is/are + verb-ing) describe acciones que están ocurriendo en el momento de hablar, o planes futuros ya acordados.',
          'Subject + be verb (am/is/are) + -ing',
          [
            '"I am studying English right now"',
            '"She is cooking dinner"',
            '"They are watching TV"',
          ],
          [
            'Confundir con present simple para habituales',
            'Olvidar "to be" antes del verbo-ing',
            'No usar para planes futuros coordinados',
          ],
          [
            'Descripciones de acciones en tiempo real',
            'Negocios: "I am reviewing the report"',
            'Comunicación de situaciones cambiantes',
          ],
          'Describe qué estás haciendo AHORA mismo usando Present Continuous. Usa al menos 3 acciones.',
          'ejercicio_contextualizado',
          ['Observa tu entorno', 'Describe acciones simultáneas', 'Usa conectores de tiempo'],
          [
            { paso: 1, descripcion: 'I am writing the lesson plan now', resultadoParcial: 'Acción en tiempo real' },
            { paso: 2, descripcion: 'I am listening to music while working', resultadoParcial: 'Acción simultánea' },
            { paso: 3, descripcion: 'I am not eating (I am focusing)', resultadoParcial: 'Negación incluida' },
            { paso: 4, descripcion: 'I am meeting my friend after this call', resultadoParcial: 'Plan futuro coordinado' },
            { paso: 5, descripcion: 'Putting together: "Right now I am writing and listening"', resultadoParcial: 'Frase completa' },
          ],
          '¿Cómo formarías "Nosotros estamos estudiando"?',
          ['present continuous', 'am', 'is', 'are', 'ing'],
          [
            { pregunta: '¿Qué verbo auxiliar usas con "I" en present continuous?', respuestaCorrecta: 'am', explicacion: 'I am + verb-ing', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo dirías "Ella está trabajando"?', respuestaCorrecta: 'She is working', explicacion: 'She is + verb-ing', tipoMemoria: 'factual' },
            { pregunta: '¿Para qué usas el present continuous?', respuestaCorrecta: 'Acciones que ocurren ahora', explicacion: 'Momento presente en acción.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'have-got-b1',
          'Have got / Has got: Poseer Cosas',
          15,
          'Imagina que haces inventario de lo que posees: una computadora, dos libros, un perro. "Have got" y "Has got" te permiten contar tus posesiones.',
          'Have got es como tu lista de cosas: "I have got" = tengo, "She has got" = tiene. Simple para posesiones.',
          [
            'Have got para "yo/tú/nosotros/ellos" (plural)',
            'Has got para "él/ella/usted" (singular)',
            'Negación: haven\'t got / hasn\'t got',
            'Pregunta: Have I? / Has she?',
          ],
          'Have got/has got expresa posesión. Have got con I/you/we/they; has got con he/she/it. Se usa en contexto informal.',
          'I/You/We/They have got | He/She/It has got',
          [
            '"I have got two dogs"',
            '"She has got a car"',
            '"We haven\'t got time"',
          ],
          [
            'Confundir have got con "have" (experiencia)',
            'No usar has got con ella/usted',
            'Olvidar la negación corta',
          ],
          [
            'Descripciones de posesiones',
            'Conversaciones informales',
            'Inventarios personales',
          ],
          'Después del trabajo, ¿qué te ha quedado? Usa "have got/has got" para describir 3 posesiones.',
          'problema_resuelto',
          ['Lista objetos personales', 'Usa have/has según persona', 'Practica contracciones'],
          [
            { paso: 1, descripcion: 'I have got a laptop', resultadoParcial: 'have (yo)' },
            { paso: 2, descripcion: 'She has got two phones', resultadoParcial: 'has (ella)' },
            { paso: 3, descripcion: 'We have not got time (haven\'t got time)', resultadoParcial: 'Negación' },
            { paso: 4, descripcion: 'Have got = posesión. I have got = I own', resultadoParcial: 'Contraste con "have" experiencia' },
            { paso: 5, descripcion: 'Putting together: "I have got a laptop but I haven\'t got time"', resultadoParcial: 'Combinado' },
          ],
          '¿Qué diferencia hay entre "have" y "have got"?',
          ['have got', 'has got', 'possession', 'ownership', 'experience'],
          [
            { pregunta: '¿Cómo dirías "Ella tiene un coche"?', respuestaCorrecta: 'She has got a car / She has a car', explicacion: 'Has got para posesión.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo formas la negación de "I have got"?', respuestaCorrecta: 'I haven\'t got', explicacion: 'Contracción.', tipoMemoria: 'factual' },
            { pregunta: '¿Con quién usas "have got" vs "has got"?', respuestaCorrecta: 'I/you/we/they have got; he/she/it has got', explicacion: 'Concordancia.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'articulos-determinados',
          'Artículos Definidos: The, A, An',
          18,
          'Imagina que en una librería apuntan a cosas: "el libro" (específico), "un libro" (cualquiera). Los artículos son como dedos que señalan: "the" = este, "a/an" = uno cualquiera.',
          'El artículo es como señalar en un catálogo: "the book" apunta a un libro conocido; "a book" es cualquier libro.',
          [
            'The: artículo definido, algo conocido o único',
            'A: artículo indefinido, algo no específico (sonido "ah")',
            'An: artículo indefinido, algo no específico (sonido "eh")',
            'A/an: antes de cosas contables en singular',
          ],
          'Los artículos (the, a, an) introducen o especifican un sustantivo. The es definido; a/an es indefinido. An va antes de sonidos vocálicos.',
          'the = definido; a/an = indefinido',
          [
            '"The book" = libro que ya conoces',
            '"A book" = cualquier libro',
            '"An apple" = sonido de "a" en apple (ah)',
            '"A university" = sonido de "y" en university (yoo)',
          ],
          [
            'Creer que "the" siempre va antes de sustantivos',
            'Confundir a/an según vocal escrita vs pronunciación',
            'Olvidar artículos en frases cortas',
          ],
          [
            'Redacción académica precisa',
            'Comunicación comercial formal',
            'Narración en presentaciones',
          ],
          'Corrige las frases: "I saw book", "I need an car", "She is a engineer".',
          'ejercicio_contextualizado',
          ['Recuerda "a/an" antes de cosa contable', 'The va con conocimiento mutuo', 'An va con sonido "eh"'],
          [
            { paso: 1, descripcion: 'I saw a book (indefinido, singular)', resultadoParcial: 'a antes de consonante' },
            { paso: 2, descripcion: 'I need a car (car = sonido "c" = consonante)', resultadoParcial: 'a, no an' },
            { paso: 3, descripcion: 'She is an engineer (engineer = sonido "e" = vocal)', resultadoParcial: 'an antes de vocal' },
            { paso: 4, descripcion: 'Putting together: "I saw a book, I need a car, she is an engineer"', resultadoParcial: 'Artículos correctos' },
            { paso: 5, descripcion: 'Verify with "the": "I saw THE book I bought yesterday"', resultadoParcial: 'Definido' },
          ],
          '¿Qué artículo usarías antes de "apple"?',
          ['the', 'a', 'an', 'articles', 'definite'],
          [
            { pregunta: '¿Qué artículo usas para algo no específico en singular?', respuestaCorrecta: 'a o an', explicacion: 'Indefinido.', tipoMemoria: 'factual' },
            { pregunta: '¿Cuál artículo usas antes de "university"?', respuestaCorrecta: 'a', explicacion: 'Suena como "yoo", consonante.', tipoMemoria: 'factual' },
            { pregunta: '¿Cuál artículo usas antes de "orange"?', respuestaCorrecta: 'an', explicacion: 'Suena como "or", vocal.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'preguntas-wh-b1',
          'Preguntas WH: Who, What, Where, When, Why, How',
          21,
          'Imagina un detective: pregunta quién hizo algo, qué pasó, dónde ocurrió, cuándo, por qué y cómo. Cada pregunta abre una puerta diferente.',
          'Las preguntas WH son como llaves: cada una abre una habitación diferente de la historia. Who → personas, What → cosas, Where → lugares.',
          [
            'Who: preguntar por personas',
            'What: preguntar por cosas o acciones',
            'Where: preguntar por lugares',
            'When: preguntar por tiempo',
            'Why: preguntar por razones',
            'How: preguntar por manera',
          ],
          'Las preguntas WH (who, what, where, when, why, how) se usan para obtener información específica. Se forman invirtiendo el orden del verbo.',
          'WH-word + verb (to be/do)',
          [
            '"Who is she?"',
            '"What are you doing?"',
            '"Where does he live?"',
            '"Why did they leave?"',
          ],
          [
            'Confundir who con what para personas',
            'No invertir el orden del verbo',
            'Olvidar "do/does" en preguntas con verbos normales',
          ],
          [
            'Entrevistas y encuestas',
            'Conversaciones de viaje',
            'Negocios: preguntas de investigación',
          ],
          'Escribe 5 preguntas WH diferentes sobre el viaje perfecto. Usa cada palabra WH una vez.',
          'ejercicio_contextualizado',
          ['Think of a trip scenario', 'Use each WH word once', 'Make them natural'],
          [
            { paso: 1, descripcion: 'Who: "Who will you travel with?"', resultadoParcial: 'Persona' },
            { paso: 2, descripcion: 'What: "What will you do there?"', resultadoParcial: 'Actividad' },
            { paso: 3, descripcion: 'Where: "Where will you go?"', resultadoParcial: 'Lugar' },
            { paso: 4, descripcion: 'When: "When will you travel?"', resultadoParcial: 'Tiempo' },
            { paso: 5, descripcion: 'Why: "Why do you want to travel?" + How: "How will you get there?"', resultadoParcial: 'Razón y manera' },
          ],
          '¿Cuál pregunta usarías para preguntar por una razón?',
          ['who', 'what', 'where', 'when', 'why', 'how'],
          [
            { pregunta: '¿Qué pregunta usarías para una persona?', respuestaCorrecta: 'Who', explicacion: 'Who se refiere a personas.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué pregunta usarías para una razón?', respuestaCorrecta: 'Why', explicacion: 'Why pregunta causas.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué se invierte el orden en preguntas?', respuestaCorrecta: 'Porque se pone el verbo antes que el sujeto', explicacion: 'Inversión verb-sujeto en preguntas.', tipoMemoria: 'conceptual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: '¿Cómo dirías "Hago ejercicio ahora" en Present Continuous?', respuestaCorrecta: 'I am exercising right now / I am doing exercise now', explicacion: 'am + verb-ing.', tipoMemoria: 'factual' },
        { pregunta: '¿Qué diferencia hay entre "a" y "an"?', respuestaCorrecta: 'An va antes de sonidos vocálicos, a antes de consonantes', explicacion: 'Depende del sonido, no de la letra.', tipoMemoria: 'factual' },
        { pregunta: '¿Qué pregunta usarías para preguntar por un lugar?', respuestaCorrecta: 'Where', explicacion: 'Where pregunta por lugares.', tipoMemoria: 'factual' },
      ],
    },
    {
      id: 'entertainment-b1',
      titulo: 'B1: Entertainment English - Cultura Pop y Humor',
      orden: 3,
      spacedReviewSchedule: ['día 4', 'día 6', 'día 13', 'día 24'],
      lecciones: [
        leccion(
          'chistes-basicos',
          'Chistes Básicos: When Words Play Games',
          22,
          'Imagina que una palabra quiere ser otra cosa. Si "book" se viste de "cook", ¡hay carcajada! El humor es jugar con significados.',
          'Un chiste es como un acertijo visual: ves algo, piensas otra cosa, y de repente entiendes la trampa.',
          [
            'Escucha chistes simples: "Why did the tomato turn red?"',
            'Entiende: "Because it saw the salad dressing!"',
            'Practica con frases similares',
            'Intenta crear tu propio chiste usando palabras similares',
          ],
          'El humor en inglés incluye juegos de palabras (homófonos), dobles sentidos y chistes de situación.',
          '',
          [
            '"I scream" vs "ice cream" (homófonos)',
            '"Time flies like an arrow" (doble sentido)',
            '"I\'m reading a book about anti-gravity. It\'s impossible to put down." (ironía)',
          ],
          [
            'Tomar chistes demasiado en serio',
            'No entender contexto cultural',
            'Traducir literal sin sentido cultural',
          ],
          [
            'Entender series y películas en inglés',
            'Hacer amigos angloparlantes',
            'Comprender redes sociales en inglés',
          ],
          'Crea un chiste tipo "Why did..." usando un animal y una acción divertida.',
          'ejercicio_contextualizado',
          [
            'Empieza con: "Why did the [animal]..."',
            'Piensa en una acción rara o graciosa',
            'Asegúrate de que funcione como juego de palabras',
          ],
          [
            { paso: 1, descripcion: 'Choose animal and situation', resultadoParcial: 'Why did the cat join a band?' },
            { paso: 2, descripcion: 'Create punchline', resultadoParcial: 'Because it wanted to be a purr-cussionist!' },
            { paso: 3, descripcion: 'Practice with shadowing', resultadoParcial: 'Natural delivery' },
          ],
          '¿Qué tipo de chiste fue el de gato y la banda?',
          ['joke', 'laugh', 'funny', 'because', 'animal'],
          [
            { pregunta: '¿Qué es un homófono?', respuestaCorrecta: 'Palabras que suenan igual pero tienen significados diferentes', explicacion: 'Ejemplo: "to", "too", "two".', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué es difícil entender chistes al principio?', respuestaCorrecta: 'Falta conocimiento cultural y contexto', explicacion: 'El humor depende de normas sociales.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Qué tipo de chiste usa "I\'m reading a book about anti-gravity"?', respuestaCorrecta: 'Doble sentido o ironía', explicacion: 'Juega con la imposibilidad literal.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'verbos-favoritos-b1',
          'Verbos Phrasal: Look After, Turn On, etc.',
          18,
          'Imagina frases cortas que en realidad hacen varias cosas: "turn off" no es solo "apagar", es una combinación mágica. Cada verbo + palabra = una nueva acción.',
          'Los verbos phrasal son como códigos secretos: "look after" = cuidar, "run out of" = quedarse sin, "turn off" = apagar.',
          [
            'give up: rendirse / dejar',
            'look forward to: esperar con ansias',
            'run out of: quedarse sin',
            'put off: postergar',
            'turn on/off: encender/apagar',
          ],
          'Los verbos phrasal (verb + adverb/preposition) crean significados diferentes a la suma de sus partes. Son esenciales en inglés coloquial.',
          'verb + particle = new meaning',
          [
            '"Don\'t give up!" (no te rindas)',
            '"I look forward to the weekend" (espero con ansias)',
            '"We ran out of milk" (no queda leche)',
          ],
          [
            'Traducir literalmente cada parte',
            'Creer que son frases idiomáticas sueltas',
            'No memorizar con contexto',
          ],
          [
            'Conversaciones informales',
            'Entender series con diálogos naturales',
            'Comunicación en envíos y pedidos',
          ],
          'Escribe 3 frases usando verbos phrasal sobre tu día. Incluye al menos "turn on" y "run out of".',
          'problema_resuelto',
          ['Escoge situaciones cotidianas', 'Usa el significado correcto', 'Practica con shadowing'],
          [
            { paso: 1, descripcion: 'I turn on the lights when I come home', resultadoParcial: 'turn on = encender' },
            { paso: 2, descripcion: 'I ran out of coffee this morning', resultadoParcial: 'run out of = quedarse sin' },
            { paso: 3, descripcion: 'I look forward to the weekend', resultadoParcial: 'look forward to = esperar con ansias' },
            { paso: 4, descripcion: 'Putting together: "I turned on the TV but ran out of snacks"', resultadoParcial: 'Frase múltiple' },
            { paso: 5, descripcion: 'Verify understanding: "turn on" ≠ "turn off"', resultadoParcial: 'Diferenciación' }
          ],
          '¿Qué significa "give up"?',
          ['phrasal verb', 'give up', 'look forward', 'run out', 'put off'],
          [
            { pregunta: '¿Qué significa "give up"?', respuestaCorrecta: 'Rendirse o dejar de hacer algo', explicacion: 'No te rindas.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo usarías "look forward to"?', respuestaCorrecta: 'Para expresar expectativa positiva', explicacion: 'Espero con ansias.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué son difíciles los verbos phrasal?', respuestaCorrecta: 'Significado no es suma de partes', explicacion: 'El significado cambia completamente.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'will-vs-going-to',
          'Will vs Going to: El Futuro Según el Contexto',
          17,
          'Imagina dos tipos de futuro: lo que ya decidiste (going to) y lo que acabas de decidir ahora (will). "I am going to marry" vs "I will help you".',
          'Will es como una promesa en el momento de hablar. Going to es como un plan ya hecho.',
          [
            'Going to: planes ya decididos (evidencia, decisión previa)',
            'Will: decisiones espontáneas, promesas, predicciones sin evidencia',
            'Going to se forma: am/is/are + going to + infinitivo',
            'Will se forma: will + infinitivo',
          ],
          'Will expresa decisiones espontáneas, promesas y predicciones. Going to expresa planes ya decididos y predicciones con evidencia actual.',
          'am/is/are + going to | will',
          [
            '"I will help you!" (decisión espontánea)',
            '"I am going to travel tomorrow" (plan ya hecho)',
            '"It\'s going to rain" (evidencia: ves nubes)',
          ],
          [
            'Usar will para planes preestablecidos',
            'Confundir will con going to en promesas',
            'No usar predicción con evidencia',
          ],
          [
            'Conversaciones de futuro',
            'Negocios: pronósticos y planes',
            'Pronunciación natural de contracciones',
          ],
          'Describe 3 situaciones: (1) un plan que ya decidiste, (2) una promesa ahora, (3) una predicción con evidencia.',
          'ejercicio_contextualizado',
          ['Usa "going to" para planes', 'Usa "will" para promesas', 'Usa "going to" para predicciones'],
          [
            { paso: 1, descripcion: 'Plan: "I am going to visit my friend tomorrow"', resultadoParcial: 'going to (plan hecho)' },
            { paso: 2, descripcion: 'Promesa: "I will call you later"', resultadoParcial: 'will (decisión momento)' },
            { paso: 3, descripcion: 'Evidencia: "Look at those clouds - it\'s going to rain"', resultadoParcial: 'going to (evidencia visual)' },
            { paso: 4, descripcion: 'Verify: "I will buy milk" (decisión) vs "I am going to buy milk" (plan)', resultadoParcial: 'Diferencia clara' },
            { paso: 5, descripcion: 'Shadowing: practica pronunciación de contracciones', resultadoParcial: 'Naturalización' }
          ],
          '¿Cuál usarías para una promesa?',
          ['will', 'going to', 'future', 'promise', 'plan'],
          [
            { pregunta: '¿Qué diferencia hay entre "will" y "going to"?', respuestaCorrecta: 'Will es decisión espontánea; going to es plan preestablecido', explicacion: 'Decisión vs intención.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Qué usas para predecir viendo nubes?', respuestaCorrecta: 'Going to', explicacion: 'Evidencia visual actual.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo usarías "will" para una promesa?', respuestaCorrecta: 'I will help you', explicacion: 'Promesa/ofrecimiento.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'sustantivos-contables',
          'Sustantivos Contables vs Incontables',
          19,
          'Imagina que contas cosas: "una manzana" (contable), "agua" (incontable). Los contables vienen con dedos (uno, dos, tres), los incontables con cuantificadores (mucho, poco).',
          'Los sustantivos contables son como monedas: puedes tener 1, 2, 3. Los incontables son como el aire: no puedes tener "1 aire", dices "mucho aire".',
          [
            'Contables: se pueden contar (un libro, dos libros)',
            'Incontables: no se pueden contar (agua, tiempo, dinero)',
            'Muchos: many (contables), much (incontables)',
            'Pocos: few (contables), little (incontables)',
          ],
          'Los sustantivos contables pueden contarse individualmente (one apple, two apples). Los incontables son masivos (some water, much time).',
          'contables: some, any, how many | incontables: some, any, how much',
          [
            '"two cars, three houses" (contables)',
            '"some water, much time" (incontables)',
            '"How many books?" vs "How much milk?"',
          ],
          [
            'Usar "much" con contables',
            'Creer que todos los sustantivos son contables',
            'No usar cuantificadores correctos',
          ],
          [
            'Conversaciones de compras',
            'Redacción descriptiva',
            'Cálculos de inventario',
          ],
          'Corrige este diálogo: "How much books do you have? I have much books."',
          'problema_resuelto',
          ['Usa "how many" para contables', 'Usa "many" para plural', 'No necesitas artículo'],
          [
            { paso: 1, descripcion: 'How much → How many (pregunta sobre contables)', resultadoParcial: 'Correcto: How many' },
            { paso: 2, descripcion: 'much → many (para contables en plural)', resultadoParcial: 'Correcto: many books' },
            { paso: 3, descripcion: 'Putting together: "How many books do you have? I have many books."', resultadoParcial: 'Grammar fix' },
            { paso: 4, descripcion: 'Alternative: "How much money do you have? I have much money."', resultadoParcial: 'Incontable correcto' },
            { paso: 5, descripcion: 'Verify: contables se cuentan, incontables se miden', resultadoParcial: 'Distinción clara' }
          ],
          '¿Cómo preguntarías por agua (incontable)?',
          ['contable', 'incontable', 'many', 'much', 'how many'],
          [
            { pregunta: '¿Qué sustantivo es contable?', respuestaCorrecta: 'Book (se puede: one book, two books)', explicacion: 'Libros se pueden contar.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué sustantivo es incontable?', respuestaCorrecta: 'Water (no decimos "one water")', explicacion: 'Agua no se cuenta.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué usas con contables en preguntas?', respuestaCorrecta: 'How many / any / some', explicacion: 'Contables cuentan.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'adjetivos-comparativos',
          'Comparativos y Superlativos: Más, Menos y el Mejor',
          21,
          'Imagina una carrera: tú eres más rápido, tu amigo es el más rápido. Los comparativos comparan dos, los superlativos eligen el mejor de muchos.',
          'Comparativo = escala de 2 elementos. Superlativo = el extremo de una escala. "Tall → taller → el más alto".',
          [
            'Comparativo: -er (tall → taller), más/menos + largo',
            'Superlativo: -est (tall → tallest), el más/la más + largo',
            'Más de 2 sílabas: more/big, most/big',
            'Palabras irregulares: good → better → best',
          ],
          'Los comparativos comparan dos elementos (más/menos). Los superlativos indican el extremo en un grupo (el/la más/menos).',
          'Comparative: -er/-est or more/most',
          [
            '"Taller" = comparativo de tall (más alto)',
            '"The tallest" = superlativo (el más alto de muchos)',
            '"More interesting" = para 3+ sílabas',
          ],
          [
            'Usar -er/-est para palabras de 3+ sílabas',
            'Confundir "more" y "most"',
            'No usar irregulars correctamente',
          ],
          [
            'Comparación de productos',
            'Opiniones en debates',
            'Descripciones de habilidades',
          ],
          'Compara 2 personas: tú y un amigo. Describe 3 diferencias usando comparativos y 1 usando superlativo.',
          'problema_resuelto',
          ['Piensa en estaturas, habilidades, intereses', 'Usa -er/-est o more/most', 'Verifica forma correcta'],
          [
            { paso: 1, descripcion: 'Comparativo: "I am taller than my friend"', resultadoParcial: '-er + than' },
            { paso: 2, descripcion: 'Comparativo: "She is more intelligent than me"', resultadoParcial: 'more + than' },
            { paso: 3, descripcion: 'Comparativo: "This book is more interesting than that one"', resultadoParcial: 'more + than' },
            { paso: 4, descripcion: 'Superlativo: "My friend is the tallest in class"', resultadoParcial: 'the + -est' },
            { paso: 5, descripcion: 'Irregular: "I am better at sports"', resultadoParcial: 'good → better' }
          ],
          '¿Cómo dirías "El más rápido de todos"?',
          ['comparativo', 'superlativo', 'más', 'menos', 'than'],
          [
            { pregunta: '¿Cómo se forma el comparativo de "tall"?', respuestaCorrecta: 'taller', explicacion: '-er para 1 sílaba.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo se forma el superlativo de "intelligent"?', respuestaCorrecta: 'the most intelligent', explicacion: 'more/most para 3+ sílabas.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué usas después de un comparativo?', respuestaCorrecta: 'than', explicacion: 'Comparación requiere "than".', tipoMemoria: 'factual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: '¿Qué significa "give up"?', respuestaCorrecta: 'Rendirse o dejar de hacer algo', explicacion: 'No te rindas.', tipoMemoria: 'factual' },
        { pregunta: '¿Qué diferencia hay entre "will" y "going to"?', respuestaCorrecta: 'Will es decisión espontánea; going to es plan preestablecido', explicacion: 'Decisión vs intención.', tipoMemoria: 'conceptual' },
        { pregunta: '¿Cómo dirías "El más rápido de todos"?', respuestaCorrecta: 'The fastest of all', explicacion: 'Superlativo con -est.', tipoMemoria: 'factual' },
      ],
    },
    {
      id: 'academic-english-b2',
      titulo: 'B2: Academic English - Para Estudios Superiores',
      orden: 4,
      spacedReviewSchedule: ['día 5', 'día 8', 'día 14', 'día 24'],
      lecciones: [
        leccion(
          'used-to-b2',
          'Used to: Cosas del Pasado que Cambiaron',
          20,
          'Imagina que eras un niño y comías cereal todos los días, pero ahora no. "Used to" expresa esas costumbres del pasado que ya no existen.',
          'Used to es como un álbum de fotos: muestra lo que "solía ser" antes, aunque ya no lo es.',
          [
            '"I used to play football" = solía jugar fútbol (ya no)',
            'Para costumbres pasadas que han cambiado',
            'Pregunta: "Did you use to...?"',
            'Negación: "I didn\'t use to..."',
          ],
          'Used to describe expresa hábitos del pasado que ya no ocurren. Se usa con "did" para preguntas y negaciones.',
          'used to + verb (base)',
          [
            '"I used to live in Arequipa" (ya no vivo allí)',
            '"She didn\'t use to cook" (antes no cocinaba, pero ahora sí)',
            '"Did you use to smoke?" "No, I never used to smoke"',
          ],
          [
            'Confundir con past simple para acciones concluidas',
            'No usar "did" en preguntas/negaciones',
            'Olvidar que es "used to" no "use to"',
          ],
          [
            'Narración de cambios personales',
            'Comparación de etapas de vida',
            'Conversaciones sobre evolución personal',
          ],
          'Describe 3 cosas que solías hacer cuando eras niño pero ya no haces. Usa "used to".',
          'ejercicio_contextualizado',
          ['Piensa en actividades de la infancia', 'Contrasta con ahora', 'Usa estructura correcta'],
          [
            { paso: 1, descripcion: 'I used to play with toy cars when I was little', resultadoParcial: 'Hábito infantil' },
            { paso: 2, descripcion: 'Now I play video games instead (contrast)', resultadoParcial: 'Cambio de actividad' },
            { paso: 3, descripcion: 'I used to wake up early but now I sleep late', resultadoParcial: 'Hábito de horario' },
            { paso: 4, descripcion: 'Verification: used to = solía (pasado que cambió)', resultadoParcial: 'Entendimiento claro' },
          ],
          '¿Qué diferencia hay entre "used to" y "would"?',
          ['used to', 'past habit', 'change', 'would', 'memory'],
          [
            { pregunta: '¿Qué significa "I used to play guitar"?', respuestaCorrecta: 'Solía tocar guitarra pero ya no', explicacion: 'Hábito pasado que cambió.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo formas la pregunta?', respuestaCorrecta: 'Did you use to + verb?', explicacion: 'Con did en pasado.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué usarías "used to" en una entrevista?', respuestaCorrecta: 'Para contrastar experiencia pasada con presente', explicacion: 'Evolución personal.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'first-second-third',
          'First, Second, Third Conditionals: Condicionales Completos',
          24,
          'Imagina escenarios hipotéticos: "Si hubiera estudiado, habría aprobado". Los condicionales son como simulacros: pruebas de "qué pasaría si".',
          'Los condicionales son como ramificaciones de un árbol: each one leads to a different outcome depending on probability.',
          [
            'First: real/probable ("If I study, I will pass")',
            'Second: unreal/current ("If I studied, I would pass")',
            'Third: unreal/past ("If I had studied, I would have passed")',
            'Zero: general truths ("If you heat ice, it melts")',
          ],
          'Los condicionales expresan hipótesis y sus consecuencias. First = probable, Second = irreal actual, Third = irreal pasado.',
          'If + condición, resultado',
          [
            '"If it rains, I will stay inside" (first - probable)',
            '"If I were rich, I would travel" (second - irreal)',
            '"If I had studied, I would have passed" (third - pasado irreal)',
          ],
          [
            'Confundir segundas y terceras condiciones',
            'No usar Would en segundas',
            'Olvidar haber en terceras',
          ],
          [
            'Planificación y análisis de riesgos',
            'Expresión de arrepentimientos y esperanzas',
            'Redacción académica con matices de probabilidad',
          ],
          'Reescribe: "Si no hubiera estudiado, no habría aprobado" usando first conditional (haciendo real la situación).',
          'problema_resuelto',
          ['Reconoce tercera como pasado irreal', 'Transforma a real/probable', 'Mantén coherencia'],
          [
            { paso: 1, descripcion: 'Understand: "If I had studied, I would have passed" (3rd)', resultadoParcial: 'Irreal pasado' },
            { paso: 2, descripcion: 'Transforma a real: "If I study, I will pass"', resultadoParcial: '1st condicional' },
            { paso: 3, descripcion: 'Verify: "If you study hard, you will succeed"', resultadoParcial: 'Transformación correcta' },
            { paso: 4, descripcion: 'Contrast: 3rd = arrepentimiento; 1st = motivación', resultadoParcial: 'Matiz semántico' },
          ],
          '¿Qué condicional usarías para un sueño imposible?',
          ['first conditional', 'second conditional', 'third conditional', 'zero', 'if'],
          [
            { pregunta: '¿Qué condicional es "If I won the lottery, I would travel"?', respuestaCorrecta: 'Second (irreal actual)', explicacion: 'Won = pasado, but para hipótesis.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué condicional es "If you heat water to 100°C, it boils"?', respuestaCorrecta: 'Zero (verdad general)', explicacion: 'Verdad universal.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué usas para arrepentimiento del pasado?', respuestaCorrecta: 'Third conditional', explicacion: 'Had + participio.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'reported-speech-b2',
          'Reported Speech: Cuando Repites lo que Dijo',
          22,
          'Imagina que le cuentas a un amigo lo que otra persona dijo. "María dijo que vendría". El reported speech traslada la información del presente al pasado.',
          'El reported speech es como un teléfono descompasado: el mensaje se distorsiona al pasar de persona a persona.',
          [
            'Backshift: presente → pasado (do → did, will → would)',
            'Pronombres cambian: I → he/she, this → that',
            'Tiempos cambian: am/is/are → was/were',
            'Verbos: have gotta → had got',
          ],
          'El reported speech (voz indirecta) reproduce lo que dijo alguien, cambiando tiempos verbales y pronombres al pasado.',
          '"He said that..." + pasado',
          [
            '"I will go" → He said he would go',
            '"I am happy" → He said he was happy"',
            '"I live here" → He said he lived here',
          ],
          [
            'No hacer backshift cuando el reporte es actual',
            'Confundir "did" con "said"',
            'No cambiar pronombres',
          ],
          [
            'Replicación de conversaciones',
            'Noticias y testimonios',
            'Narración académica de hechos',
          ],
          'Si alguien dice "I am studying medicine at university", ¿cómo lo dirías tú?',
          'ejercicio_contextualizado',
          ['Aplica backshift: am → was', 'Cambia pronombre: I → he', 'Usa "said that"'],
          [
            { paso: 1, descripcion: 'Identifica verbo: "am studying" (present continuous)', resultadoParcial: 'Tiempo original' },
            { paso: 2, descripcion: 'Backshift: am → was, studying → studying', resultadoParcial: 'past continuous' },
            { paso: 3, descripcion: 'Pronombre: I → he', resultadoParcial: 'cambio de sujeto' },
            { paso: 4, descripcion: 'Result: "He said he was studying medicine at university"', resultadoParcial: 'Reported speech correcto' },
          ],
          '¿Por qué el reported speech "backshifts" el tiempo?',
          ['reported speech', 'backshift', 'said', 'would', 'was'],
          [
            { pregunta: '¿Cómo se forma el reported speech con "I will go"?', respuestaCorrecta: 'He said he would go', explicacion: 'Will → would.', tipoMemoria: 'factual' },
            { pregunta: '¿Cambia el pronombre "I" en reported speech?', respuestaCorrecta: 'Sí, a "he" o "she"', explicacion: 'Depende del sujeto.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué usamos reported speech?', respuestaCorrecta: 'Para relatar lo que dijo otra persona', explicacion: 'Comunicación indirecta.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'relative-clauses',
          'Relative Clauses: La Coma que Une Ideas',
          23,
          'Imagina frases que añaden información extra con una coma: "Mi hermano, que vive en Madrid, es médico". Las relative clauses son como extensiones que dan más detalles.',
          'Las relative clauses son como adjetivos largos: "La casa" vs "La casa que está en la colina".',
          [
            'Who: personas ("the man who helped me")',
            'Which: cosas ("the book which I read")',
            'That: personas o cosas ("the house that I bought")',
            'Where: lugares ("the city where I live")',
            'When: tiempo ("the day when I met her")',
          ],
          'Las relative clauses (cláusulas relativas) añaden información descriptiva a un sustantivo usando who, which, that, where, when.',
          'Sustantivo + who/which/that + información',
          [
            '"The man who helped me was kind" (who = personas)',
            '"The book which I read was interesting" (which = cosas)',
            '"The place where I study is quiet" (where = lugares)',
          ],
          [
            'Olvidar coma en relative clause no restrictiva',
            'Confundir who/which/that',
            'No mantener el mismo sujeto',
          ],
          [
            'Descripciones detalladas en narración',
            'Redacción académica con precisión',
            'Biografías y perfiles',
          ],
          'Escribe una frase sobre un lugar importante para ti, usando "where" y una persona usando "who".',
          'ejercicio_contextualizado',
          ['Piensa en lugar y persona', 'Usa conectores correctos', 'Mantén coherencia'],
          [
            { paso: 1, descripcion: 'Lugar: "The park where I first played soccer"', resultadoParcial: 'where = lugar' },
            { paso: 2, descripcion: 'Persona: "The teacher who inspired me"', resultadoParcial: 'who = persona' },
            { paso: 3, descripcion: 'Combined: "The teacher who inspired me teaches at the school where I studied"', resultadoParcial: 'Doble relative clause' },
            { paso: 4, descripcion: 'Verify: who=persona, which=cosa, where=lugar', resultadoParcial: 'Concordancia correcta' },
          ],
          '¿Qué palabra usarías para describir una persona?',
          ['relative clause', 'who', 'which', 'that', 'where'],
          [
            { pregunta: '¿Qué relative clause describes a person?', respuestaCorrecta: 'Who', explicacion: 'Who se refiere a personas.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué uses para un lugar?', respuestaCorrecta: 'Where', explicacion: 'Where se refiere a lugares.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué usarías "that"?', respuestaCorrecta: 'Para personas o cosas de forma flexible', explicacion: 'That = ambos usos.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'gerundio-infinitive',
          'Gerundio vs Infinitivo: La Forma -ing o "to + verb"',
          24,
          'Imagina que un verbo puede tener dos formas: "swimming" (gerundio, cosa en sí) o "to swim" (infinitivo, acción a realizar). Dependiendo del otro verbo, uno o el otro.',
          'Es como un menú: "enjoy swimming" (placer) vs "want to swim" (intención). Cada verbo elige su compañero.',
          [
            'Gerundio (-ing): después de "enjoy", "avoid", "consider"',
            'Infinitivo (to + verb): después de "want", "decide", "hope"',
            'Algunos verbos: ambos (begin, forget, remember, stop)',
            'Ambigüedad: "I stopped smoking" vs "I stopped to smoke"',
          ],
          'El gerundio (-ing) y el infinitivo (to + verb) son formas no personales del verbo. Dependen del verbo que los introduce: gozar + ing, querer + to.',
          'verb + gerund OR verb + to-infinitive',
          [
            '"I enjoy swimming" (placer)',
            '"I want to swim" (intención)',
            '"I stopped smoking" (dejé de fumar)',
            '"I stopped to smoke" (paré para fumar)',
          ],
          [
            'Confundir gerundio con infinitivo',
            'No memorizar pares de verbos',
            'Olvidar ambigüedad en "stop"',
          ],
          [
            'Descripciones precisas en textos',
            'Expresión de intenciones vs hábitos',
            'Redacción académica con matices',
          ],
          'Corrige: "I enjoy to read books" y "I decided reading the book".',
          'problema_resuelto',
          ['Recuerda preferencias usan gerundio', 'Decisiones usan infinitivo', 'Verifica verbo según estructura'],
          [
            { paso: 1, descripcion: 'I enjoy to read → should be: I enjoy reading', resultadoParcial: 'enjoy + gerundio' },
            { paso: 2, descripcion: 'I decided reading → should be: I decided to read', resultadoParcial: 'decide + infinitivo' },
            { paso: 3, descripcion: 'Verify with memory: "I love to dance" vs "swimming is fun"', resultadoParcial: 'Doble verificación'},
            { paso: 4, descripcion: 'Mnemonic: ENJOY ends in -Y → use Y-ing (gerund)', resultadoParcial: 'Truco mnemotécnico'},
            { paso: 5, descripcion: 'Putting together: "I enjoy reading but decided to study"', resultadoParcial: 'Ambos casos' }
          ],
          '¿Por qué "stop + gerundio" difiere de "stop + infinitive"?',
          ['gerund', 'infinitive', 'enjoy', 'want', 'decide'],
          [
            { pregunta: '¿Después de "enjoy" usas gerundio o infinitivo?', respuestaCorrecta: 'Gerundio (-ing)', explicacion: 'Enjoy + verb-ing.', tipoMemoria: 'factual' },
            { pregunta: '¿Después de "want" usas gerundio o infinitivo?', respuestaCorrecta: 'Infinitivo (to + verb)', explicacion: 'Want + to + verb.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué significa "I stopped smoking"?', respuestaCorrecta: 'Dejé de fumar (gerundio = cosa)', explicacion: 'Acción que dejé.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'linking-words-b2',
          'Linking Words: Conectores para Textos Coherentes',
          20,
          'Imagina escribir un texto donde cada frase salta sin conexión. Los linking words son puentes: "firstly", "however", "finally". Sin ellos, tu texto es un salto sin aterrizaje.',
          'Los conectores son como vías férreas: "Addition" (and) = vías paralelas, "Contrast" (but) = desvío, "Cause" (because) = ramal que lleva a causa.',
          [
            'Addition: furthermore, moreover, in addition',
            'Contrast: however, on the other hand, nevertheless',
            'Cause: because, since, due to',
            'Result: therefore, consequently, as a result',
            'Example: for instance, such as, namely',
          ],
          'Los linking words (conectores) unen ideas en textos, mostrando relaciones de adición, contraste, causa-efecto y ejemplo.',
          'n/a',
          [
            '"Furthermore, the data shows..." (adición)',
            '"However, the study was limited" (contraste)',
            '"As a result, we concluded..." (resultado)',
          ],
          [
            'Usar siempre "and" en lugar de conectores variados',
            'No usar conectores académicos formales',
            'Confundir "however" con "although"',
          ],
          [
            'Ensayos académicos',
            'Informes profesionales',
            'Presentaciones formales',
          ],
          'Escribe 2 párrafos sobre el cambio climático usando al menos 3 conectores diferentes.',
          'ejercicio_contextualizado',
          ['Planifica 2 párrafos', 'Usa conectores: addition, contrast, result', 'Revisa coherencia'],
          [
            { paso: 1, descripcion: 'Párrafo 1: "Climate change is real. Furthermore, data confirms it."', resultadoParcial: 'Adición' },
            { paso: 2, descripcion: 'Párrafo 2: "However, some deny it. Nevertheless, action is needed."', resultadoParcial: 'Contraste' },
            { paso: 3, descripcion: 'Conclusión: "As a result, governments must act."', resultadoParcial: 'Resultado' },
            { paso: 4, descripcion: 'Verification: coherencia con conectores', resultadoParcial: 'Texto fluido' },
          ],
          '¿Qué conector usarías para una contradicción?',
          ['linking words', 'however', 'furthermore', 'therefore', 'because'],
          [
            { pregunta: '¿Qué conector indica adición?', respuestaCorrecta: 'Furthermore / Moreover / In addition', explicacion: 'Añade información.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué conector indica contraste?', respuestaCorrecta: 'However / Nevertheless / On the other hand', explicacion: 'Contrasta ideas.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué conector indica resultado?', respuestaCorrecta: 'Therefore / Consequently / As a result', explicacion: 'Resultado de acción.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'voz-activa-pasiva-b2',
          'Voz Pasiva: The Action is Done by Someone',
          23,
          'Imagina que no importa quién hizo algo, solo que fue hecho. "La carta fue escrita" (no importa quién). La voz pasiva enfoca en la acción, no en el agente.',
          'La voz activa es como "Yo hice" y la pasiva es como "Fue hecho". En pasiva, el verbo cambia a "ser + participio".',
          [
            'Forma: to be + past participle',
            'Objetivo pasa a sujeto: "The letter was written by John"',
            'Útil cuando el agente no importa o es desconocido',
            'En académico: "The experiment was conducted..."',
          ],
          'La voz pasiva construye el verbo con "to be" + participio pasado. El sujeto recibe la acción, no la realiza.',
          'was/were + verb-ed (participio)',
          [
            '"The house was built in 1990" (pasiva sin agente)',
            '"The experiment was conducted by researchers" (pasiva con agente)',
            '"The results were analyzed" (plural)',
          ],
          [
            'Confundir pasiva con "ser" + adjetivo',
            'No concordar el participio con el sujeto',
            'Omitir agente cuando es importante',
          ],
          [
            'Redacción científica formal',
            'Descripciones de procesos históricos',
            'Reportes de investigación',
          ],
          'Construye 3 frases en voz pasiva sobre un experimento escolar.',
          'ejercicio_contextualizado',
          ['Identifica sujeto, verbo, objeto', 'Usa was/were + participio', 'Verifica concordancia'],
          [
            { paso: 1, descripcion: 'The hypothesis was tested by students', resultadoParcial: 'was + tested' },
            { paso: 2, descripcion: 'The data was collected using sensors', resultadoParcial: 'was + collected' },
            { paso: 3, descripcion: 'The results were analyzed with software', resultadoParcial: 'were + analyzed'},
            { paso: 4, descripcion: 'Passive voice: action before agent', resultadoParcial: 'Estructura pasiva'},
            { paso: 5, descripcion: 'Active contrast: "Students tested the hypothesis"', resultadoParcial: 'Voz activa'},
          ],
          '¿Por qué usarías la voz pasiva en un informe científico?',
          ['voz pasiva', 'was', 'were', 'participio', 'agente'],
          [
            { pregunta: '¿Cómo se forma la voz pasiva?', respuestaCorrecta: 'was/were + past participle', explicacion: 'To be + verbo terminado.', tipoMemoria: 'factual' },
            { pregunta: '¿Cuál es el sujeto en "The letter was written"?', respuestaCorrecta: 'letter (recibe la acción)', explicacion: 'Sujeto pasivo.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué usar voz pasiva sin mencionar el agente?', respuestaCorrecta: 'Cuando el agente no importa o es desconocido', explicacion: 'Enfoque en acción, no quien la realizó.', tipoMemoria: 'conceptual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: '¿Qué diferencia hay entre "used to" y "would"?', respuestaCorrecta: 'Used to describe expresa hábitos pasados; would solo para acciones recurrentes', explicacion: '"I used to live" (cambio) vs "I would play" (repetición).', tipoMemoria: 'conceptual' },
        { pregunta: '¿Qué condicional usas para "Si tuviera dinero, viajaría"?', respuestaCorrecta: 'Segundo condicional (irreal actual)', explicacion: 'Tuviera = subjuntivo pasado, would = irreal.', tipoMemoria: 'factual' },
        { pregunta: '¿Cómo se dice "El libro fue leído por mí" en voz pasiva?', respuestaCorrecta: 'The book was read by me', explicacion: 'was + participio.', tipoMemoria: 'factual' },
      ],
    },
    {
      id: 'proficient-english-c1',
      titulo: 'C1: Proficient English - Dominio Total',
      orden: 5,
      spacedReviewSchedule: ['día 6', 'día 10', 'día 18', 'día 30'],
      lecciones: [
        leccion(
          'inversiones',
          'Inversión y Estructuras Complejas: Beyond Basic English',
          26,
          'Imagina que para enfatizar algo, cambias el orden: "Little does he know...". La inversión es como un volteo: toma una estructura normal y la da vuelta para énfasis.',
          'La inversión es como un acorde musical dissonante que se resuelve: "Never have I seen..." suena inusual pero es potente.',
          [
            'Inversión negativa: "Never have I..."',
            'Inversión con "such": "Such is life"',
            'Estructuras: "Had I studied, I would have passed"',
            'Cláusulas condicionales invertidas',
          ],
          'La inversión en inglés invierte el orden normal de sujeto-verbo para lograr énfasis o estilo. Se usa en contextos formales y literarios.',
          'Not-SV, SV-Not',
          [
            '"Never have I seen such beauty"',
            '"Rarely does he arrive late"',
            '"Had I known, I would have helped"',
          ],
          [
            'Usar solo en contextos formales',
            'No invertir sin razón estilística',
            'Confundir con estructuras condicionales',
          ],
          [
            'Escritura académica avanzada',
            'Literatura y análisis de textos',
            'Discursos formales y presentaciones',
          ],
          'Escribe 3 frases enfáticas sobre una decisión importante, usando al menos una inversión.',
          'ejercicio_contextualizado',
          ['Piensa en decisiones clave', 'Usa estructuras normales', 'Añade inversión para énfasis'],
          [
            { paso: 1, descripcion: 'Normal: "I have never seen such dedication"', resultadoParcial: 'Orden estándar' },
            { paso: 2, descripcion: 'Inversión: "Never have I seen such dedication"', resultadoParcial: 'Énfasis logrado' },
            { paso: 3, descripcion: 'Condicional: "Had I invested early, I would be rich"', resultadoParcial: 'Inversión causal' },
            { paso: 4, descripcion: 'Final: "Such is the power of compound interest"', resultadoParcial: 'Inversión enfática'},
            { paso: 5, descripcion: 'Verification: all invert properly for style', resultadoParcial: 'Maestría avanzada'}
          ],
          '¿Cuándo usarías la inversión en inglés?',
          ['inversión', 'énfasis', 'formal', 'such', 'never'],
          [
            { pregunta: '¿Qué significa "Never have I seen such beauty"?', respuestaCorrecta: 'Nunca he visto tal belleza (énfasis)', explicacion: 'Inversión para énfasis negativo.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo invertirías "I have never traveled abroad"?', respuestaCorrecta: 'Never have I traveled abroad', explicacion: 'Invierte negación + verbo.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué se usa la inversión?', respuestaCorrecta: 'Para añadir énfasis o estilo', explicacion: 'Rompe con el orden normal.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'subjunto-c1',
          'Modo Subjuntivo: La Realidad de lo Posible',
          25,
          'Imagina expresar deseos, dudas o posibilidades: "Es importante que estudies". El subjuntivo es como abrir una puerta a múltiples realidades.',
          'El subjuntivo es como una encrucijada: en lugar de afirmar lo que es, expresa lo que podría ser.',
          [
            'Después de emociones: "I suggest that he studies"',
            'Deseo no real: "If I were rich..."',
            'Duda: "I doubt that she knows"',
            'Impersonal: "It is essential to..."',
          ],
          'El subjuntivo expresa deseo, duda, emoción o posibilidad. En inglés moderno se usa con "that" + presente para indicar incertidumbre o deseo.',
          '"It is important that..." + presente',
          [
            '"It is essential that you study" (importancia)',
            '"I wish I were taller" (deseo irreal)',
            '"If I were you, I would..." (consejo)',
          ],
          [
            'Confundir con pasado simple',
            'No usar después de adjetivos emocionales',
            'Olvidar "were" en subjuntivo irreal',
          ],
          [
            'Discursos académicos formales',
            'Expresión de emociones y juicios',
            'Escritura literaria y filosófica',
          ],
          'Expresa 3 emociones sobre tu futuro: una esperanza, un miedo y una duda. Usa el subjuntivo.',
          'problema_resuelto',
          ['Piensa en tus emociones futuras', 'Usa "It is/was + adjetivo + that"', 'Verifica estructura'],
          [
            { paso: 1, descripcion: 'Hope: "It is hopeful that I will succeed"', resultadoParcial: 'Esperanza' },
            { paso: 2, descripcion: 'Fear: "It is worrying that I might fail"', resultadoParcial: 'Miedo' },
            { paso: 3, descripcion: 'Doubt: "I doubt that he studies enough"', resultadoParcial: 'Duda' },
            { paso: 4, descripcion: 'Subjunctive "were": "If I were you..."', resultadoParcial: 'Irreal'},
            { paso: 5, descripcion: 'Verification: all express uncertainty/desire', resultadoParcial: 'Subjuntivo correcto'}
          ],
          '¿Por qué usarías "If I were" en vez de "If I was"?',
          ['subjuntivo', 'were', 'wish', 'doubt', 'essential'],
          [
            { pregunta: '¿Después de qué se usa el subjuntivo?', respuestaCorrecta: 'Emociones, deseos, dudas', explicacion: 'Expresa incertidumbre.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo dirías "Es importante que estudies"?', respuestaCorrecta: 'It is important that you study', explicacion: 'Subjuntivo con "that".', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué "were" en "If I were you"?', respuestaCorrecta: 'Subjuntivo para irreal', explicacion: 'No es real, es consejo hipotético.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'conciliacion-discursos',
          'Coordinación de Discursos: Cohesionar un Texto Complejo',
          23,
          'Imagina tejer un tapiz: cada hilo es una idea, y los conectores son los puntos de cruce. Un texto cohesivo es un tapiz bien tejido.',
          'La cohesión es como un río: debe fluir sin interrupciones. Los conectores son puentes; las referencias son corrientes subterráneas.',
          [
            'Anáfora: repetir palabra al inicio de frases',
            'Catafraasis: invertir orden para estilo',
            'Referencia cruzada: "As mentioned above,..."',
            'Estructura: progresiva, inversa, cíclica',
          ],
          'La cohesión y coherencia coordinan ideas a nivel de discurso mediante conectores, repetición, referencia cruzada y estructura textual.',
          'n/a',
          [
            'Anáfora: "We must act. We must decide. We must change."',
            'Catafraasis: "Not only did she study, but she also taught others."',
            'Referencia: "As stated in section 2..."',
          ],
          [
            'Repetir sin propósito estilístico',
            'No planificar estructura del discurso',
            'Olvidar cohesión interna',
          ],
          [
            'Tesis académicas',
            'Ensayos literarios',
            'Discursos institucionales',
          ],
          'Escribe el esquema de un ensayo sobre "La educación como herramienta de transformación", con al menos 4 cohesionadores.',
          'problema_resuelto',
          ['Planifica introducción-desarrollo-conclusión', 'Usa conectores cohesionadores', 'Asegura coherencia'],
          [
            { paso: 1, descripcion: 'Introducción: "Education transforms society"', resultadoParcial: 'Tesis' },
            { paso: 2, descripcion: 'Primero: "Firstly, education reduces inequality"', resultadoParcial: 'Secuencia' },
            { paso: 3, descripcion: 'Contraste: "However, access is still limited"', resultadoParcial: 'Oposición'},
            { paso: 4, descripcion: 'Conclusión: "Therefore, investment in education is essential"', resultadoParcial: 'Resultado'},
            { paso: 5, descripcion: 'Verification: cohesionadores correctos, coherencia establecida', resultadoParcial: 'Texto cohesivo'},
          ],
          '¿Qué función cumple la anáfora en un texto?',
          ['cohesión', 'coherencia', 'conectores', 'anáfora', 'estructura'],
          [
            { pregunta: '¿Qué conecta cohesión y coherencia?', respuestaCorrecta: 'Cohesión usa recursos textuales; coherencia es relación de sentido', explicacion: 'Superficie vs significado.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Qué es la anáfora?', respuestaCorrecta: 'Repetición de una palabra al inicio de frases', explicacion: 'Crea ritmo y cohesión.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué estructura de discurso es lineal?', respuestaCorrecta: 'Progresiva (introducción a conclusión)', explicacion: 'Orden cronológico de ideas.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'vocabulario-academico-c1',
          'Vocabulario Académico Avanzado: Precisiones Conceptuales',
          24,
          'Imagina tener un cajón de herramientas lingüísticas: "implementar", "facilitar", "constatar". El vocabulario C1 es como tener herramientas específicas para cada tarea intelectual.',
          'El vocabulario académico avanzado es como una caja de herramientas: cada palabra es una herramienta distinta para construir ideas complejas.',
          [
            'Palabras de alta frecuencia académica: analyze, assume, constitute, derive',
            'Sinónimos precisos: facilitate vs help, implement vs do',
            'Colocaciones: strong argument, significant evidence, crucial role',
            'Matices de significado: refute vs deny vs reject',
          ],
          'El vocabulario académico avanzado incluye palabras de alta frecuencia en textos universitarios, con matices precisos y colocaciones específicas.',
          'n/a',
          [
            '"The data facilitates understanding" vs "The data helps understanding"',
            '"The study refutes previous findings" vs "rejects" vs "denies"',
            '"A significant correlation was found" (colocación academic)',
          ],
          [
            'Usar palabras muy generales (good, bad, things)',
            'No aprender colocaciones',
            'Confundir sinónimos con matices distintos',
          ],
          [
            'Redacción académica avanzada',
            'Análisis crítico de textos',
            'Debates intelectuales',
          ],
          'Sustituye estas palabras generales por vocabulario académico: "helps", "shows", "big impact".',
          'ejercicio_contextualizado',
          ['Busca sinónimos precisos', 'Considera matices', 'Mantén fluidez'],
          [
            { paso: 1, descripcion: 'helps → facilitates / assists / contributes to', resultadoParcial: 'Sinónimo académico' },
            { paso: 2, descripcion: 'shows → demonstrates / reveals / indicates', resultadoParcial: 'Verbos precisos' },
            { paso: 3, descripcion: 'big impact → significant influence / substantial effect', resultadoParcial: 'Expresión avanzada' },
            { paso: 4, descripcion: 'Verification: natural en contexto académico', resultadoParcial: 'Vocabulario preciso'},
            { paso: 5, descripcion: 'Example: "The study facilitates understanding... demonstrates significant influence..."', resultadoParcial: 'Texto fluido'}
          ],
          '¿Qué diferencia hay entre "refute" y "reject"?',
          ['vocabulario académico', 'facilitate', 'refute', 'demonstrate', 'significant'],
          [
            { pregunta: '¿Qué tipo de palabras son en vocabulario C1?', respuestaCorrecta: 'Precisas, con matices específicos', explicacion: 'Cada palabra tiene función exacta.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Qué colocación usarías con "evidence"?', respuestaCorrecta: 'Significant evidence / strong evidence', explicacion: 'Colocaciones académicas.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo dirías "muy importante" en académico?', respuestaCorrecta: 'Of paramount importance / Crucial / Significant', explicacion: 'Vocabulario elevado.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'discusiones-y debates',
          'Discusiones y Debates: Expresando Posturas con Precisión',
          25,
          'Imagina defender una idea en inglés: "I firmly believe that..." o "From my perspective...". El debate requiere no solo vocabulario, sino postura y estructura.',
          'Debatir es como un baile: expresar tu posición (paso adelante), escuchar (paso lateral) y responder con precisión (paso atrás).',
          [
            'Expresar opinión: "I firmly believe", "From my perspective"',
            'Conceder punto: "Admittedly", "Granted that"',
            'Refutar: "However", "On the contrary", "This is a misconception"',
            'Concluir: "Therefore", "All things considered"',
          ],
          'Las discusiones en inglés C1 usan expresiones formales para expresar opiniones, conceder puntos, refutar y concluir con precisión y cortesía.',
          'n/a',
          [
            '"Admittedly, the theory has merit"',
            '"However, recent studies refute this claim"',
            '"On the contrary, evidence suggests..."',
          ],
          [
            'No reconocer puntos válidos del adversario',
            'Usar lenguaje demasiado coloquial en debates formales',
            'No tener estructura clara de argumentación',
          ],
          [
            'Debates académicos',
            'Discusiones en entornos profesionales',
            'Negociación intercultural',
          ],
          'Participa en un debate: "Las redes sociales son perjudiciales para la salud mental". Da tu posición, 2 argumentos y 1 refutación.',
          'ejercicio_contextualizado',
          ['Toma posición clara', 'Aporta argumentos con evidencia', 'Refuta con respeto'],
          [
            { paso: 1, descripcion: 'Position: "I firmly believe social media negatively impacts mental health"', resultadoParcial: 'Tesis clara' },
            { paso: 2, descripcion: 'Argumento 1: "Excessive use correlates with anxiety (study, 2023)"', resultadoParcial: 'Dato cuantitativo' },
            { paso: 3, descripcion: 'Argumento 2: "Comparison culture increases depression rates"', resultadoParcial: 'Efecto psicológico'},
            { paso: 4, descripcion: 'Refutación: "Admittedly it connects people, but the costs outweigh benefits"', resultadoParcial: 'Concesión'},
            { paso: 5, descripcion: 'Conclusion: "Therefore, regulation is needed"', resultadoParcial: 'Cierre argumentativo'},
          ],
          '¿Cómo dirías "Por supuesto que sí sabes" con cortesía?',
          ['debate', 'opinión', 'refutación', 'argumento', 'concesión'],
          [
            { pregunta: '¿Cómo expresas una concesión?', respuestaCorrecta: 'Admittedly / Granted that', explicacion: 'Reconoces un punto válido del otro lado.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué expresión usas para empezar una refutación?', respuestaCorrecta: 'However / On the contrary', explicacion: 'Contrastas con la idea anterior.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué es importante conceder puntos en un debate?', respuestaCorrecta: 'Muestra apertura y fortalece el argumento', explicacion: 'Debilidad percibida = fuerzaargumentativa.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'cultura-inglesa-c1',
          'Cultura Inglesa: Idioma y Contexto Sociocultural',
          26,
          'Imagina entender no solo las palabras, sino por qué las dicen. El inglés vivo incluye modismos, ironía, cumplidos indirectas y referencias culturales.',
          'Cultura inglesa es como un manual de instrucciones no escrito: el "sarcasmo", "understatement" y "small talk" son dialectos de la vida cotidiana.',
          [
            'Sarcasmo: decir lo contrario con tono ("Oh great!" en situación mala)',
            'Understatement: minimizar lo grande ("It\'s a bit warm" en día de calor extremo)',
            'Small talk: charlar sobre clima, comida, tiempo',
            'Modismos: "to bite the bullet", "costs an arm and a leg"',
          ],
          'La cultura anglosajona expresa sentimientos a través del sarcasmo, understatement y small talk. Comprender el contexto sociocultural es clave para el nivel C1.',
          'n/a',
          [
            'Sarcasmo: "Fantastic weather!" (cuando llueve)',
            'Understatement: "Not bad" (cuando ganaste una lotería)',
            'Small talk: "Nice weather we\'re having"',
          ],
          [
            'Tomar el sarcasmo como una queja directa',
            'No reconocer el understatement como modéstia',
            'Ignorar el small talk como cortesía social',
          ],
          [
            'Interacción intercultural',
            'Negocios internacionales',
            'Literatura y medios en inglés',
          ],
          'Analiza esta frase: "Well, that\'s just great!" dicho después de que algo saliera mal. ¿Cómo se intenta interpretar el tono?',
          'ejercicio_contextualizado',
          ['Identifica palabras clave de ironía', 'Considera el contexto', 'Interpreta intención', 'Propón respuesta adecuada'],
          [
            { paso: 1, descripcion: 'Palabras: "just great" (superficialmente positivas)', resultadoParcial: 'Contraste' },
            { paso: 2, descripcion: 'Contexto: "algo salió mal"', resultadoParcial: 'Ironía' },
            { paso: 3, descripcion: 'Intención: expresar frustración indirectamente', resultadoParcial: 'Sarcasmo británico'},
            { paso: 4, descripcion: 'Respuesta: "Yeah, totally..." con tono similar', resultadoParcial: 'Reciprocidad cultural'},
            { paso: 5, descripcion: 'Verification: cultural, not literal', resultadoParcial: 'Intercambio socio-cultural'}
          ],
          '¿Qué significa el small talk en la cultura inglesa?',
          ['cultura', 'sarcasmo', 'understatement', 'small talk', 'modismo'],
          [
            { pregunta: '¿Cómo se manifiesta el sarcasmo?', respuestaCorrecta: 'Diciendo lo opuesto con tono', explicacion: 'Ironía verbal.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué es el understatement?', respuestaCorrecta: 'Minimizar algo grande con modestia', explicacion: 'Modéstia cultural.', tipoMemoria: 'factual' },
            { pregunta: '¿Para qué sirve el small talk?', respuestaCorrecta: 'Romper el hielo social', explicacion: 'Cortesía y conexión.', tipoMemoria: 'conceptual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: '¿Cómo invertirías "I have never traveled abroad"?', respuestaCorrecta: 'Never have I traveled abroad', explicacion: 'Inversión de negación para énfasis.', tipoMemoria: 'factual' },
        { pregunta: '¿Por qué usarías "It is important that..." con subjuntivo?', respuestaCorrecta: 'Para expresar una necesidad o valoración subjetiva', explicacion: 'Subjuntivo tras emociones/valoraciones.', tipoMemoria: 'conceptual' },
        { pregunta: '¿Qué conectores usarías para una concesión en un debate?', respuestaCorrecta: 'Admittedly / Granted that', explicacion: 'Reconocer puntos válidos del otro.', tipoMemoria: 'factual' },
      ],
    },
  ],
};
