import { CursoBase, QuizActiveRecall } from '../../tipos';

function leccion(
  id: string,
  titulo: string,
  duracion: number,
  intuicion: string,
  analogia: string,
  pasos: string[],
  definicion: string,
  formula: string | undefined,
  ejemplos: string[],
  errores: string[],
  aplicaciones: string[],
  retoEnunciado: string,
  retoTipo: 'problema_resuelto' | 'ejercicio_contextualizado' | 'simulacion',
  retoPistas: string[],
  retoSolucion: { paso: number; descripcion: string; formulaUsada?: string; resultadoParcial?: string }[],
  retoVerificacion: string,
  palabrasClave: string[],
  quiz: QuizActiveRecall[]
) {
  return {
    id,
    titulo,
    duracionAproximada: duracion,
    explicacionFeynman: {
      intuicionInicial: intuicion,
      analogiaSimple: analogia,
      pasoAPasoIntuitivo: pasos,
    },
    conceptoTecnico: {
      definicionFormal: definicion,
      formulaMatematica: formula,
      ejemplos,
      erroresComunes: errores,
      conexionAplicaciones: aplicaciones,
    },
    retoPractico: {
      tipo: retoTipo,
      enunciado: retoEnunciado,
      pistas: retoPistas,
      solucionPasoAPaso: retoSolucion,
      verificacionActiveRecall: retoVerificacion,
    },
    palabrasClave,
    quizActiveRecall: quiz,
  };
}

export const FisicaCurso: CursoBase = {
  id: 'fisica-neuro',
  nombre: 'Física Viva: Intuición sobre Ecuaciones',
  descripcion: 'Curso de Física para Secundaria donde se descubre el porqué de los fenómenos antes de las fórmulas, usando el Método Feynman.',
  nivelEducativo: 'Secundaria',
  competencias: [
    'Aplicar leyes de Newton en situaciones cotidianas',
    'Resolver problemas de cinemática con intuición física',
    'Entender la termodinámica como flujo de energía',
    'Interpretar resultados físicos en contexto',
    'Desarrollar razonamiento científico crítico',
  ],
  duracionEstimada: '14 meses',
  metodologia: {
    metodoFeynman: true,
    activeRecall: true,
    spacedRepetition: true,
    intuicionAntesFormula: true,
    estrategiasTransversales: [
      'Experimentos mentales antes de fórmulas',
      'Identificación de patrones en fenómenos',
      'Uso de analogías intuitivas',
      'Resolución paso a paso con papel y lápiz digital',
      'Autoevaluación con feedback inmediato',
    ],
  },
  modulos: [
    {
      id: 'cinematica-basica',
      titulo: 'Cinemática: El Viaje del Cohete Curioso',
      orden: 1,
      spacedReviewSchedule: ['día 1', 'día 3', 'día 8', 'día 20'],
      lecciones: [
        leccion(
          'movimiento-rectilini',
          'Movimiento Rectilíneo: Cuando Todo va en Línea Recta',
          20,
          'Imagina que lanzas una pelota hacia adelante. ¿Qué tan rápido se mueve? ¿En qué dirección? Esa es la velocidad. Si cambia la rapidez, eso es aceleración.',
          'Un coche en una autopista: la velocidad indica qué tan rápido avanza, la aceleración es cómo pisar el pedal para ir más rápido.',
          ['Observa: ¿el objeto se mueve o está quieto?', 'Mide qué tan lejos recorre en qué tiempo: velocidad = distancia / tiempo', '¿La velocidad cambia? Si sube o baja, hay aceleración.', 'La aceleración te dice qué tan rápido cambia la velocidad.'],
          'La velocidad es la razón de cambio de posición respecto al tiempo. La aceleración es la razón de cambio de velocidad.',
          'v = d/t ; a = Δv/Δt',
          ['Coche recorre 100m en 5s: v = 20 m/s', 'Coche pasa de 10 m/s a 30 m/s en 4s: a = 5 m/s²'],
          ['Confundir distancia con desplazamiento', 'Olvidar unidades al final', 'Signos incorrectos en aceleración negativa'],
          ['Calcular tiempo de viaje en coche', 'Determinar frenado de un coche', 'Velocidad de caída libre'],
          'Un coche viaja a velocidad constante de 60 km/h durante 2.5 horas. ¿Qué distancia recorre?',
          'problema_resuelto',
          ['Usa v = d/t', 'Despeja d = v × t', 'Sustituye valores'],
          [{ paso: 1, descripcion: 'Identifica la fórmula', formulaUsada: 'v = d/t' }, { paso: 2, descripcion: 'Despeja distancia', resultadoParcial: 'd = v × t' }, { paso: 3, descripcion: 'Sustituye: d = 60 × 2.5', resultadoParcial: 'd = 150 km' }],
          '¿Qué pasa si en lugar de velocidad constante, el coche acelera?',
          ['velocidad', 'aceleración', 'posición', 'tiempo', 'distancia'],
          [
            { pregunta: '¿Qué diferencia hay entre velocidad y aceleración?', respuestaCorrecta: 'Velocidad es distancia/tiempo, aceleración es cambio de velocidad/tiempo.', explicacion: 'La aceleración mide cómo cambia la velocidad con el tiempo.', tipoMemoria: 'conceptual' },
            { pregunta: 'Un objeto recorre 80 metros en 4 segundos. ¿Cuál es su velocidad?', respuestaCorrecta: '20 m/s', explicacion: 'v = 80/4 = 20 metros por segundo.', tipoMemoria: 'procedural' },
            { pregunta: '¿Qué indica una aceleración negativa?', respuestaCorrecta: 'Que la velocidad está disminuyendo', explicacion: 'Aceleración negativa significa frenado o desaceleración.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'movimiento-acelerado',
          'Movimiento Acelerado: El Cohete que Acelera',
          22,
          'Cuando un coche pisa el acelerador, la velocidad sube poco a poco. Esa subida constante es una aceleración uniforme. La distancia no sube lineal, sube al cuadrado del tiempo.',
          'Imagina inflar un globo: al principio sube lento, luego más rápido. La aceleración constante es como una regla de multiplicar la velocidad.',
          ['Usa ecuaciones MRUV: v = v₀ + at', 'x = x₀ + v₀t + ½at²', 'v² = v₀² + 2aΔx', 'Aplica según lo que pida el problema'],
          'El movimiento rectilíneo uniformemente acelerado (MRUV) tiene aceleración constante. Las ecuaciones son: v = v₀ + at; x = x₀ + v₀t + ½at².',
          'v = v₀ + at ; x = x₀ + v₀t + ½at²',
          ['Desde reposo, a = 2 m/s², t = 5s: v = 10 m/s, x = 25 m', 'f = 20 m/s, v₀ = 0, a = 4 m/s²: t = 5s'],
          ['Confundir MRU con MRUV', 'Olvidar el ½ en x = v₀t + ½at²', 'No usar unidades consistentes'],
          ['Lanzamiento de proyectiles', 'Frenado de vehículos', 'Caída libre'],
          'Un coche parte del reposo y acelera a 3 m/s². ¿Qué velocidad alcanzará en 8 segundos? ¿Qué distancia recorrerá?',
          'problema_resuelto',
          ['Usa v = v₀ + at con v₀ = 0', 'Luego usa x = v₀t + ½at²'],
          [{ paso: 1, descripcion: 'v = 0 + 3(8) = 24 m/s', formulaUsada: 'v = v₀ + at' }, { paso: 2, descripcion: 'x = 0 + ½(3)(8²) = 96 m', resultadoParcial: 'x = 96 m' }],
          '¿Qué forma tiene la gráfica de x vs t en MRUV?',
          ['aceleración', 'MRUV', 'velocidad', 'tiempo', 'distancia'],
          [
            { pregunta: 'Un coche acelera a 2 m/s² desde el reposo. ¿Qué velocidad tiene en 5 s?', respuestaCorrecta: '10 m/s', explicacion: 'v = 0 + 2(5) = 10 m/s.', tipoMemoria: 'procedural' },
            { pregunta: '¿Qué forma tiene la distancia vs tiempo en MRUV?', respuestaCorrecta: 'Una parábola (curva cuadrática)', explicacion: 'x = ½at² es una parábola.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Por qué el ½ aparece en x = v₀t + ½at²?', respuestaCorrecta: 'Es el área bajo la gráfica de velocidad en forma de triángulo', explicacion: 'El ½ convierte la Base×Altura del triángulo en área.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'caida-libre',
          'Caída Libre: Cuando la Gravedad No Perdona',
          19,
          'Si dejas caer una moneda y una bala al mismo tiempo en un vacío, llegan juntas. La gravedad acelera todo por igual: 9.8 m/s² hacia el suelo.',
          'Imagina un ascensor cayendo: todo dentro cae a la misma velocidad. No importa el peso, solo el tiempo y la altura.',
          ['La caída libre ignora la resistencia del aire', 'a = g ≈ 9.8 m/s² (hacia abajo)', 'Usa ecuaciones de MRUV con a = g', 'Verifica dirección del movimiento'],
          'La caída libre es el movimiento de un cuerpo bajo la única influencia de la gravedad. La aceleración es g = 9.8 m/s² hacia el centro de la Tierra.',
          'g ≈ 9.8 m/s²',
          ['Lanzar algo hacia arriba: v(t) = v₀ - gt', 'Altura máxima: h = v₀²/(2g)', 'Tiempo de subida = tiempo de bajada'],
          ['Ignorar el sentido de g (positivo/negativo)', 'No considerar el punto más alto (v = 0)', 'Confundir altura con distancia'],
          ['Diseño de paracaídas', 'Ingeniería de seguridad vial', 'Deportes de salto y lanzamiento'],
          'Lanzas una pelota hacia arriba a 20 m/s. ¿Cuánto tarda en volver? ¿Qué altura alcanza?',
          'problema_resuelto',
          ['En el punto más alto, v = 0', 'Usa v = v₀ - gt para tiempo de subida', 'Luego h = v₀t - ½gt²'],
          [{ paso: 1, descripcion: 'Tiempo subida: 0 = 20 - 9.8t → t = 2.04s', formulaUsada: 'v = v₀ - gt' }, { paso: 2, descripcion: 'Altura: h = 20(2.04) - ½(9.8)(2.04²)', resultadoParcial: 'h ≈ 20.4 m' }, { paso: 3, descripcion: 'Tiempo total: 2 × 2.04 = 4.08s', resultadoParcial: '≈ 4.1 segundos' }],
          '¿Por qué en la Tierra real una pelota de papel no cae igual que una roca?',
          ['caída libre', 'gravedad', 'aceleración', 'resistencia del aire', 'proyectil'],
          [
            { pregunta: '¿Qué aceleración tienen todos los objetos en caída libre?', respuestaCorrecta: '9.8 m/s² hacia el suelo', explicacion: 'g es la aceleración de la gravedad cerca de la Tierra.', tipoMemoria: 'factual' },
            { pregunta: '¿En qué instante una pelota lanzada hacia arriba tiene velocidad cero?', respuestaCorrecta: 'En el punto más alto', explicacion: 'La velocidad se anula momentáneamente antes de caer.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Cuánto tarda en caer un objeto desde 5 m (sin velocidad inicial)?', respuestaCorrecta: 'Aproximadamente 1 segundo', explicacion: 'h = ½gt² → t = √(2h/g) = √(10/9.8) ≈ 1s.', tipoMemoria: 'procedural' },
          ]
        ),
        leccion(
          'movimiento-parabolico',
          'Movimiento Parabólico: El Arco de la Flecha Inca',
          24,
          'Cuando lanzas algo al aire con ángulo, la gravedad te tira hacia abajo mientras avanzas recto. El resultado es una curva perfecta: parábola. Como las flechas que disparaban los incas.',
          'Imagina lanzar una piedra desde una colina: mientras sube, la gravedad la frena; al bajar, la acelera. El camino dibuja una parábola.',
          ['Separa movimiento horizontal (constante) y vertical (acelerado)', 'Horizontal: x = v₀cos(θ)t', 'Vertical: y = v₀sin(θ)t - ½gt²', 'Calcula tiempo de vuelo, alcance y altura máxima'],
          'El movimiento parabólico resulta de combinar movimiento horizontal uniforme y vertical acelerado. La trayectoria es una parábola.',
          'R = (v₀² · sin(2θ)) / g ; H = (v₀² · sin²θ) / (2g)',
          ['Lanzamiento a 45° con v₀=20 m/s: R ≈ 40.8 m, H ≈ 10.2 m', 'Ángulo óptimo es 45° para máximo alcance'],
          ['No separar componentes x e y', 'Confundir ángulos con radianes', 'Olvidar la componente vertical en caída'],
          ['Arqueros y flechas', 'Deportes de lanzamiento (javelina)', 'Ingeniería de proyectiles'],
          'Lanzas una flecha a 25 m/s con ángulo de 30°. ¿Cuál es el alcance y la altura máxima? Usa g = 10 m/s².',
          'problema_resuelto',
          ['Descompón v₀ en componentes: v₀x = v₀cos(θ), v₀y = v₀sin(θ)', 'Calcula tiempo de vuelo: t = 2v₀y/g', 'Alcance = v₀x × t'],
          [{ paso: 1, descripcion: 'v₀x = 25cos(30°) ≈ 21.65, v₀y = 25sin(30°) = 12.5', formulaUsada: 'Componentes' }, { paso: 2, descripcion: 't = 2(12.5)/10 = 2.5s', resultadoParcial: 'Tiempo de vuelo = 2.5s' }, { paso: 3, descripcion: 'R = 21.65 × 2.5 = 54.1m', resultadoParcial: 'Alcance ≈ 54 m' }],
          '¿Por qué el ángulo de 45° da el mayor alcance?',
          ['parábola', 'componentes', 'alcance', 'proyectil', 'ángulo'],
          [
            { pregunta: '¿Qué componente de velocidad se mantiene constante en caída libre?', respuestaCorrecta: 'La componente horizontal', explicacion: 'Solo la vertical cambia por la gravedad.', tipoMemoria: 'conceptual' },
            { pregunta: '¿A qué ángulo obtienes el mayor alcance?', respuestaCorrecta: '45°', explicacion: 'Sen(2θ) = 1 cuando 2θ = 90°, es decir θ = 45°.', tipoMemoria: 'factual' },
            { pregunta: 'Si lanzas a 30° y a 60° con la misma velocidad, ¿qué ocurre con el alcance?', respuestaCorrecta: 'Ambos alcanzan el mismo alcance', explicacion: 'Sen(60°) = Sen(30°) porque 2×30° = 60° y 2×60° = 120°, complementos.', tipoMemoria: 'conceptual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: 'Un coche parte del reposo con a = 4 m/s². ¿Qué velocidad tiene en 3 s?', respuestaCorrecta: '12 m/s', explicacion: 'v = 0 + 4(3) = 12 m/s.', tipoMemoria: 'procedural' },
        { pregunta: '¿Qué aceleración tiene un objeto en caída libre (sin resistencia)?', respuestaCorrecta: '9.8 m/s² hacia el suelo', explicacion: 'g = 9.8 m/s² es la aceleración de gravedad.', tipoMemoria: 'factual' },
        { pregunta: '¿Por qué separas movimiento horizontal y vertical en caída libre?', respuestaCorrecta: 'Porque son independientes: solo la vertical cambia', explicacion: 'La gravedad solo afecta al movimiento vertical.', tipoMemoria: 'conceptual' },
      ],
    },
    {
      id: 'dinamica-newton',
      titulo: 'Dinámica: Las Fuerzas que Mueven el Mundo',
      orden: 2,
      spacedReviewSchedule: ['día 2', 'día 6', 'día 12', 'día 25'],
      lecciones: [
        leccion(
          'leyes-newton',
          'Leyes de Newton: Por qué Empujar una Pared te Devuelve el Golpe',
          25,
          'Si empujas una pared, ella te empuja de vuelta con la misma fuerza. Eso es la tercera ley: a toda acción hay reacción opuesta. Y si quieres mover algo, necesitas superar su inercia.',
          'Patear una pelota: tu pie ejerce fuerza (acción), la pelota vuela (reacción). La pelota pesa mucho si es de cemento, poco si es de goma.',
          ['Ley 1: Objeto quieto quiere quedarse quieto. Objeto en movimiento quiere seguir moviéndose.', 'Ley 2: Cuanto más fuerte empujes, más acelera. Cuanto más pesado, menos acelera.', 'Ley 3: Cada empujón tiene un empujón de vuelta del mismo tamaño.'],
          'Ley de Inercia: un cuerpo permanece en reposo o movimiento uniforme si no hay fuerza neta. Ley Fundamental: F = ma. Tercera Ley: acción = reacción.',
          'F = m × a',
          ['Empujar caja de 10 kg con 20 N: a = 2 m/s²', 'Pesar 5 kg, empujar con 15 N: a = 3 m/s²'],
          ['Confundir masa y peso', 'No considerar fuerzas opuestas (fricción)', 'Aplicar tercera ley incorrectamente en sistema'],
          ['Entender por qué los coches necesitan frenos', 'Calcular fuerza necesaria para levantar objetos', 'Diseñar paracaídas de seguridad'],
          '¿Cuánta fuerza necesitas aplicar para acelerar un carrito de 12 kg a 3 m/s² en una pista sin fricción?',
          'ejercicio_contextualizado',
          ['Usa la segunda ley de Newton', 'F = m × a', 'Sustituye m = 12, a = 3'],
          [{ paso: 1, descripcion: 'Aplica F = m × a', formulaUsada: 'F = 12 × 3' }, { paso: 2, descripcion: 'Calcula el resultado', resultadoParcial: 'F = 36 N' }, { paso: 3, descripcion: 'Verifica unidades', resultadoParcial: 'Fuerza en Newtones' }],
          '¿Qué pasa si añadimos fricción?',
          ['fuerza', 'masa', 'aceleración', 'inercia', 'reaacción'],
          [
            { pregunta: '¿Cuál es la primera ley de Newton también conocida como?', respuestaCorrecta: 'Ley de la inercia', explicacion: 'Un objeto tiende a mantener su estado a menos que actúe una fuerza.', tipoMemoria: 'factual' },
            { pregunta: 'Un objeto de 5 kg acelera a 4 m/s². ¿Cuál es la fuerza aplicada?', respuestaCorrecta: '20 N', explicacion: 'F = m × a = 5 × 4 = 20 Newtones.', tipoMemoria: 'procedural' },
            { pregunta: '¿Qué ley explica por qué al patear una pelota esta se mueve?', respuestaCorrecta: 'Segunda ley de Newton', explicacion: 'La fuerza aplicada genera aceleración según F = ma.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'friccion',
          'Fricción: El Enemigo Invisible que Frena el Movimiento',
          20,
          'La fricción es como un guardia que siempre está atento: cuando intentas deslizar algo, tira para frenarte. Es la fuerza que se opone al movimiento relativo entre superficies.',
          'Imagina arrastrar una caja por la arena: cuesta más que por el hielo. La fricción depende de la rugosidad de las superficies.',
          ['Identifica normal N (fuerza perpendicular)', 'Usa μ (coeficiente de fricción)', 'Fricción = μ × N', 'La dirección es opuesta al movimiento'],
          'La fricción es la fuerza que se opone al movimiento relativo entre dos superficies en contacto. F_fricción = μ × N.',
          'F_f = μ × N',
          ['Caja de 10 kg, μ = 0.3, g = 10: F_f = 30 N', 'Si empujas con 25 N y fricción = 30 N, no se mueve'],
          ['No distinguir estática de dinámica', 'Olvidar que N = mg en superficie horizontal', 'Signo incorrecto en ecuaciones'],
          ['Diseño de neumáticos de coche', 'Deportes y calzado de agarre', 'Ingeniería de maquinaria'],
          'Una caja de 20 kg se empuja sobre una mesa con μ = 0.25. ¿Cuál es la fuerza mínima para moverla?',
          'problema_resuelto',
          ['N = mg = 20 × 9.8 = 196 N', 'F_fricción = μN = 0.25 × 196', 'La fuerza mínima supera la fricción estática'],
          [{ paso: 1, descripcion: 'Calcula N = 20 × 9.8 = 196 N', formulaUsada: 'N = mg' }, { paso: 2, descripcion: 'F_f = 0.25 × 196 = 49 N', resultadoParcial: 'F ≥ 49 N' }],
          '¿Por qué es más fácil arrastrar una caja cuando usas ruedas?',
          ['fricción', 'coeficiente', 'superficie', 'movimiento', 'fuerza'],
          [
            { pregunta: '¿En qué dirección actúa la fuerza de fricción?', respuestaCorrecta: 'Opuesta al movimiento o intento de movimiento', explicacion: 'La fricción siempre se opone al desplazamiento relativo.', tipoMemoria: 'conceptual' },
            { pregunta: 'Un bloque de 5 kg en una mesa con μ = 0.4. ¿Fuerza mínima para moverlo? (g=10)', respuestaCorrecta: '20 N', explicacion: 'F = μN = 0.4 × 50 = 20 N.', tipoMemoria: 'procedural' },
            { pregunta: '¿Cuál es la diferencia entre fricción estática y dinámica?', respuestaCorrecta: 'Estática: antes de mover; dinámica: durante el movimiento', explicacion: 'La estática es mayor, se rompe al iniciar movimiento.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'segunda-ley-newton',
          'Aplicación de la 2ª Ley: El Carrito de la Montana de Calle',
          21,
          'Imagina una montaña rusa bajando: la gravedad tira de ti hacia adelante, las ruedas frenan, y al final necesitas fuerza para seguir subiendo. La 2ª ley combina todas las fuerzas.',
          'Todos los empujones juntos crean una fuerza neta. Como cuando juntas fuerzas de amigos para empujar un auto: la suma determina la aceleración.',
          ['Dibuja todas las fuerzas (diagrama de cuerpo libre)', 'Suma vectorialmente (cuidado con signos)', 'Aplica ΣF = ma', 'Verifica dirección y sentido'],
          'La segunda ley de Newton: la aceleración de un cuerpo es directamente proporcional a la fuerza neta e inversamente proporcional a su masa.',
          'ΣF = m × a',
          ['Bloque en plano inclinado: a = g·sen(θ)', 'Dos bloques unidos por cuerda: a = (m₁g - m₂g·μ)/(m₁ + m₂)', 'Elevador acelerado: N = m(g + a)'],
          ['No dibujar todas las fuerzas', 'Confundir direcciones positivas/negativas', 'Olvídates de la masa en caída libre'],
          ['Análisis de estructuras', 'Diseño de vehículos', 'Física deportiva'],
          'Dos bloques (3 kg y 2 kg) están unidos por una cuerda sin masa. Si el bloque de 3 kg cuelga del borde, ¿qué aceleración tendrán?',
          'problema_resuelto',
          ['La masa mayor tira del sistema: F_neta = (3-2)g = 10 N', 'a = F_neta / (m₁ + m₂) = 10/5'],
          [{ paso: 1, descripcion: 'F_neta = 3×9.8 - 2×9.8 = 9.8 N', formulaUsada: 'ΣF = (m₁-m₂)g' }, { paso: 2, descripcion: 'a = 9.8/(3+2) = 1.96 m/s²', resultadoParcial: 'a ≈ 2 m/s²' }],
          '¿Qué pasa si el sistema está en equilibrio?',
          ['segunda ley', 'fuerza neta', 'diagrama de cuerpos', 'aceleración', 'masa'],
          [
            { pregunta: '¿Qué fuerza se puede calcular despejando la 2ª ley?', respuestaCorrecta: 'F = ma', explicacion: 'Fuerza es masa por aceleración.', tipoMemoria: 'factual' },
            { pregunta: 'Si dos fuerzas de 10 N y 6 N actúan en sentido opuesto, ¿cuál es la fuerza neta?', respuestaCorrecta: '4 N en dirección de la mayor', explicacion: '10 - 6 = 4 N (mayor - menor).', tipoMemoria: 'procedural' },
            { pregunta: '¿Qué forma tiene la gráfica de a vs F si m es constante?', respuestaCorrecta: 'Una recta directa', explicacion: 'a = F/m es proporcional directo.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'tercera-ley-newton',
          'Tercera Ley de Newton: La Pelota de Pelota de Nieve',
          18,
          'Cuando sales de una canoa, esta se aleja. Tu empuje te impulsa hacia adelante y la canoa recibe el empujón exactamente opuesto. Cada acción tiene reacción.',
          'Imagina patinar sobre hielo y lanzar una pelota: al lanzar, retrocedes. La pelota va hacia adelante, tú hacia atrás. Misma fuerza, direcciones opuestas.',
          ['Identifica el par de objetos interactuando', 'Acción: fuerza que A ejerce sobre B', 'Reacción: fuerza que B ejerce sobre A', 'Misma magnitud, direcciones opuestas'],
          'La tercera ley de Newton: a toda fuerza de acción corresponde una fuerza de reacción de misma magnitud, sentido opuesto y misma línea.',
          'F_AB = -F_BA',
          ['Al caminar: empujas el suelo → él te impulsa', 'Al nadar: empujas agua → ella te empuja', 'Cohete: expulsión de gas → empuje hacia arriba'],
          ['Confundir acción y reacción como fuerzas del mismo cuerpo', 'No reconocer que actúan sobre cuerpos distintos', 'Error de signos'],
          ['Propulsión de cohetes', 'Navegación de barcos', 'Caminar y correr'],
          'Una persona de 60 kg está en patín. Lanza una pelota de 2 kg a 10 m/s. ¿Qué velocidad adquiere la persona?',
          'problema_resuelto',
          ['Conservación de momento: m₁v₁ + m₂v₂ = 0 (inicialmente en reposo)', 'm_persona × v_persona = -m_pelota × v_pelota'],
          [{ paso: 1, descripcion: '60·v = -2·10 = -20', formulaUsada: 'p_conservada = 0' }, { paso: 2, descripcion: 'v = -20/60', resultadoParcial: 'v ≈ -0.33 m/s' }],
          '¿Por qué la reacción es igual pero opuesta?',
          ['tercera ley', 'acción', 'reacción', 'conservación', 'momento'],
          [
            { pregunta: '¿Las fuerzas de acción y reacción actúan sobre el mismo cuerpo?', respuestaCorrecta: 'No, actúan sobre cuerpos distintos', explicacion: 'Acción en A sobre B, reacción en B sobre A.', tipoMemoria: 'conceptual' },
            { pregunta: 'Al caminar, ¿qué fuerza te empuja hacia adelante?', respuestaCorrecta: 'La fricción del suelo', explicacion: 'Empujas el suelo hacia atrás, él te empuja hacia adelante.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Por qué un cohete sube sin tocar el suelo?', respuestaCorrecta: 'Expulsa gas hacia abajo y recibe empuje hacia arriba', explicacion: 'Tercera ley: la reacción del gas hacia arriba.', tipoMemoria: 'conceptual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: 'Un objeto de 10 kg recibe F = 30 N. ¿Cuál es su aceleración?', respuestaCorrecta: '3 m/s²', explicacion: 'a = F/m = 30/10 = 3.', tipoMemoria: 'procedural' },
        { pregunta: '¿Qué ley de Newton explica la inercia?', respuestaCorrecta: 'Primera ley', explicacion: 'La primera ley establece que los objetos tienden a mantener su estado.', tipoMemoria: 'factual' },
        { pregunta: '¿Las fuerzas acción-reacción actúan sobre el mismo objeto?', respuestaCorrecta: 'No', explicacion: 'Actúan sobre objetos diferentes.', tipoMemoria: 'conceptual' },
      ],
    },
    {
      id: 'termodinamica-basica',
      titulo: 'Termodinámica: El Baile de la Energía',
      orden: 3,
      spacedReviewSchedule: ['día 3', 'día 7', 'día 15', 'día 30'],
      lecciones: [
        leccion(
          'calor-energia',
          'Calor y Energía: Por qué el Hielo se Transforma en Agua',
          28,
          'La energía no se crea ni se destruye, solo cambia de forma. Como cuando el hielo se derrite: la energía del calor se transforma en movimiento de moléculas.',
          'Piensa en una piscina: si sales corriendo, el agua se mueve. Más energía = más movimiento = más calor.',
          ['La energía térmica es movimiento de partículas diminutas', 'Cuando algo se calienta, las partículas se mueven más rápido', 'Al cambiar de estado, la energía reorganiza las partículas'],
          'La energía térmica depende de la temperatura y masa. El calor es energía que fluye por diferencia de temperatura.',
          'Q = m × c × ΔT',
          ['Calentar 1 kg de agua 10°C: Q = 1 × 4186 × 10 = 41860 J', 'Cambiar 500g de hielo a agua: Q = 0.5 × 334000 = 167000 J'],
          ['Confundir temperatura con calor', 'Olvidar calor latente en cambios de estado', 'Unidades inconsistentes (cal vs julios)'],
          ['Entender por qué el aire acondicionado enfría', 'Calcular energía para cocinar', 'Diseñar aislamientos térmicos'],
          '¿Cuánta energía necesitas para calentar 500 ml de agua de 20°C a 80°C? (cp del agua = 4.186 J/g°C)',
          'problema_resuelto',
          ['Convierte ml a gramos: 1 ml = 1 g', 'Usa Q = m × c × ΔT', 'ΔT = 80 - 20 = 60°C'],
          [{ paso: 1, descripcion: 'Identifica valores: m=500g, c=4.186, ΔT=60', formulaUsada: 'Q = m × c × ΔT' }, { paso: 2, descripcion: 'Sustituye: Q = 500 × 4.186 × 60', resultadoParcial: 'Q = 125,580 J' }, { paso: 3, descripcion: 'Expresa en kJ', resultadoParcial: 'Q = 125.6 kJ' }],
          '¿Qué cambia si en lugar de agua usamos alcohol?',
          ['energía térmica', 'calor', 'temperatura', 'entropía', 'cambio de estado'],
          [
            { pregunta: '¿Qué primera ley de la termodinámica establece?', respuestaCorrecta: 'La conservación de la energía', explicacion: 'La energía no se crea ni destruye, solo se transforma.', tipoMemoria: 'factual' },
            { pregunta: '¿Cuál es el calor específico del agua en J/g°C?', respuestaCorrecta: '4.186', explicacion: 'El agua requiere mucha energía para cambiar su temperatura.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué ocurre durante el cambio de estado sólido a líquido?', respuestaCorrecta: 'La energía rompe enlaces sin cambiar temperatura', explicacion: 'Durante la fusión, la energía se usa para separar partículas.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'leyes-termodinamica',
          'Leyes de la Termodinámica: El Contrato de la Energía',
          22,
          'Imagina un sistema cerrado como un recodo de río: la energía puede entrar y salir, pero el total nunca cambia. La entropía es como la caos natural que siempre quiere crecer.',
          'Las leyes de la termodinámica son como reglas de un juego: la energía no desaparece, pero se dispersa. Todo trata de cómo se mueve y se reorganiza.',
          ['Primera ley: energía conservada (ΔU = Q - W)', 'Segunda ley: entropía siempre aumenta', 'La energía útil siempre se dispersa', 'No se puede extraer trabajo infinito'],
          'Primera ley: la energía interna cambia con calor añadido y trabajo realizado. Segunda ley: la entropía de un sistema aislado nunca disminuye.',
          'ΔU = Q - W',
          ['Calor 100 J y trabajo 30 J: ΔU = 70 J', 'Motor ideal: nunca 100% eficiente'],
          ['Creer que la energía se "pierde" en vez de dispersarse', 'No considerar la entropía del universo', 'Olvidar la conservación en transformaciones'],
          ['Eficiencia de motores', 'Sostenibilidad energética', 'Cosmología y big bang'],
          'Un motor recibe 500 J de calor y realiza 150 J de trabajo. ¿Cuál es la eficiencia y cuánto calor se disipa?',
          'problema_resuelto',
          ['Eficiencia = trabajo útil / calor entrante', 'Calor disipado = calor entrante - trabajo'],
          [{ paso: 1, descripcion: 'Eficiencia = 150/500 = 30%', formulaUsada: 'η = W/Q' }, { paso: 2, descripcion: 'Calor disipado = 500 - 150 = 350 J', resultadoParcial: '350 J se disipan' }],
          '¿Por qué no podemos tener una máquina del 100% de eficiencia?',
          ['termodinámica', 'energía', 'entropía', 'eficiencia', 'conservación'],
          [
            { pregunta: '¿Qué ley establece que la energía no se crea ni destruye?', respuestaCorrecta: 'Primera ley de la termodinámica', explicacion: 'La energía se conserva, solo cambia de forma.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué tiende a aumentar en un sistema aislado?', respuestaCorrecta: 'La entropía', explicacion: 'La segunda ley establece que la entropía nunca disminuye.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué la eficiencia nunca alcanza 100%?', respuestaCorrecta: 'Parte de la energía se disipa como calor inútil', explicacion: 'Siempre hay pérdidas irreversibles.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'calor-latente',
          'Calor Latente: El Secreto de los Cambios de Estado',
          20,
          'Cuando el hielo se derrite, la temperatura no sube aunque le des calor. Ese calor va a romper enlaces: es energía "escondida". Como pagar por una puerta secreta.',
          'Imagina un edificio con puertas que abrirse a cierta temperatura. Hasta que no se abran todas, la temperatura no sube.',
          ['El calor latente no cambia temperatura', 'Depende de la masa y el tipo de cambio', 'Q = m × L', 'Solidifica/congelación vs. funde/ebapora'],
          'El calor latente es la energía necesaria para cambiar el estado físico de una sustancia sin cambiar su temperatura. Q = m·L.',
          'Q = m × L',
          ['Para fundir hielo: L_fusión = 334 J/g', 'Para hervir agua: L_ebullición = 2260 J/g'],
          ['Confundir con calor sensible (Q = mcΔT)', 'No usar unidades consistentes', 'Olvidar el signo (absorbe vs libera)'],
          ['Almacenamiento de energía térmica', 'Ingeniería de refrigeración', 'Meteorología'],
          '¿Cuánta energía se necesita para convertir 200 g de hielo a 0°C en agua a 0°C? (L_fusión = 334 J/g)',
          'problema_resuelto',
          ['Usa Q = m × L_fusión', 'Sustituye valores'],
          [{ paso: 1, descripcion: 'Q = 200 × 334', formulaUsada: 'Q = mL' }, { paso: 2, descripcion: 'Q = 66,800 J = 66.8 kJ', resultadoParcial: 'Energía para fundir' }],
          '¿Qué calor latente es mayor: el de fusión o el de ebullición?',
          ['calor latente', 'fusion', 'ebullición', 'cambio de estado', 'energía'],
          [
            { pregunta: '¿Por qué la temperatura no sube al fundir hielo?', respuestaCorrecta: 'El calor rompe enlaces intermoleculares, no aumenta energía cinética', explicacion: 'El calor latente va a separar moléculas.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Cuál es el calor latente de fusión del agua en J/g?', respuestaCorrecta: '334', explicacion: 'Se necesitan 334 J para fundir 1 g de hielo.', tipoMemoria: 'factual' },
            { pregunta: '2 kg de hielo a 0°C se derriten. ¿Cuánta energía absorbe? (L = 334 kJ/kg)', respuestaCorrecta: '668 kJ', explicacion: 'Q = 2 × 334 = 668 kJ.', tipoMemoria: 'procedural' },
          ]
        ),
        leccion(
          'conduccion-conveccion-radiacion',
          'Transferencia de Calor: Tres Maneras de Compartir Energía',
          19,
          'El calor viaja como un mensaje: por contacto directa (conducción, como tocar una taza caliente), por corriente de fluido (convección, como el agua hirviendo) o por radiación (como el sol).',
          'Imagina un incendio: las llamas suben (convección), el calor te quema sin tocar (radiación), la estuf de leña calienta los ladrillos (conducción).',
          ['Conducción: contacto directo, material conductor mejor', 'Convección: movimiento de fluidos calientes', 'Radiación: ondas electromagnéticas, no necesita medio'],
          'La transferencia de calor ocurre por conducción (conductividad térmica), convección (movimiento de fluidos) y radiación (emisión de ondas).',
          'Q = kA(ΔT/Δx)',
          ['Plato caliente: conducción por el utensilio', 'Agua hirviendo: convección por convección natural', 'Sol: radiación electromagnética'],
          ['Confundir los tres mecanismos', 'No entender que la radiación no necesita medio', 'Olvidar factores de área y espesor'],
          ['Aislamiento térmico en casas', 'Refrigeración y aire acondicionado', 'Ingeniería de materiales'],
          '¿Por qué una bebida fría se enfría más rápido en un vaso de metal que de plástico?',
          'ejercicio_contextualizado',
          ['La conductividad térmica del metal es alta', 'El plástico es un aislante térmico'],
          [{ paso: 1, descripcion: 'Metal conduce calor mejor que plástico', formulaUsada: 'Q = kA(ΔT)t' }, { paso: 2, descripcion: 'El vaso metálico transfiere calor al ambiente más rápido', resultadoParcial: 'Mayor pérdida térmica' }],
          '¿Cómo viaja el calor del Sol hasta la Tierra?',
          ['conducción', 'convección', 'radiación', 'calor', 'temperatura'],
          [
            { pregunta: '¿Cuál es el mecanismo principal de transferencia en el espacio?', respuestaCorrecta: 'Radiación', explicacion: 'No hay medio para conducción ni convección en el vacío.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Por qué los pinos se derriten al tacto pero el hielo no?', respuestaCorrecta: 'Mayor conductividad térmica del metal', explicacion: 'El metal transfiere calor al cuerpo mucho más rápido.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Qué forma tiene el agua caliente al hervir?', respuestaCorrecta: 'Burbujas que suben por convección', explicacion: 'El agua caliente sube, la fría baja.', tipoMemoria: 'factual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: '¿Qué cantidad de energía se necesita para calentar 500 g de agua 10°C? (c=4.186)', respuestaCorrecta: '20,930 J', explicacion: 'Q = mcΔT = 500×4.186×10 = 20,930 J.', tipoMemoria: 'procedural' },
        { pregunta: '¿Qué ley de la termodinámica establece la conservación de energía?', respuestaCorrecta: 'Primera ley', explicacion: 'La energía interna cambia con calor y trabajo.', tipoMemoria: 'factual' },
        { pregunta: '¿Por cuál mecanismo viaja el calor del Sol?', respuestaCorrecta: 'Radiación', explicacion: 'La radiación electromagnética viaja sin necesidad de medio.', tipoMemoria: 'conceptual' },
      ],
    },
  ],
};
