import { CursoBase, QuizActiveRecall } from '../../tipos';

function leccion(
  id: string,
  titulo: string,
  duracion: number,
  intuicion: string,
  analogia: string,
  pasos: string[],
  definicion: string,
  formula: string | undefined,
  ejemplos: string[],
  errores: string[],
  aplicaciones: string[],
  retoEnunciado: string,
  retoTipo: 'problema_resuelto' | 'ejercicio_contextualizado' | 'simulacion',
  retoPistas: string[],
  retoSolucion: { paso: number; descripcion: string; formulaUsada?: string; resultadoParcial?: string }[],
  retoVerificacion: string,
  palabrasClave: string[],
  quiz: QuizActiveRecall[]
) {
  return {
    id,
    titulo,
    duracionAproximada: duracion,
    explicacionFeynman: {
      intuicionInicial: intuicion,
      analogiaSimple: analogia,
      pasoAPasoIntuitivo: pasos,
    },
    conceptoTecnico: {
      definicionFormal: definicion,
      formulaMatematica: formula,
      ejemplos,
      erroresComunes: errores,
      conexionAplicaciones: aplicaciones,
    },
    retoPractico: {
      tipo: retoTipo,
      enunciado: retoEnunciado,
      pistas: retoPistas,
      solucionPasoAPaso: retoSolucion,
      verificacionActiveRecall: retoVerificacion,
    },
    palabrasClave,
    quizActiveRecall: quiz,
  };
}

export const QuimicaCurso: CursoBase = {
  id: 'quimica-neuro',
  nombre: 'Química Visual: Donde los Átomos Cuentan su Historia',
  descripcion: 'Curso de Química desde cero hasta orgánica, priorizando la visualización molecular antes de fórmulas y ecuaciones estequiométricas.',
  nivelEducativo: 'Secundaria',
  competencias: [
    'Visualizar reacciones a nivel molecular',
    'Interpretar el comportamiento de átomos y enlaces',
    'Balancear ecuaciones químicas con intuición',
    'Aplicar conceptos a situaciones cotidianas',
    'Desarrollar pensamiento científico analítico',
  ],
  duracionEstimada: '15 meses',
  metodologia: {
    metodoFeynman: true,
    activeRecall: true,
    spacedRepetition: true,
    intuicionAntesFormula: true,
    estrategiasTransversales: [
      'Visualización de procesos moleculares',
      'Predicción de productos antes de balancear',
      'Uso de modelos 3D conceptuales',
      'Asociación de tabla periódica con propiedades reales',
      'Autoevaluación con predicción de observaciones',
    ],
  },
  modulos: [
    {
      id: 'atomos-moleculas',
      titulo: 'Átomos y Moléculas: El Lego del Universo',
      orden: 1,
      spacedReviewSchedule: ['día 1', 'día 3', 'día 7', 'día 21'],
      lecciones: [
        leccion(
          'estructura-atomica',
          'Estructura Atómica: El Planeta con Protones y Electrones',
          24,
          'Imagina un átomo como un planeta pequeño: en el centro hay un sol de protones y un nucleón, y alrededor orbitan planetas diminutos de electrones.',
          'Un átomo es como una orquesta: los protones son los tambores fuertes en el centro, los neutrones los sienten apagados, y los electrones son los violinistas moviéndose rápido alrededor.',
          ['El núcleo tiene protones (+) y neutrones (neutros)', 'Los electrones (-) giran en capas alrededor del núcleo', 'El número de protones define el elemento', 'Islas: mismo número de protones pero diferente de neutrones'],
          'Un átomo consiste en un núcleo de protones y neutrones con electrones en órbitas definidas. El número atómico es el número de protones.',
          'Masa = protones + neutrones',
          ['Hidrógeno: 1 protón, 0 neutrones → masa 1', 'Carbono-12: 6 protones, 6 neutrones → masa 12', 'Carbono-14: 6 protones, 8 neutrones → masa 14'],
          ['Confundir número atómico con masa', 'Olvidar que neutrones pueden variar (isótopos)', 'Creer que electrones pesan tanto como protones'],
          ['Radiocarbono en datación arqueológica', 'Isótopos en medicina nuclear', 'Relojes atómicos con átomos de cesio'],
          'El carbono tiene un isótopo con 6 protones y 8 neutrones. ¿Cuál es su masa atómica? ¿Cómo se llama?',
          'ejercicio_contextualizado',
          ['Masa = protones + neutrones', 'Número de protones = 6 (carbono)', '8 neutrones + 6 protones = ?'],
          [{ paso: 1, descripcion: 'Identifica protones = 6, neutrones = 8', formulaUsada: 'Masa = p + n' }, { paso: 2, descripcion: 'Calcula masa: 6 + 8', resultadoParcial: 'Masa = 14' }, { paso: 3, descripcion: 'Nombra el isótopo', resultadoParcial: 'Carbono-14' }],
          '¿Por qué el carbono-14 se usa en datación?',
          ['protón', 'neutrón', 'electrón', 'núcleo', 'isótopo'],
          [
            { pregunta: '¿Dónde están los protones en un átomo?', respuestaCorrecta: 'En el núcleo', explicacion: 'Los protones son parte del núcleo junto con los neutrones.', tipoMemoria: 'factual' },
            { pregunta: 'Un átomo tiene 8 protones y 9 neutrones. ¿Cuál es su masa?', respuestaCorrecta: '17', explicacion: 'Masa = 8 + 9 = 17 u.m.a.', tipoMemoria: 'procedural' },
            { pregunta: '¿Qué diferencia hay entre protón y electrón?', respuestaCorrecta: 'Protones tienen carga positiva, electrones negativa', explicacion: 'Los protones cargan positivo, los electrones cargan negativo.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'numero-masas-isotopos',
          'Número de Masa e Isótopos: Las Variantes del Mismo Elemento',
          17,
          'Un mismo elemento puede tener versiones diferentes, como gemelos que pesan distinto. El número atómico es siempre el mismo, pero los neutrones cambian.',
          'Imagina una familia: el padre siempre es el mismo (número atómico), pero los hijos pueden tener diferente peso (neutrones).',
          ['Número atómico = protones (definen el elemento)', 'Masa = protones + neutrones', 'Isótopos: mismo elemento, diferente masa', 'Calcular masa promedio ponderada'],
          'El número atómico (Z) es el número de protones. El número de masa (A) es protones + neutrones. Isótopos son átomos del mismo elemento con diferente número de neutrones.',
          'A = Z + n⁰ ; masa promedio = Σ(isótopo × abundancia)',
          ['Carbono-12 (99%) y Carbono-13 (1%): masa promedio = 12.01', 'Cloro-35 (75%) y Cloro-37 (25%): masa promedio ≈ 35.5'],
          ['Confundir número atómico con masa', 'Olvidar multiplicar por abundancia', 'No usar notación correcta: ^A_ZX'],
          ['Datación radiométrica', 'Medicina nuclear', 'Pesos atómicos en química analítica'],
          'El litio tiene dos isótopos: Li-6 (7.5%) y Li-7 (92.5%). ¿Cuál es la masa atómica promedio del litio?',
          'problema_resuelto',
          ['Multiplica cada masa por su abundancia', 'Suma los resultados'],
          [{ paso: 1, descripcion: '6 × 0.075 = 0.45', formulaUsada: 'Σ(isótopo × %)' }, { paso: 2, descripcion: '7 × 0.925 = 6.475', resultadoParcial: 'Suma = 6.925 u.m.a' }, { paso: 3, descripcion: 'Verifica con tabla periódica', resultadoParcial: 'Litio ≈ 6.94' }],
          '¿Por qué la masa atómica en la tabla periódica es un decimal?',
          ['isótopo', 'masa atómica', 'abundancia', 'número de masa', 'número atómico'],
          [
            { pregunta: '¿Qué define el elemento químico?', respuestaCorrecta: 'El número de protones', explicacion: 'El número atómico Z identifica al elemento.', tipoMemoria: 'factual' },
            { pregunta: 'Un isótopo de carbono tiene 8 neutrones. ¿Cuál es su masa?', respuestaCorrecta: '14', explicacion: '6 protones + 8 neutrones = 14 u.m.a.', tipoMemoria: 'procedural' },
            { pregunta: '¿Por qué la masa atómica promedio no es un número entero?', respuestaCorrecta: 'Porque combina isótopos con diferentes masas y abundancias', explicacion: 'Es una media ponderada de isótopos.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'modelo-electronico',
          'Modelo Electrónico: El Baile de los Electrones en su Pista',
          21,
          'Los electrones bailan en "pistas" (órbitas) alrededor del núcleo. Cada pista tiene un límite: la primera 2, la segunda 8, la tercera 18. No se pueden duplicar.',
          'Imagina una discoteca con niveles: el primer nivel caben 2 personas, el segundo 8, el tercero 18. Los electrones siguen ocupando niveles, nunca más.',
          ['Primer nivel: 2 electrones', 'Segundo nivel: 8 electrones', 'Tercer nivel: 18 electrones', 'Distribución según energía (capas)'],
          'Los electrones se distribuyen en capas según el modelo de KWL: K (2), L (8), M (18), N (32). La capa de valencia determina la reactividad.',
          undefined,
          ['Hidrógeno: 1e⁻ en capa K', 'Oxígeno: 2e⁻ K, 6e⁻ L (capa completa necesita 8)', 'Cloro: 2, 8, 7 (le falta 1 para completar)'],
          ['Confundir capas con subcapas', 'No contar electrones totales', 'Olvidar la capa de valencia'],
          ['Configuración electrónica en química', 'Predicción de enlaces químicos', 'Propiedades periódicas'],
          'Escribe la configuración electrónica del oxígeno (Z=8) y cloro (Z=17).',
          'problema_resuelto',
          ['Cuenta electrones = número atómico', 'Distribuye capas: K(2), L(8), M(18)'],
          [{ paso: 1, descripcion: 'Oxígeno: K=2, L=6', formulaUsada: 'K(2) L(6)' }, { paso: 2, descripcion: 'Cloro: K=2, L=8, M=7', resultadoParcial: 'M le falta 1 e⁻' }, { paso: 3, descripcion: 'Capa de valencia completa = 8 e⁻ (excepto H, He)', resultadoParcial: 'Amblos buscan estabilidad octetálida' }],
          '¿Por qué el sodio (Na) es muy reactivo?',
          ['electrones', 'capa', 'valencia', 'reactividad', 'configuración'],
          [
            { pregunta: '¿Cuántos electrones puede contener la capa K (primera)?', respuestaCorrecta: '2', explicacion: 'K = 2n² donde n=1 → 2 electrones.', tipoMemoria: 'factual' },
            { pregunta: 'El sodio tiene 11 electrones. ¿Cuántos tiene en su capa de valencia?', respuestaCorrecta: '1', explicacion: 'Configuración: K(2)L(8)M(1). Capa M le falta 7.', tipoMemoria: 'procedural' },
            { pregunta: '¿Qué es la capa de valencia?', respuestaCorrecta: 'La capa más externa con electrones', explicacion: 'Determina la reactividad del elemento.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'tabla-periodica',
          'Tabla Periódica: El Diccionario de los Átomos',
          20,
          'La tabla periódica organiza los elementos como un diccionario: de izquierda a derecha, de arriba a abajo. Cada fila es una capa de electrones. Cada columna comparten propiedades.',
          'Imagina un mapa del tesoro: elementos similares están en la misma columna (grupo), elementos con misma capa electrónica en la misma fila (periodo).',
          ['De izquierda a derecha: aumenta el número atómico', 'Arriba-abajo: aumenta tamaño atómico (más capas)', 'Columnas = grupos (misma química)', 'Filas = periodos (misma capa de valencia)'],
          'La tabla periódica es una organización de elementos por número atómico, masa y propiedades químicas. Los grupos son columnas verticales.',
          undefined,
          ['Grupo 1 (metales alcalinos): Li, Na, K - muy reactivos', 'Grupo 17 (halógenos): F, Cl, Br - reactivos', 'Grupo 18 (gases nobles): He, Ne, Ar - estables'],
          ['Confundir grupos con periodos', 'No recordar números de grupo', 'Saltar secciones (metales de transición)'],
          ['Predicción de enlaces', 'Propiedades de materiales', 'Reactivos en laboratorio'],
          'Un elemento es del grupo 2 y periodo 3. ¿Cuál es? ¿Cuántos electrones tiene en su capa de valencia?',
          'ejercicio_contextualizado',
          ['Grupo 2 = metales alcalinotérreos', 'Periodo 3 = 3 capas de electrones'],
          [{ paso: 1, descripcion: 'Grupo 2 = magnesio (Mg)', formulaUsada: 'Z = 12' }, { paso: 2, descripcion: 'K(2)L(8)M(2) → 2 en valencia', resultadoParcial: '2 electrones de valencia' }],
          '¿Por qué los gases nobles no reaccionan?',
          ['tabla periódica', 'grupo', 'periodo', 'reactividad', 'electrones'],
          [
            { pregunta: '¿Qué grupo tiene 1 electrón de valencia?', respuestaCorrecta: 'Grupo 1', explicacion: 'Los metales alcalinos del grupo 1 tienen 1 electrón en valencia.', tipoMemoria: 'factual' },
            { pregunta: '¿Dónde están los elementos más reactivos?', respuestaCorrecta: 'Grupo 1 (abajo) y Grupo 17 (abajo)', explicacion: 'Mayor tamaño atómico = más reactivo.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Cuántos electrones necesita el oxígeno para completar su capa?', respuestaCorrecta: '6', explicacion: 'Oxi: K(2)L(6). Necesita 2 para octeto.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'enlace-iotico',
          'Enlaces iónicos: El Trueque de Electrones',
          19,
          'Un enlace iónico es como un trueque: un átomo da electrones y otro los recibe, creando cargas opuestas que se atraen. Como imanes que se juntan.',
          'Imagina que Juan da 3 stickers a María. Juan tiene -3 carga, María +3. Se atraen por el balance.',
          ['Identifica metal y no-metal', 'Determina carga del ión', 'Intercambia electrones hasta neutral', 'Escribe fórmula cruzada'],
          'Un enlace iónico se forma cuando un metal transfiere electrones a un no-metal, creando iones con cargas opuestas que se atraen.',
          'Fórmula: cruzar cargas y simplificar',
          ['Na⁺ + Cl⁻ → NaCl', 'Mg²⁺ + O²⁻ → MgO', 'Al³⁺ + 3Cl⁻ → AlCl₃'],
          ['No balancear cargas correctamente', 'Olvidar el subíndice', 'Confundir cationes con aniones'],
          ['Sales en alimentos', 'Cerámica y porcelana', 'Baterías y electrolitos'],
          '¿Cuál es la fórmula del óxido de calcio? (Ca²⁺ y O²⁻)',
          'problema_resuelto',
          ['Ca²⁺ y O²⁻ tienen cargas igualadas', 'Intercambian electrones hasta neutral', 'Fórmula: CaO (no Ca₂O₂)'],
          [{ paso: 1, descripcion: 'Ca²⁺ cruza con O²⁻', formulaUsada: 'Fórmula cruzada' }, { paso: 2, descripcion: 'CaO (simplificado)', resultadoParcial: 'Un Ca por cada O' }, { paso: 3, descripcion: 'Verifica cargas: 2+ y 2- = neutral', resultadoParcial: 'Compuesto estable' }],
          '¿Qué es una red cristalina iónicaa?',
          ['iónico', 'catión', 'anión', 'fórmula', 'red cristalina'],
          [
            { pregunta: '¿Qué tipo de elemento forma cationes?', respuestaCorrecta: 'Metales', explicacion: 'Los metales pierden electrones para formar cationes.', tipoMemoria: 'factual' },
            { pregunta: '¿Cómo se escribe la fórmula de sulfuro de aluminio (Al³⁺, S²⁻)?', respuestaCorrecta: 'Al₂S₃', explicacion: 'Cruzamos: Al³ S² → Al₂S₃ (simplificar).', tipoMemoria: 'procedural' },
            { pregunta: '¿Por qué las sales iónicas son duraderas?', respuestaCorrecta: 'Por enlaces fuertes entre iones', explicacion: 'Las redes cristalinas iónicas son fuertes y rígidas.', tipoMemoria: 'conceptual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: '¿Qué define el número atómico de un elemento?', respuestaCorrecta: 'El número de protones', explicacion: 'El número atómico Z es la cantidad de protones del núcleo.', tipoMemoria: 'factual' },
        { pregunta: '¿Cuántos electrones puede contener la capa L (segunda)?', respuestaCorrecta: '8', explicacion: 'L = 2n² donde n=2 → 8 electrones.', tipoMemoria: 'factual' },
        { pregunta: 'Un átomo con Z=12 tiene 5 isótopos con 14 neutrones. ¿Cuál es su masa?', respuestaCorrecta: '26', explicacion: '6 protones + 14 neutrones = masa 26 (Zafiro-26).', tipoMemoria: 'procedural' },
      ],
    },
    {
      id: 'enlace-quimico',
      titulo: 'Enlaces Químicos: Cómo se Abrazan los Átomos',
      orden: 2,
      spacedReviewSchedule: ['día 2', 'día 5', 'día 12', 'día 25'],
      lecciones: [
        leccion(
          'tipos-enlaces',
          'Tipos de Enlaces: Covalencia, Iónico y Metálico',
          28,
          'Los átomos se unen como amigos: comparten cosas (covalencia), uno da y otro recibe (iónico), o todos juntos se comparten (metálico).',
          'Un enlace iónico es como un trueque: un átomo da electrones al otro. Covalencia es como compartir lápices: ambos usan los mismos. Metálico es como un grupo grande compartiendo todo.',
          ['Iónico: uno pierde electrones (negativo), otro gana (positivo)', 'Covalencia: comparten pares de electrones', 'Metálico: todos comparten una nube de electrones'],
          'Los enlaces químicos son interacciones que unen átomos mediante transferencia o compartición de electrones para alcanzar estabilidad.',
          'Enlace iónico: cation + anión → sal',
          ['NaCl: Na⁺ + Cl⁻ → sal común', 'H₂O: H comparte con O → enlace covalente', 'Cobre: nubes de electrones compartidos → metálico'],
          ['Creer que todos los elementos forman enlaces metálicos', 'No prever cargas iónicas correctas', 'Olvidar que el enlace busca estabilidad (8 electrones)'],
          ['Sólidos iónicos en cerámica', 'Moléculas covalentes en medicinas', 'Metales en conductores eléctricos'],
          '¿Por qué el cloruro de sodio (NaCl) se forma mediante enlace iónico y el agua (H₂O) mediante covalencia?',
          'problema_resuelto',
          ['Observa la ubicación en la tabla periódica', 'Na es metal, Cl es no-metal', 'H y O son no-metales'],
          [{ paso: 1, descripcion: 'Metal + no-metal = enlace iónico', resultadoParcial: 'NaCl: enlace iónico' }, { paso: 2, descripcion: 'No-metal + no-metal = enlace covalente', resultadoParcial: 'H₂O: enlace covalente' }, { paso: 3, descripcion: 'Explica transferencia vs compartición', resultadoParcial: 'Na dona e⁻ a Cl; H comparte e⁻ con O' }],
          '¿Qué propiedades tendría una sustancia puramente iónica?',
          ['ión', 'iónico', 'covalente', 'metálico', 'estabilidad'],
          [
            { pregunta: '¿Qué tipo de enlace forma el agua (H₂O)?', respuestaCorrecta: 'Covalente', explicacion: 'H y O son no-metales que comparten electrones.', tipoMemoria: 'factual' },
            { pregunta: '¿Cuál es la diferencia entre enlace iónico y covalente?', respuestaCorrecta: 'Iónico: transferencia de electrones; covalente: compartición de electrones', explicacion: 'El enlace iónico implica transferencia cargas opuestas.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Por qué los metales conductores eléctricos?', respuestaCorrecta: 'Tienen electrones deslocalizados libres', explicacion: 'En enlaces metálicos, electrones fluyen libremente.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'enlace-covalente',
          'Enlace Covalente: Compartir para Ser Estable',
          23,
          'El enlace covalente es como compartir un helado entre amigos: ambos obtienen algo. Los átomos comparten pares de electrones para completar su capa de valencia.',
          'Imagina que dos personas tienen un problema: cada uno necesita 1 lápiz más. Si uno tiene 3 y el otro 1, comparten: ambos terminan con 2.',
          ['Identifica cuántos electrones necesita el elemento', 'Compartes pares para completar 8 (u 2 para H)', 'Cuenta puentes (líneas) entre átomos', 'Verifica geometría molecular'],
          'Un enlace covalente forma cuando dos átomos comparten pares de electrones para alcanzar la configuración electrónica estable.',
          'H₂O: 2 puentes | O=C=N (tríada) | doble/triple enlace = 2 o 3 pares compartidos',
          ['H₂O: O comparte 2 pares, H cada uno 1', 'CO₂: C comparte doble enlace con 2 O', 'N₂: triple enlace entre dos N'],
          ['Confundir número de puentes con electrones', 'No predecir geometría molecular', 'Olvidar electrones libres'],
          ['Dióxido de carbono en respiración', 'Agua en biología celular', 'Medicamentos con enlaces covalentes'],
          '¿Por qué el oxígeno forma dos enlaces covalentes y el carbono puede formar cuatro?',
          'ejercicio_contextualizado',
          ['Oxígeno: capa de valencia necesita 2 electrones (tiene 6 de 8)', 'Carbono: necesita 4 (tiene 4 de 8)'],
          [{ paso: 1, descripcion: 'O₂: comparte 2 pares → O=O', formulaUsada: 'Doble enlace' }, { paso: 2, descripcion: 'Carbono forma 4 puentes simples', resultadoParcial: 'CH₄: 4 enlaces' }],
          '¿Por qué el oxígeno puro es diatómico?',
          ['covalente', 'compartición', 'puente', 'geometría', 'estabilidad'],
          [
            { pregunta: '¿Cuántos enlaces covalentes forma el hidrógeno?', respuestaCorrecta: '1', explicacion: 'H necesita 1 electrón (2 totales para K complete).', tipoMemoria: 'factual' },
            { pregunta: 'En el metano (CH₄), ¿qué tipo de enlace hay entre C y H?', respuestaCorrecta: 'Covalente simple', explicacion: 'C comparte 1 electrón con cada H.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué diferencia hay entre enlace simple, doble y triple?', respuestaCorrecta: 'Simple: 1 par, doble: 2 pares, triple: 3 pares compartidos', explicacion: 'Más pares = mayor fuerza y menor rotación.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'enlace-metalico',
          'Enlace Metálico: La Nube de los Conductores',
          19,
          'En un metal, los electrones se liberan y forman una nube que fluye. Los iones positivos flotan en esta nube como peces en un estanque.',
          'Imagina una pista de baile: los iones positivos son bailarines que se mueven libremente en una nube de electrones negativos que los envuelve todo.',
          ['Iones metálicos positivos en gascea de electrones', 'Electrones deslocalizados conducen electricidad', 'Fuerte cohesión pero maleable', 'Propiedades: brillo, conductividad, dureza'],
          'El enlace metálico es la interacción entre iones metálicos positivos y una nube de electrones deslocalizados.',
          'n/a (modelo cualitativo)',
          ['Cobre: excelente conductor', 'Hierro: fuerte y magnético', 'Aluminio: ligero y maleable'],
          ['Creer que los electrones están en órbitas específicas', 'No entender maleabilidad', 'Confundir con enlaces covalentes'],
          ['Cableado eléctrico', 'Pinturas metálicas', 'Aleaciones en ingeniería'],
          '¿Por qué el cobre se usa en cables eléctricos y no el hierro?',
          'ejercicio_contextualizado',
          ['Compara conductividad eléctrica', 'Considera densidad y maleabilidad'],
          [{ paso: 1, descripcion: 'Cobre: iones + nube de e⁻ altamente móvil', formulaUsada: 'Conductividad = 100% cobre' }, { paso: 2, descripcion: 'Hierro oxida y es menos conductor', resultadoParcial: 'Cobre es mejor conductor' }],
          '¿Por qué los metales son maleables?',
          ['metálico', 'nube', 'electrones', 'conductividad', 'maleabilidad'],
          [
            { pregunta: '¿Qué característica hace a los metales conductores?', respuestaCorrecta: 'Electrones deslocalizados libres', explicacion: 'La nube de electrones mueve carga eléctrica.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Por qué el hierro puede doblarse sin romperse?', respuestaCorrecta: 'Los iones se deslizan en la nube de electrones', explicacion: 'Maleabilidad es propiedad de enlaces metálicos.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Qué propiedad NO es típica de los metales?', respuestaCorrecta: 'Baja conductividad térmica', explicacion: 'Los metales son buenos conductores tanto térmica como eléctricamente.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'geometria-molecular',
          'Geometría Molecular: La Arquitectura de las Moléculas',
          22,
          'Las moléculas tienen formas como los edificios: el agua se curva como un alabeo, la amoníaco es piramidal. La forma determina cómo se comportan.',
          'Imagina que los electrones son como resortes que tiran de los átomos: la forma final depende de cuántos "resortes" hay y de qué ángulo.',
          ['Cuenta pares de electrones del átomo central', 'Determina geometría según VSEPR', 'Ángulos típicos: lineal 180°, trigonal 120°, tetraédrica 109.5°'],
          'La geometría molecular se predice con la teoría VSEPR: los pares de electrones se distribuyen para minimizar repulsión.',
          'n/a',
          ['H₂O: 2 pares libres + 2 enlaces = ángulo 104.5°', 'CO₂: lineal, 180°', 'NH₃: piramidal trigonal, 107°'],
          ['Contar pares libres como enlaces', 'No usar VSEPR correctamente', 'Confundir geometría con forma'],
          ['Química de farmacéuticos', 'Diseño de polímeros', 'Biología molecular'],
          'Predice la geometría de la molécula de dióxido de carbono (CO₂) y agua (H₂O).',
          'problema_resuelto',
          ['Cuenta pares de electrones del átomo central', 'Aplica VSEPR', 'Determina ángulos'],
          [{ paso: 1, descripcion: 'CO₂: C con 4e⁻ → 2 pares de enlace', formulaUsada: 'VSEPR' }, { paso: 2, descripcion: 'CO₂ es lineal (180°)', resultadoParcial: 'Ángulo 180°' }, { paso: 3, descripcion: 'H₂O: O con 6e⁻ → 2 pares libres + 2 enlaces', resultadoParcial: 'Ángulo 104.5°' }],
          '¿Por qué el agua es polar pero el dióxido de carbono no?',
          ['geometría', 'molécula', 'VSEPR', 'ángulo', 'polaridad'],
          [
            { pregunta: '¿Qué geometría tiene un átomo con 3 pares de enlace y 0 pares libres?', respuestaCorrecta: 'Trigonal plana', explicacion: '3 pares de enlace → ángulos de 120°.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué el agua se curva (ángulo 104.5°)?', respuestaCorrecta: 'Los pares libres empujan los enlaces', explicacion: 'La repulsión entre pares libres reduce el ángulo.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Qué molécula tiene geometría tetraédrica?', respuestaCorrecta: 'Metano (CH₄)', explicacion: 'C con 4 pares de enlace → tetraédrica.', tipoMemoria: 'factual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: '¿Qué tipo de enlace forma NaCl?', respuestaCorrecta: 'Iónico', explicacion: 'Na (metal) transfiere e⁻ a Cl (no-metal).', tipoMemoria: 'factual' },
        { pregunta: '¿Cuántos enlaces covalentes tiene el metano (CH₄)?', respuestaCorrecta: '4', explicacion: 'Carbono comparte un electrón con cada H.', tipoMemoria: 'factual' },
        { pregunta: '¿Por qué los metales son buenos conductores?', respuestaCorrecta: 'Tienen electrones deslocalizados libres', explicacion: 'La nube de electrones conduce electricidad.', tipoMemoria: 'conceptual' },
      ],
    },
    {
      id: 'estequiometria-basica',
      titulo: 'Estequiometría: Contando lo Que Realmente Importa',
      orden: 3,
      spacedReviewSchedule: ['día 3', 'día 7', 'día 15', 'día 30'],
      lecciones: [
        leccion(
          'balance-molecular',
          'Balance Molecular: Igualdad ante Todo',
          30,
          'Una ecuación química es como una receta: necesitas la misma cantidad de ingredientes antes y después de cocinar. No puedes crear ni destruir átomos.',
          'Es como un Rompecabezas: cada pieza representa un átomo. Debes tener el mismo número de piezas del mismo color en ambos lados.',
          ['Cuenta átomos de cada tipo en ambos lados', 'Ajusta coeficientes (números pequeños) para equilibrar', 'Verifica que cada tipo de átomo tenga el mismo total', 'Recuerda: solo cambias cantidades, no fórmulas'],
          'Una ecuación química balanceada conserva la masa y el número de átomos según la ley de conservación de la masa.',
          'Átomos reactivos = Átomos productos',
          ['2H₂ + O₂ → 2H₂O: 4 H, 2 O en ambos lados', 'CH₄ + 2O₂ → CO₂ + 2H₂O: 1 C, 4 H, 4 O', 'Na + Cl₂ → NaCl: ajusta a 2Na + Cl₂ → 2NaCl'],
          ['Cambiar subíndices en lugar de coeficientes', 'No contar átomos complejos (polyatómicos)', 'Olvidar que los estados (s,l,g) no cambian la ecuación'],
          ['Fabricación de medicamentos', 'Reacciones de explosivos', 'Procesos industriales de síntesis'],
          'Balancea: NaOH + H₂SO₄ → Na₂SO₄ + H₂O',
          'ejercicio_contextualizado',
          ['Cuenta: Na, O, H, S en cada lado', 'S ajusta Na: necesitas 2NaOH', 'Verifica H y O al final'],
          [{ paso: 1, descripcion: 'Identifica átomos: Na(1), O(5), H(3), S(1)', resultadoParcial: 'Lado izq: NaOH + H₂SO₄' }, { paso: 2, descripcion: 'Añade coeficiente 2 a NaOH', resultadoParcial: '2NaOH + H₂SO₄' }, { paso: 3, descripcion: 'Verifica: Na(2), O(5), H(4), S(1) → H₂O necesita 2', resultadoParcial: '2NaOH + H₂SO₄ → Na₂SO₄ + 2H₂O' }],
          '¿Por qué la masa se conserva en reacciones químicas?',
          ['reactivo', 'producto', 'coeficiente', 'subíndice', 'conservación'],
          [
            { pregunta: '¿Qué debes equilibrar en una ecuación química?', respuestaCorrecta: 'La cantidad de átomos de cada tipo', explicacion: 'Debes tener el mismo número de átomos en ambos lados.', tipoMemoria: 'factual' },
            { pregunta: 'En 2H₂ + O₂ → 2H₂O, ¿cuántos átomos de hidrógeno hay en total?', respuestaCorrecta: '4', explicacion: '2 moléculas H₂ = 4 átomos de H; 2H₂O = 4 átomos de H.', tipoMemoria: 'procedural' },
            { pregunta: '¿Qué error es común al balancear ecuaciones?', respuestaCorrecta: 'Cambiar subíndices en lugar de coeficientes', explicacion: 'Los subíndices definen compuestos, no se modifican al balancear.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'masa-molar-estequiometria',
          'Masa Molar y Estequiometría: De Gramos a Mol',
          24,
          'La masa molar es como un "paquete estándar": 1 mol de cualquier átomo pesa su número atómico en gramos. El agua pesa 18 g/mol, el cloro 35.5 g/mol.',
          'Imagina cajas de frutas: cada caja (mol) contiene el mismo número de frutas (6.02×10²³), pero cada fruta pesa diferente.',
          ['1 mol = 6.022×10²³ partículas', 'Masa molar = masa atómica en g/mol', 'Convierte g → mol → partículas', 'Usa coeficientes como multiplicadores'],
          'La masa molar es la masa de 1 mol de sustancia. Se relaciona con el número de Avogadro: N_A = 6.022×10²³ partículas/mol.',
          'n = m / M',
          ['18 g de H₂O = 1 mol (18 g/mol)', '2 mol de NaCl = 2×58.5 = 117 g', '0.5 mol de CO₂ = 22 g'],
          ['Confundir masa molar con peso atómico', 'No usar unidades consistentes', 'Olvidar multiplicar por coeficientes'],
          ['Síntesis de fármacos', 'Preparación de soluciones', 'Cálculo de rendimientos'],
          '¿Cuántos gramos de agua produce 2 moles de H₂ reaccionando con O₂?',
          'problema_resuelto',
          ['Balancea: 2H₂ + O₂ → 2H₂O', '2 moles H₂ producen 2 moles H₂O', 'Masa H₂O = 2 × 18 = 36 g'],
          [{ paso: 1, descripcion: 'Balancea ecuación: 2H₂ + O₂ → 2H₂O', formulaUsada: 'Conservación átomos' }, { paso: 2, descripcion: '2 mol H₂ → 2 mol H₂O', resultadoParcial: 'Relación 1:1' }, { paso: 3, descripcion: 'Masa H₂O = 2 × 18 = 36 g', resultadoParcial: '36 gramos de agua' }],
          '¿Por qué el número de Avogadro es el mismo para todos los elementos?',
          ['masa molar', 'mol', 'avogadro', 'estequiometría', 'reacciones'],
          [
            { pregunta: '¿Cuántos gramos pesa 1 mol de hidrógeno?', respuestaCorrecta: '1 g', explicacion: 'Masa atómica H ≈ 1 u.m.a., luego 1 g/mol.', tipoMemoria: 'factual' },
            { pregunta: '¿Cuántas moléculas hay en 2 mol de agua?', respuestaCorrecta: '1.204×10²⁴', explicacion: '2 × 6.022×10²³ = 1.204×10²⁴.', tipoMemoria: 'procedural' },
            { pregunta: '¿Qué relación usas para convertir gramos a moles?', respuestaCorrecta: 'n = m/M', explicacion: 'Moles = masa / masa molar.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'rendimiento-quimico',
          'Rendimiento en Reacciones: El Arte de No Desperdiciar',
          20,
          'Nunca se obtiene el 100% en una reacción química. Es como hornear un pastel: siempre se queman algunos pedazos. El rendimiento te dice porcentaje real.',
          'Imagina una cocina: pides 10 hamburguesas pero solo logras 8 porque se caen. El rendimiento es 80%.',
          ['Rendimiento teórico: lo esperado por estequiometría', 'Rendimiento real: lo que obtuviste', 'Rendimiento % = (real/teórico) × 100', 'El limitante determina el máximo'],
          'El rendimiento porcentual es el porcentaje de producto obtenido respecto al máximo teórico posible.',
          'Rendimiento % = (m_real / m_teorico) × 100',
          ['Si teórico = 50 g y real = 42 g → rendimiento = 84%', 'Si teórico = 20 g y real = 18 g → rend. = 90%'],
          ['No calcular bien el teórico', 'Confundir limitante con exceso', 'Olvidar unidades'],
          ['Industrias químicas', 'Laboratorios académicos', 'Farmacéutica'],
          'Síntesis de Na₂SO₄: se obtienen 12.5 g. Calcula el rendimiento si el teórico es 15.0 g.',
          'problema_resuelto',
          ['Rendimiento = (real / teórico) × 100', 'Sustituye valores'],
          [{ paso: 1, descripcion: 'Rendimiento % = (12.5/15.0) × 100', formulaUsada: '(m_real/m_teorico)×100' }, { paso: 2, descripcion: '12.5/15 = 0.833', resultadoParcial: '83.3%' }, { paso: 3, descripcion: 'Verifica razonabilidad', resultadoParcial: '≈ 83% razonable' }],
          '¿Qué es el reactivo limitante?',
          ['rendimiento', 'rendimiento %', 'reactivo limitante', 'teórico', 'real'],
          [
            { pregunta: 'Si produjiste 8 g pero el teórico es 10 g, ¿cuál es el rendimiento?', respuestaCorrecta: '80%', explicacion: '100 × 8/10 = 80%.', tipoMemoria: 'procedural' },
            { pregunta: '¿Qué es el reactivo limitante?', respuestaCorrecta: 'El que se consume primero y limita el producto', explicacion: 'Determina la cantidad máxima de producto.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Por qué el rendimiento real nunca es 100%?', respuestaCorrecta: 'Pérdidas por escapamiento, adsorción y residuos', explicacion: 'Siempre hay pérdidas irreversibles.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'soluciones-concentra',
          'Soluciones y Concentración: El Cóctel Perfecto',
          21,
          'Una solución es como un cóctel: el sabor fuerte depende de qué proporción de ingredientes usas. La concentración dice qué tan "fuerte" es.',
          'Imagina agua con colorante: cuanto más gotas, más intenso. La concentración molar dice cuántas moléculas "dulces" hay por cada litro.',
          ['Concentración molar = moles / litros de solución', 'Molaridad (M) = n/V', 'Dilución: M₁V₁ = M₂V₂', 'Porcentaje en peso, volumen'],
          'La molaridad (M) es la concentración expresada en moles de soluto por litro de solución.',
          'M = n / V',
          ['0.5 M NaCl = 0.5 moles en 1 L', 'Diluir 1 M a 0.2 M: necesitas 5× más volumen'],
          ['Confundir mol con masa', 'No usar unidades consistentes', 'Olvidar la dilución conserva M₁V₁'],
          ['Preparación de reactivos en laboratorio', 'Medicamentos y dosis', 'Análisis químico'],
          'Necesitas preparar 500 mL de solución 0.1 M de HCl. ¿Cuántos gramos de HCl necesitas? (M_HCl = 36.5 g/mol)',
          'problema_resuelto',
          ['M = n/V → n = M × V', 'm = n × M_molar'],
          [{ paso: 1, descripcion: 'n = 0.1 × 0.5 = 0.05 mol', formulaUsada: 'n = MV' }, { paso: 2, descripcion: 'm = 0.05 × 36.5 = 1.825 g', resultadoParcial: '≈ 1.8 g HCl' }],
          '¿Qué diferencia hay entre molaridad y molalidad?',
          ['concentración', 'molaridad', 'moles', 'solución', 'dilución'],
          [
            { pregunta: '¿Qué unidad tiene la molaridad?', respuestaCorrecta: 'mol/L o M', explicacion: 'Moles por litro de solución.', tipoMemoria: 'factual' },
            { pregunta: 'Si tienes 2 M de NaCl en 3 L, ¿cuántos moles hay?', respuestaCorrecta: '6 moles', explicacion: 'n = M × V = 2 × 3 = 6.', tipoMemoria: 'procedural' },
            { pregunta: '¿Qué ecuación usas para diluir una solución?', respuestaCorrecta: 'M₁V₁ = M₂V₂', explicacion: 'La cantidad de moles se conserva al diluir.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'reacciones-disolucion',
          'Reacciones de Disolución: El Baile de los Iones',
          18,
          'Cuando una sal se disuelve, se separa en iones que bailan libres como en una discoteca. Algunos iones son espectadores (no reaccionan) y otros se combinan.',
          'Imagina una fiesta donde algunos invitados se emparejan (reacción) y otros se quedan mirando (ión espectador).',
          ['Escribe ecuación completa con iones', 'Separa en ecuación iónica completa', 'Elimina iones espectadores', 'Verifica carga y átomos'],
          'Una ecuación iónica completa muestra todos los iones. Los iones espectadores aparecen en ambos lados y se eliminan.',
          '(cloruro de sodio) Na⁺ + Cl⁻; (sulfato de bario) Ba²⁺ + SO₄²⁻ → BaCl₂ + SO₄²⁻',
          ['NaCl + AgNO₃ → NaNO₃ + AgCl', 'El Cl⁻ y Na⁺ son espectadores'],
          ['No escribir átomos en el lado correcto', 'Olvidar estados físicos', 'Confundir precipitado con gas'],
          ['Análisis cualitativo de iones', 'Preparación de complejos', 'Reacciones en medio acuoso'],
          'Escribe la ecuación iónica completa de: NaCl(aq) + AgNO₃(aq) → AgCl(s) + NaNO₃(aq)',
          'problema_resuelto',
          ['Escribe todos los iones en solución', 'Identifica precipitado (AgCl)', 'Elimina iones espectadores'],
          [{ paso: 1, descripcion: 'Na⁺ + Cl⁻ + Ag⁺ + NO₃⁻ → AgCl(s) + Na⁺ + NO₃⁻', formulaUsada: 'Iones en solución' }, { paso: 2, descripcion: 'Elimina Na⁺ y NO₃⁻ (espectadores)', resultadoParcial: 'Cl⁻ + Ag⁺ → AgCl(s)' }, { paso: 3, descripcion: 'Verifica precipitado', resultadoParcial: 'Ecuación iónica neta correcta' }],
          '¿Qué es un ion espectador?',
          ['iónico', 'espectador', 'disolución', 'precipitado', 'concentración'],
          [
            { pregunta: '¿En qué estado aparecen los iones que reaccionan?', respuestaCorrecta: 'En el lado derecho como producto', explicacion: 'Forman precipitados o gases.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Qué símbolo usas para indicar que un compuesto se disuelve?', respuestaCorrecta: '(aq)', explicacion: 'aq = acuoso, disuelto en agua.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué ecuación muestra solo la reacción real?', respuestaCorrecta: 'Ecuación iónica neta', explicacion: 'Sin iones espectadores.', tipoMemoria: 'factual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: 'Balancea: H₂ + O₂ → H₂O', respuestaCorrecta: '2H₂ + O₂ → 2H₂O', explicacion: '4 H y 2 O en ambos lados.', tipoMemoria: 'procedural' },
        { pregunta: '¿Cuántos gramos de NaCl contiene 2 moles? (M = 58.5 g/mol)', respuestaCorrecta: '117 g', explicacion: '2 × 58.5 = 117 g.', tipoMemoria: 'procedural' },
        { pregunta: '¿Qué significa "reactivo limitante"?', respuestaCorrecta: 'El que se consume primero y limita el producto', explicacion: 'Determina la cantidad máxima de producto.', tipoMemoria: 'conceptual' },
      ],
    },
  ],
};
