import { CursoBase, QuizActiveRecall } from '../../tipos';

function leccion(
  id: string,
  titulo: string,
  duracion: number,
  intuicion: string,
  analogia: string,
  pasos: string[],
  definicion: string,
  formula: string | undefined,
  ejemplos: string[],
  errores: string[],
  aplicaciones: string[],
  retoEnunciado: string,
  retoTipo: 'problema_resuelto' | 'ejercicio_contextualizado' | 'simulacion',
  retoPistas: string[],
  retoSolucion: { paso: number; descripcion: string; formulaUsada?: string; resultadoParcial?: string }[],
  retoVerificacion: string,
  palabrasClave: string[],
  quiz: QuizActiveRecall[]
) {
  return {
    id,
    titulo,
    duracionAproximada: duracion,
    explicacionFeynman: {
      intuicionInicial: intuicion,
      analogiaSimple: analogia,
      pasoAPasoIntuitivo: pasos,
    },
    conceptoTecnico: {
      definicionFormal: definicion,
      formulaMatematica: formula,
      ejemplos,
      erroresComunes: errores,
      conexionAplicaciones: aplicaciones,
    },
    retoPractico: {
      tipo: retoTipo,
      enunciado: retoEnunciado,
      pistas: retoPistas,
      solucionPasoAPaso: retoSolucion,
      verificacionActiveRecall: retoVerificacion,
    },
    palabrasClave,
    quizActiveRecall: quiz,
  };
}

export const BiologiaCurso: CursoBase = {
  id: 'biologia-neuro',
  nombre: 'Biología Visual: El Código de la Vida',
  descripcion: 'Curso de Biología desde la célula hasta los ecosistemas, priorizando la visualización molecular y las conexiones sistémicas.',
  nivelEducativo: 'Secundaria',
  competencias: [
    'Visualizar procesos celulares y moleculares',
    'Interpretar relación entre estructura y función biológica',
    'Aplicar conceptos de genética a la vida cotidiana',
    'Analizar sistemas ecológicos y su equilibrio',
    'Desarrollar pensamiento científico basado en evidencias',
  ],
  duracionEstimada: '15 meses',
  metodologia: {
    metodoFeynman: true,
    activeRecall: true,
    spacedRepetition: true,
    intuicionAntesFormula: true,
    estrategiasTransversales: [
      'Visualización de procesos moleculares',
      'Modelado con analogías antes de terminología',
      'Conexión entre niveles de organización biológica',
      'Autoevaluación con predicción de observaciones',
    ],
  },
  modulos: [
    {
      id: 'celula-adn',
      titulo: 'Célula y ADN: El Código de la Vida',
      orden: 1,
      spacedReviewSchedule: ['día 1', 'día 4', 'día 10', 'día 25'],
      lecciones: [
        leccion(
          'estructura-celular',
          'Estructura Celular: La Fábrica viva',
          25,
          'Una célula es como una ciudad: el núcleo es el ayuntamiento, el ADN es la biblioteca, las mitocondrias son centrales energéticas.',
          'Imagina una fábrica: núcleo = oficina principal, ADN = archivo de instrucciones, mitocondrias = generadores de energía.',
          ['El núcleo contiene el ADN y controla la célula', 'Las mitocondrias producen energía (ATP)', 'El retículo endoplásmico transporta materiales', 'La membrana celular protege y regula'],
          'Una célula es la unidad básica de los organismos vivos, con membrana, citoplasma y núcleo, con organelas especializadas.',
          undefined,
          ['Célula animal: núcleo grande, muchas mitocondrias', 'Célula vegetal: cloroplastos, pared celular', 'Bacteria: sin núcleo, membrana plasmática'],
          ['Confundir organelas con su función', 'Olvidar membrana selectivamente permeable', 'No distinguir procariota de eucariota'],
          ['Microscopía celular', 'Estudios de transporte', 'Biología del desarrollo'],
          '¿Cuál es la diferencia entre célula procariota y eucariota? Nombra dos organelas de célula vegetal.',
          'ejercicio_contextualizado',
          ['Compara tamaño y complejidad', 'Busca diferencias en núcleo y organelas'],
          [{ paso: 1, descripcion: 'Procariota: sin núcleo, más pequeña', resultadoParcial: 'Bacteria' }, { paso: 2, descripcion: 'Eucariota: con núcleo delimitado', resultadoParcial: 'Animal/planta' }, { paso: 3, descripcion: 'Organelas vegetales: cloroplastos y pared celular', resultadoParcial: 'Fotosíntesis y soporte' }],
          '¿Por qué la membrana celular es fundamental para la supervivencia?',
          ['célula', 'núcleo', 'ADN', 'mitocondria', 'organela'],
          [
            { pregunta: '¿Cuál es la función del núcleo celular?', respuestaCorrecta: 'Contener el ADN y controlar la célula', explicacion: 'El núcleo alberga material genético y dirige actividades.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué organela produce ATP?', respuestaCorrecta: 'Mitocondria', explicacion: 'Las mitocondrias son fabricantes de energía celular.', tipoMemoria: 'factual' },
            { pregunta: '¿Diferencia entre célula animal y vegetal?', respuestaCorrecta: 'Vegetal tiene cloroplastos y pared celular', explicacion: 'Plantas: cloroplastos, pared celular.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'adn-doble-helix',
          'ADN: La Doble Hélice del Código Genético',
          27,
          'El ADN es un libro de instrucciones con dos páginas (hebras) unidas. Bases forman palabras (códigos) que dicen cómo construir proteínas.',
          'Imagina una escalera de caracol: pelos son hebras de ADN, peldaños son bases.',
          ['Bases: A, T, G, C', 'Doble hélice como escalera', 'Hebras separadas sirven de plantilla', 'Secuencias forman códones'],
          'El ADN es molécula con doble hebra de nucleótidos con bases A,T,G,C, que codifican proteínas.',
          'A-T (2 enlaces), G-C (3 enlaces) | Código: 3 bases = 1 aminoácido',
          ['A-T, G-C, A-T...', 'Código: AUG = metionina (inicio)', 'TAC → AUG → primera proteína'],
          ['Confundir ARN con ADN', 'No recordar A con T', 'Olvidar triple código'],
          ['Secuenciación genómica', 'Edad molecular (telómeros)', 'Edición genética (CRISPR)'],
          'Diseña secuencia ADN de 12 bases que codifique 4 aminoácidos. Si plantilla es ATCGATCGATCG, escribe hebra complementaria.',
          'problema_resuelto',
          ['Recuerda: A↔T, G↔C', 'Lee 3 bases (códon)', 'Complementaria = complemento inverso'],
          [{ paso: 1, descripcion: 'Complementaria: TAGCTAGCTAGC', formulaUsada: 'A↔T, G↔C' }, { paso: 2, descripcion: 'Códon de ARN: 4 códones de 3', resultadoParcial: 'ATC-GAT-CGA-TCG' }, { paso: 3, descripcion: 'Traducir a aminoácidos', resultadoParcial: '4 aminoácidos' }],
          '¿Por qué el ADN guarda información de la vida?',
          ['ADN', 'doble hélice', 'base', 'códon', 'genoma'],
          [
            { pregunta: '¿Qué bases forman el ADN?', respuestaCorrecta: 'A, T, G, C', explicacion: 'Adenina, Timina, Guanina, Citosina.', tipoMemoria: 'factual' },
            { pregunta: '¿Cuántos enlaces A-T y G-C?', respuestaCorrecta: '2 y 3 enlaces', explicacion: 'A-T: 2 pares H; G-C: 3 pares.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué significa doble hélice?', respuestaCorrecta: 'Dos hebras enrolladas en espiral', explicacion: 'Doble hélice: estructura escalera del ADN.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'sintesis-proteica',
          'Síntesis Proteica: La fábrica de células',
          30,
          'Síntesis proteica es fábrica de libros: ADN da instrucciones, ARNm las copia, ribosomas leen, proteína es producto final.',
          'Receta: ADN libro de recetas, ARNm copia, ribosoma chef, proteína pastel.',
          ['Transcripción: ADN → ARNm', 'Traducción: ARNm → proteína', 'Códon inicio AUG', 'Códon parada UAA, UAG, UGA'],
          'Síntesis proteica: transcripción (ARNm) y traducción (proteína), código genético a aminoácidos.',
          'ARNm → ARNt | Códon inicio AUG',
          ['ADN → ARNm: T cambia por U', 'Cada ARNt lleva un aminoácido', 'Ribosomas maquinaria de ensamblaje'],
          ['Confundir ARNm con ARNt', 'No entender códones', 'Olvidar dirección 5 a 3'],
          ['Terapias génicas', 'Producción de insulina', 'Vacunas de ARN'],
          'Diseña ARNm de 9 bases que codifique 3 aminoácidos. Si ADN original es TACGGCTAC, escribe ARNm y aminoácidos.',
          'problema_resuelto',
          ['Transcripción: T→U en plantilla', 'Traducción: 3 códones = 3 aminoácidos'],
          [{ paso: 1, descripcion: 'Transcribir: TACGGCTAC → AUGCCGAUG', formulaUsada: 'T→U' }, { paso: 2, descripcion: 'Dividir códones: AUG-CCG-AUG', resultadoParcial: 'AUG inicia' }, { paso: 3, descripcion: 'Traducir: AUG=met, CCG=pro, AUG=met', resultadoParcial: 'met-pro-met' }],
          '¿Por qué la proteína es producto final y no el ARNm?',
          ['transcripción', 'traducción', 'ARNm', 'codón', 'aminoácido'],
          [
            { pregunta: '¿En qué etapa se crea el ARNm?', respuestaCorrecta: 'Transcripción', explicacion: 'ARNm se transcribe del ADN en núcleo.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué códon marca inicio?', respuestaCorrecta: 'AUG', explicacion: 'AUG: metionina e inicio de traducción.', tipoMemoria: 'factual' },
            { pregunta: '¿ARNm vs ARNt?', respuestaCorrecta: 'mensajero lleva info; ARNt lleva aminoácidos', explicacion: 'ARNm codifica, ARNt transporta.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'mutaciones',
          'Mutaciones: Los errores que impulsan la evolución',
          22,
          'Una mutación es error de escritura en receta: a veces no cambia, otras mejora (resistencia a malaria), otras la arruina.',
          'Error al copiar libro: "gato" → "gato" (igual), "casa" → "cosa" (silenciosa), "fallecido" → "fatalético" (grave).',
          ['Mutación puntual: una base cambiada', 'Inserción/deleción: bases añadidas/quitadas', 'Silenciosas: no cambian proteína', 'Deleterias/presiones/benéficas'],
          'Mutación: cambio en secuencia ADN que puede ser neutral, deleteria o benéfica, fuente de variabilidad genética.',
          'Tipos: puntual, inserción, deleción, duplicación | Efectos: silenciosa, neutral, deleteria, benéfica',
          ['A→G: puede ser silenciosa', 'Inserción Huntington: CAG excesivo', 'Mutación fibrina: coagulación'],
          ['Creer todas mutaciones malas', 'No clasificar correctamente', 'Confundir germinal con somática'],
          ['Test paternidad', 'Terapia génica', 'Evolución bacteriana'],
          'Proteína tiene 100 aminoácidos. Mutación inserción añade 3 bases. ¿Cuántos aminoácidos cambia?',
          'ejercicio_contextualizado',
          ['3 bases = 1 aminoácido', 'Proteína tendría 101 aminoácidos'],
          [{ paso: 1, descripcion: '3 bases añadidas = 1 códon = 1 aminoácido', resultadoParcial: '+1 aminoácido' }, { paso: 2, descripcion: 'Original: 100, Mutado: 101', resultadoParcial: 'Cambio +1 aminoácido' }, { paso: 3, descripcion: 'La proteína cambia en 1 aminoácido', resultadoParcial: 'Cambio marco lectura' }],
          '¿Por qué algunas mutaciones necesarias para evolución?',
          ['mutación', 'ADN', 'proteína', 'evolución', 'variabilidad'],
          [
            { pregunta: '¿Qué tipo mutación cambia una base?', respuestaCorrecta: 'Mutación puntual', explicacion: 'Cambia una sola base.', tipoMemoria: 'factual' },
            { pregunta: '¿Efecto de inserción de 3 bases?', respuestaCorrecta: 'Añade un aminoácido', explicacion: '3 bases = 1 aminoácido.', tipoMemoria: 'procedural' },
            { pregunta: '¿Mutación germinal vs somática?', respuestaCorrecta: 'Germinal: heredable; somática: no heredable', explicacion: 'Germinal afecta gametos; somática células cuerpo.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'clonacion-reprogramacion',
          'Clonación y Reprogramación: Copias y recetas de vida',
          24,
          'Clonación = fotocopiar receta; reprogramación = convertir postre en sopa. Célula de piel a célula madre.',
          'Libro de recetas: clonación copia; reprogramación convierte receta de postre a receta de sopa.',
          ['Clonación: copia idéntica (Dolly la oveja)', 'Reprogramación: célula diferenciada → célula madre', 'Yamanaka: 4 genes reloj celular', 'Terapia regenerativa'],
          'Clonación: organismos genéticamente idénticos. Reprogramación: convierte células diferenciadas a pluripotentes.',
          'n/a (conceptual)',
          ['Clonación Dolly: 497 células tejido oveja', 'Células embrionaria vs inducidas (iPSC)', 'Organoides: mini órganos cultivo'],
          ['Creer embrionaria = embriones completos', 'No entender reprogramación', 'Confundir terapia con clonación'],
          ['Terapia enfermedades degenerativas', 'Investigación', 'Cultivo órganos'],
          '¿Diferencia entre iPSC (célula madre inducida) y célula madre embrionaria?',
          'simulacion',
          ['Investiga ambos tipos', 'Considera origen y potencial'],
          [{ paso: 1, descripcion: 'iPSC: reprogramada desde célula adulta', resultadoParcial: 'Inducida' }, { paso: 2, descripcion: 'Embrionaria: natural, de blastocisto', resultadoParcial: 'Natural' }, { paso: 3, descripcion: 'Ambas: pluripotentes', resultadoParcial: 'Similar potencial' }],
          '¿Cómo funcionan los factores de Yamanaka?',
          ['clonación', 'reprogramación', 'célula madre', 'ADN', 'factor Yamanaka'],
          [
            { pregunta: '¿Qué es Dolly?', respuestaCorrecta: 'Una oveja clonada', explicacion: 'Primera Mamífero clonada por transferencia nuclear.', tipoMemoria: 'factual' },
            { pregunta: '¿Cuántos factores Yamanaka?', respuestaCorrecta: '4', explicacion: 'Oct4, Sox2, Klf4, c-Myc reprograman células.', tipoMemoria: 'factual' },
            { pregunta: '¿Clonación vs reprogramación?', respuestaCorrecta: 'Clonación: copia; reprogramación: cambio identidad', explicacion: 'Clonación replica; reprogramación transforma.', tipoMemoria: 'conceptual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: '¿Función principal del ADN?', respuestaCorrecta: 'Almacenar información genética', explicacion: 'ADN contiene instrucciones.', tipoMemoria: 'factual' },
        { pregunta: '¿Proceso convierte ADN en proteínas?', respuestaCorrecta: 'Transcripción y traducción', explicacion: 'ADN → ARNm → proteínas.', tipoMemoria: 'factual' },
        { pregunta: '¿Clonación vs reprogramación?', respuestaCorrecta: 'Clonación crea copias; reprogramación cambia identidad', explicacion: 'Clonación replica; reprogramación transforma.', tipoMemoria: 'conceptual' },
      ],
    },
    {
      id: 'genetica-evolucion',
      titulo: 'Genética y Evolución: El Origen de la Diversidad',
      orden: 2,
      spacedReviewSchedule: ['día 2', 'día 6', 'día 14', 'día 30'],
      lecciones: [
        leccion(
          'mendel-genetica',
          'Genética de Mendel: Las Reglas del Azar',
          26,
          'La genética de Mendel es como lanzar monedas: cada gen viene en pares y al azar se elige cuál mostrar. Como tener dos libros y elegir páginas.',
          'Imagina una caja de dobles: cada gen tiene dos copias (alelos), y al formar gametos, cada copia se separa como si tiraras una moneda.',
          ['Primera ley: segregación de alelos', 'Segunda ley: distribución independiente', 'Dominante vs recesivo', 'Fenotipo vs genotipo'],
          'Las leyes de Mendel establecen que los caracteres se heredan como unidades discretas que se segregan e distribuyen.',
          undefined,
          ['Fenotipo: 3:1 (domin:rec) | Genotipo: 1:2:1 | Aa x Aa → 25% AA, 50% Aa, 25% aa'],
          ['Confundir fenotipo con genotipo', 'Aplicar leyes a genes ligados al sexo', 'No considerar epistasis'],
          ['PREDICT', 'Consejos genéticos', 'Estudios población'],
          'Un padre (Aa) y una madre (aa) tienen un hijo. ¿Probabilidad de que el hijo sea afectado (aa)?',
          'problema_resuelto',
          ['Usa cuadrilla de Punnett', 'Aa x aa → 50% Aa, 50% aa'],
          [{ paso: 1, descripcion: 'Punnett: A de padre, a de madre', resultadoParcial: 'Aa y aa' }, { paso: 2, descripcion: '50% Aa portador, 50% aa afectado', resultadoParcial: '50% afectado' }, { paso: 3, descripcion: 'Si dominante completo, hijo visible 50%', resultadoParcial: 'Prob 50%' }],
          '¿Por qué la genética sigue reglas matemáticas?',
          ['Mendel', 'alelo', 'fenotipo', 'genotipo', 'Punnett'],
          [
            { pregunta: '¿Qué establece primera ley de Mendel?', respuestaCorrecta: 'Los alelos se segregan en gametos', explicacion: 'Cada gen tiene alelos que se separan en gametos.', tipoMemoria: 'factual' },
            { pregunta: '¿Fenotipo más probable de Aa x Aa?', respuestaCorrecta: '3 dominantes : 1 recesivo', explicacion: '25% AA, 50% Aa, 25% aa.', tipoMemoria: 'procedural' },
            { pregunta: '¿Diferencia entre hombres leyes?', respuestaCorrecta: 'Primera: segregación; segunda: distribución independiente', explicacion: 'Separan alelos vs distribuyen genes.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'darwin-evolucion',
          'Darwin y la Evolución: La Gran Explanada',
          28,
          'Evolución es torneo de talento: versiones que sobreviven compiten. Rápido, camuflado o resistente deja más descendencia.',
          'Isla: gaviotas con patas diferentes; las que agarran mejor sobreviven.',
          ['Selección natural: supervivencia adecuada', 'Variación heredable', 'Reproducción diferencial', 'Adaptación: característica ventajosa'],
          'Evolución: cambio en características hereditarias de poblaciones, por selección natural y deriva genética.',
          undefined,
          ['Águilas con garras fuertes caza mejor', 'Bacterias resistentes a antibióticos', 'Cambio tamaño caparazones galápagos'],
          ['Creer dirección evolución', 'No entender actúa sobre fenotipos', 'Pensar es solo teoría'],
          ['Biología evolutiva', 'Conservación de especies', 'Estrategias resistencia'],
          'En isla, mamuts con cuernos grandes sobreviven mejor. ¿Cambio en 100 generaciones?',
          'ejercicio_contextualizado',
          ['Identifica presión selectiva', 'Predice cambio evolutivo'],
          [{ paso: 1, descripcion: 'Selección natural favorece cuernos grandes', resultadoParcial: 'Selección' }, { paso: 2, descripcion: 'Individuos cuernos grandes más descendencia', resultadoParcial: 'Herencia' }, { paso: 3, descripcion: 'Proporción cuernos grandes aumenta', resultadoParcial: 'Evolución' }],
          '¿Cómo evolución produce complejidad sin diseñador?',
          ['Darwin', 'evolución', 'selección natural', 'adaptación', 'variación'],
          [
            { pregunta: '¿Qué observó Darwin en gaviotas?', respuestaCorrecta: 'Patatas de pico diferentes según isla', explicacion: 'Picos adaptados a islas y recursos.', tipoMemoria: 'factual' },
            { pregunta: '¿3 ingredientes de evolución?', respuestaCorrecta: 'Variación, heredabilidad, selección diferencial', explicacion: 'Variación existe, se hereda, selecciona natural.', tipoMemoria: 'factual' },
            { pregunta: '¿Evolución vs desarrollo?', respuestaCorrecta: 'Evolución entre generaciones; desarrollo dentro organismo', explicacion: 'Evolución cambia genes población; desarrollo cambia células.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'especiacion-adaptacion',
          'Especiación y Adaptación: El Nacimiento de Especies',
          24,
          'Especiación es familia separada: hermanos viven lugares diferentes y cambian, hasta no poder tener hijos juntos.',
          'Río cambia curso; mitad peces aislada: evolucionan hasta especies distintas.',
          ['Especiación alopátrica: aislamiento geográfico', 'Especiación simpátrica: sin aislamiento', 'Barrera reproductiva: no cruzarse', 'Adaptación: característica ventajosa'],
          'Especiación: proceso donde una especie se divide. Adaptación: característica que aumenta fitness.',
          'Fitness = éxito reproductivo relativo',
          ['Canguros vs americanos', 'Especiación anfibios montaña', 'Adaptación moscas'],
          ['Confundir especiación con adaptación', 'No barrera reproductiva', 'Pensar especies siempre forman'],
          ['Conservación especies peligro', 'Biología invasoras', 'Estudios híbridos'],
          'Una población de mariposas se separa por montaña. Una mitad evoluciona amar a rojas, otra a amarillas. ¿Tipo?',
          'ejercicio_contextualizado',
          ['Busca aislamiento geográfico', 'Define barrera reproductiva'],
          [{ paso: 1, descripcion: 'Montaña separa geográficamente', resultadoParcial: 'Aislamiento geográfico' }, { paso: 2, descripcion: 'Prefieren flores diferentes (comportamiento)', resultadoParcial: 'Barrera reproductiva' }, { paso: 3, descripcion: 'No se cruzan → especiación alopátrica', resultadoParcial: 'Especies nuevas' }],
          '¿Por qué híbridos suelen ser estériles?',
          ['especiación', 'adaptación', 'barrera reproductiva', 'aislamento', 'flor'],
          [
            { pregunta: '¿Especiación por aislamiento geográfico?', respuestaCorrecta: 'Alopátrica', explicacion: 'Alopátrica requiere aislamiento geográfico.', tipoMemoria: 'factual' },
            { pregunta: '¿Adaptación vs evolución?', respuestaCorrecta: 'Adaptación: característica; evolución: cambio poblacional', explicacion: 'Adaptación es rasgo, evolución proceso.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Ejemplo especiación en moscas Hawaii?', respuestaCorrecta: 'Radiación adaptativa islas', explicacion: 'Moscas islas se adaptaron a nichos.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'genetica-poblacional',
          'Genética de Poblaciones: Estadística de la Vida',
          22,
          'Genética de poblaciones es encuesta: preguntan qué genes tiene gente, porcentaje que cambia con el tiempo.',
          'Encuesta: 600 pelo castaño, 400 rubio. Nueva encuesta: 700 castaño = pelo aumenta.',
          ['Hardy-Weinberg: equilibrio genético', 'Flujo genético: entrada/salida genes', 'Deriva: cambio aleatorio', 'Selección natural: cambio no aleatorio', 'Tasa mutación'],
          'Genética de poblaciones: cambio en frecuencia de alelos en poblaciones, modelando procesos.',
          'p² + 2pq + q² = 1',
          ['Hardy-Weinberg: p² AA + 2pq Aa + q² aa', 'Deriva poblaciones pequeñas', 'Flujo: migración genes'],
          ['No asumir infinita', 'Olvidar 5 fuerzas equilibrio', 'Confundir frecuencia alelos con genes'],
          ['Ancestralidad', 'Conservación especies', 'Evolución bacteriana'],
          'En población, alelo A frecuencia 0.7, a 0.3. Hardy-Weinberg, frecuencia esperada AA, Aa, aa?',
          'problema_resuelto',
          ['p = 0.7, q = 0.3', 'Usa p² + 2pq + q² = 1'],
          [{ paso: 1, descripcion: 'p² = 0.49 (AA)', formulaUsada: 'p²' }, { paso: 2, descripcion: '2pq = 0.42 (Aa)', resultadoParcial: '= 0.42' }, { paso: 3, descripcion: 'q² = 0.09 (aa)', resultadoParcial: 'Suma = 1.0' }],
          '¿Por qué Hardy-Weinberg útil aunque modelo ideal?',
          ['Hardy-Weinberg', 'alelo', 'población', 'derivación', 'selección'],
          [
            { pregunta: '¿Ecuación Hardy-Weinberg?', respuestaCorrecta: 'p² + 2pq + q² = 1', explicacion: 'Modela frecuencias genotípicas equilibrio.', tipoMemoria: 'factual' },
            { pregunta: '¿Fuerza causa deriva?', respuestaCorrecta: 'Cambios aleatorios poblaciones pequeñas', explicacion: 'Deriva es cambio no dirigido azar.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Afecta flujo genético?', respuestaCorrecta: 'Introduce nuevos alelos población', explicacion: 'Flujo entrada genes migración.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'biologia-molecular',
          'Biología Molecular: Tecnologías del Futuro',
          24,
          'Biología molecular es kit superhéroe: PCR copia ADN, electroforesis separa como tamiz, CRISPR corta y pega.',
          'ADN libro: PCR fotocopia páginas, electroforesis separa tamaño, CRISPR edita precisión.',
          ['PCR: amplificación ADN', 'Electroforesis: separación tamaño', 'Microarrays: expresión masiva', 'CRISPR-Cas9: edición precisa'],
          'Biología molecular: PCR, electroforesis, CRISPR para manipular y estudiar ADN.',
          'n/a',
          ['PCR: 3 pasos (desnaturalización, anclaje, elongación)', 'Gel agarosa: bandas = tamaño', 'CRISPR: guía + corte + corrección'],
          ['Confundir PCR con secuenciación', 'No entender CRISPR', 'Olvidar controles positivos PCR'],
          ['Diagnóstico PCR', 'Patoguardia genética', 'Terapia CRISPR'],
          '¿Diferencia entre CRISPR y PCR? ¿Uso cada?',
          'ejercicio_contextualizado',
          ['Investiga función ambas', 'Considera aplicación'],
          [{ paso: 1, descripcion: 'PCR: amplifica ADN existente', resultadoParcial: 'Copia' }, { paso: 2, descripcion: 'CRISPR: corta y edita ADN específico', resultadoParcial: 'Edición' }, { paso: 3, descripcion: 'PCR diagnóstico; CRISPR terapia', resultadoParcial: 'Aplicaciones distintas' }],
          '¿Cómo CRISPR puede curar enfermedades genéticas?',
          ['PCR', 'CRISPR', 'ADN', 'biología molecular', 'electroforesis'],
          [
            { pregunta: '¿Significa PCR?', respuestaCorrecta: 'Reacción cadena polimerasa', explicacion: 'PCR amplifica fragmentos ADN.', tipoMemoria: 'factual' },
            { pregunta: '¿Componentes CRISPR?', respuestaCorrecta: 'Guía RNA y proteína Cas9', explicacion: 'Complejo guía-Cas9 localiza corta ADN.', tipoMemoria: 'factual' },
            { pregunta: '¿PCR vs secuenciación?', respuestaCorrecta: 'PCR amplifica; secuenciación lee secuencia', explicacion: 'PCR copia, secuenciación identifica bases.', tipoMemoria: 'conceptual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: '¿Establece Hardy-Weinberg?', respuestaCorrecta: 'Frecuencia alelos constante sin fuerzas', explicacion: 'En equilibrio, no hay cambio.', tipoMemoria: 'factual' },
        { pregunta: '¿5 fuerzas evolutivas?', respuestaCorrecta: 'Mutación, deriva, flujo, selección, migración', explicacion: 'Cambian frecuencia genes poblaciones.', tipoMemoria: 'factual' },
        { pregunta: '¿CRISPR diferencia de PCR?', respuestaCorrecta: 'CRISPR edita ADN; PCR amplifica', explicacion: 'CRISPR corta-pega; PCR copia.', tipoMemoria: 'conceptual' },
      ],
    },
    {
      id: 'ecologia-sistemas',
      titulo: 'Ecología y Sistemas: El Equilibrio del Planeta',
      orden: 3,
      spacedReviewSchedule: ['día 3', 'día 8', 'día 16', 'día 35'],
      lecciones: [
        leccion(
          'cadena-alimentaria',
          'Cadena Alimentaria: La Pirámide de Energía',
          23,
          'Cadena alimentaria es pirámide personas: productores (plantas) base energía, consumidores arriba menos energía.',
          'Teatro: plantas público fondo, herbívoros medio, carnívoros pocos frente.',
          ['Productor: convierte luz energía (fotosíntesis)', 'Consumidor primario: come plantas', 'Consumidor secundario: come animales', 'Descomponedor: recicla'],
          'Cadena alimentaria: transferencia energía y materia entre niveles tróficos, desde productores.',
          'Ley 10%: solo 10% transferencia entre niveles tróficos',
          ['Plancton → peces → depredadores marinos', 'Pasto → conejo → zorro → lobo', 'Árbol → oruga → pájaro → halcón'],
          ['No asumir 10% estricto', 'Confundir cadena con red', 'Olvidar descomponedores'],
          ['Gestión pesquerías', 'Conservación depredadores', 'Restauración ecosistemas'],
          'En cadena: hierba → ratón → gato → lechuza. Si hierba 1000 energía, ¿cuánto llega lechuza?',
          'problema_resuelto',
          ['Aplica ley 10%', 'Cada nivel pierde 90%'],
          [{ paso: 1, descripcion: 'Hierba: 1000 unidades', resultadoParcial: 'Base' }, { paso: 2, descripcion: 'Ratón: 100 unidades', formulaUsada: 'Ley 10%' }, { paso: 3, descripcion: 'Gato: 10, Lechuza: 1 unidad', resultadoParcial: '1% energía original' }],
          '¿Por qué cadenas más cortas en ecosistemas fríos?',
          ['cadena alimentaria', 'productor', 'consumidor', 'descompuesto', 'trófico'],
          [
            { pregunta: '¿Cadena vs red alimentaria?', respuestaCorrecta: 'Cadena: única línea; red: múltiples conexiones', explicacion: 'Redes: ciclos, retroalimentación.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Porcentaje energía entre niveles?', respuestaCorrecta: '~10%', explicacion: 'Ley 10% limita cadena.', tipoMemoria: 'factual' },
            { pregunta: '¿Por qué depredadores críticos?', respuestaCorrecta: 'Controlan poblaciones mantienen equilibrio', explicacion: 'Depredadores regulan presas.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'ciclos-biogeoquimicos',
          'Ciclos Biogeoquímicos: Reciclaje del Planeta',
          26,
          'Ciclos biogeoquímicos lavandería: agua, carbono, nitrógeno nunca se pierden, siempre reciclan.',
          'Lavandería: agua evapora → nublarse → lluvia. Carbono: árboles absorben CO₂ → animales exhalan.',
          ['Ciclo agua: evaporación, condensación, precipitación', 'Ciclo carbono: respiración, fotosíntesis, combustión', 'Ciclo nitrógeno: fijación, descomposición, nitrificación', 'Transformaciones inorgánica/orgánica'],
          'Ciclos biogeoquímicos: caminos repetitivos de elementos esenciales, manteniendo biosfera.',
          'n/a',
          ['Agua: 71% planeta, ciclo hidrológico', 'Carbono: CO₂ atmósfó, CO₂ disuelto', 'Nitrógeno: 78% atmósfera, bacteria'],
          ['Confundir ciclo con cadena', 'Olvidar transformaciones bacterianas', 'No conexión clima'],
          ['Gestión agua', 'Secuestro carbono', 'Fertilidad suelo'],
          '¿Cómo cambio climático afecta ciclo agua?',
          'ejercicio_contextualizado',
          ['Considera calentamiento', 'Piensa patrones lluvia'],
          [{ paso: 1, descripcion: 'Calentamiento = más evaporación', resultadoParcial: 'Intensifica ciclo' }, { paso: 2, descripcion: 'Patrones lluvia cambian', resultadoParcial: 'Sequías e inundaciones' }, { paso: 3, descripcion: 'Disrupción ecosistemas', resultadoParcial: 'Impacto ciclos' }],
          '¿Por qué nitrógeno importante?',
          ['ciclo', 'agua', 'carbono', 'nitrógeno', 'transformación'],
          [
            { pregunta: '¿Etapa ciclo agua lluvia?', respuestaCorrecta: 'Precipitación', explicacion: 'Condensación nubes, precipitación lluvia.', tipoMemoria: 'factual' },
            { pregunta: '¿Gas ciclo carbono?', respuestaCorrecta: 'CO₂', explicacion: 'Dióxido carbono absorbe/libera ciclos.', tipoMemoria: 'factual' },
            { pregunta: '¿Proceso fija nitrógeno?', respuestaCorrecta: 'Fijación bacterias', explicacion: 'Bacterias nitrógeno fijan atmósfera.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'equilibrio-ecologico',
          'Equilibrio Ecológico: La Delicada Bola de Nieve',
          21,
          'Ecosistema es bola nieve: empujes fuerte (especie invasora), desliza montaña. Quitamos algo (depredador), bola estalla.',
          'Rompecabezas: pieza (especie) encaja. Quitamos pieza, otras caen. Equilibrio: piezas lugar.',
          ['Equilibrio dinámico: todo cambia tendencias se mantienen', 'Retroalimentación: efectos regulan', 'Puntos críticos: pequeños grandes', 'Resiliencia: capacidad recuperación'],
          'Equilibrio ecológico: estado dinámico, interacciones biológicas físicas mantienen estabilidad.',
          'n/a',
          ['Depredador → presa: regulación población', 'Mutualismo: abejas y flores', 'Competencia: especies similares'],
          ['No asumir equilibrio fijo', 'Olvidar retroalimentación', 'Pensar siempre estable'],
          ['Gestión parques', 'Especies peligro', 'Ecología restauración'],
          'Si introducen especie invasora pez en lago sin depredadores, ¿sucesos según equilibrio?',
          'simulacion',
          ['Considera depredadores ausentes', 'Piensa recursos limitados'],
          [{ paso: 1, descripcion: 'Sin depredador, población pez crece', resultadoParcial: 'Crece exponencial' }, { paso: 2, descripcion: 'Consumen recursos (plancton)', resultadoParcial: 'Disminuyen' }, { paso: 3, descripcion: 'Colapso cadena alimentaria', resultadoParcial: 'Especies mueren' }],
          '¿Qué significa equilibrio dinámico?',
          ['equilibrio', 'ecosistema', 'retroalimentación', 'especie', 'resiliencia'],
          [
            { pregunta: '¿Establece ley trophic cascade?', respuestaCorrecta: 'Depredadores superiores regulan presas', explicacion: 'Depredadores top-down controlan.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Qué es resiliencia?', respuestaCorrecta: 'Capacidad ecosistema recuperarse disturbios', explicacion: 'Resiliencia permite recuperación.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Mutualismo vs competencia?', respuestaCorrecta: 'Mutualismo: beneficio mutuo; competencia: lucha recursos', explicacion: 'Mutualismo ayuda, competencia perjudica.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'biodiversidad',
          'Biodiversidad: La Biblioteca de la Vida',
          24,
          'Biodiversidad es biblioteca todos idiomas: más libros y lenguas, más valor. Perder libro = perder cultura.',
          'Museo obras arte: especie obra única. Destruyes obra, diversidad museo reduce.',
          ['Diversidad genética: variación especies', 'Diversidad especies: número total', 'Diversidad ecosistemas: hábitats', 'Endemismo: únicas un lugar'],
          'Biodiversidad: variedad organismos, genes, ecosistemas; esencial servicios ecológicos.',
          'n/a',
          ['Amazonía: 10% especies planeta', 'Coral reefs: 25% especies marinas', 'Zonas Galápagos, Madagascar'],
          ['Confundir especie con individuo', 'No entender servicios', 'Pensar más especies = mejor'],
          ['Conservación hábitats', 'Recuperación especies', 'Restauración ecológica'],
          '¿Importancia del Coral Triangle para biodiversidad?',
          'ejercicio_contextualizado',
          ['Investiga centros biodiversidad', 'Considera servicios'],
          [{ paso: 1, descripcion: 'Coral Triangle: 6x más biodiverso', resultadoParcial: 'Alto endemismo' }, { paso: 2, descripcion: 'Hábitat 76% peces especies', resultadoParcial: 'Servicio: pesca' }, { paso: 3, descripcion: 'Proteger = seguridad alimentaria', resultadoParcial: 'Vulnerable calentamiento' }],
          '¿Biodiversidad importante humanos?',
          ['biodiversidad', 'especie', 'genética', 'endemismo', 'conservación'],
          [
            { pregunta: '¿Capas biodiversidad?', respuestaCorrecta: 'Tres: genética, especies, ecosistemas', explicacion: 'Biodiversidad tres niveles anidados.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué significa endémico?', respuestaCorrecta: 'Especie nativa lugar específico', explicacion: 'Endémica = única región.', tipoMemoria: 'factual' },
            { pregunta: '¿Efecto pérdida biodiversidad?', respuestaCorrecta: 'Menor resiliencia servicios', explicacion: 'Menos biodiversidad = menos servicios.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'cambio-climatico',
          'Cambio Climático: El Calentamiento del Planeta',
          27,
          'Cambio climático subir volumen equipo: sube lento, después no aguantar. Planeta +1°C, tormentas fuertes.',
          'Olla presión: más calor (CO₂), vapor subir, día abrir válvula (clima extremo).',
          ['Gases efecto invernadero: CO₂, CH₄', 'Efecto invernadero natural vs antropogénico', 'Retroalimentación', 'Mitigación vs adaptación'],
          'Cambio climático: cambio duradero condiciones climáticas por gases efecto invernadero.',
          'CO₂: 420 ppm (preindustrial: 280 ppm)',
          ['Derretimiento glaciares', 'Nivel mar 3.3mm/año', 'Eventos extremos', 'Calentamiento océano 0.1°C/década'],
          ['Confundir clima con tiempo', 'No diferencia escala', 'Olvidar causas'],
          ['Acuerdo París', 'Tecnologías limpias', 'Captura carbono'],
          'Si emisiones CO₂ reducen mitad, ¿esperas 50 años según clima?',
          'simulacion',
          ['Considera CO₂ atmósferico', 'Modela temperatura'],
          [{ paso: 1, descripcion: 'Mitad emisiones = menor acumulación CO₂', resultadoParcial: 'Slowdown' }, { paso: 2, descripcion: 'Temperatura se estabiliza, no 2°C+', resultadoParcial: '1.5°C límite' }, { paso: 3, descripcion: 'Eventos extremos menos frecuentes', resultadoParcial: 'Mitigación parcial' }],
          '¿Cómo cambio climático afecta biodiversidad?',
          ['cambio climático', 'CO₂', 'invernadero', 'mitigación', 'adaptación'],
          [
            { pregunta: '¿Principal gas antropogénico?', respuestaCorrecta: 'CO₂ (dióxido carbono)', explicacion: 'Quemadas combustibles fósiles emiten CO₂.', tipoMemoria: 'factual' },
            { pregunta: '¿Mitigación vs adaptación?', respuestaCorrecta: 'Mitigación: reducir emisiones; adaptación: ajustarse', explicacion: 'Mitigación evita, adaptación se ajusta.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Medir calentamiento global?', respuestaCorrecta: 'Temperatura media, CO₂ ppm, nivel mar', explicacion: 'Indicadores: temperatura, gases, niveles.', tipoMemoria: 'factual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: '¿Diferencia clima y tiempo?', respuestaCorrecta: 'Clima: patrones largo plazo; tiempo: condiciones momento', explicacion: 'Clima promedio, tiempo instantáneo.', tipoMemoria: 'conceptual' },
        { pregunta: '¿Implica ley 10%?', respuestaCorrecta: 'Solo 10% energía transferencia entre niveles', explicacion: '90% se pierde calor, excretas.', tipoMemoria: 'factual' },
        { pregunta: '¿Tres capas biodiversidad?', respuestaCorrecta: 'Diversidad genética, especies, ecosistemas', explicacion: 'Biodiversidad tres niveles anidados.', tipoMemoria: 'factual' },
      ],
    },
  ],
};
