import { CursoBase, QuizActiveRecall } from '../../tipos';

function leccion(
  id: string,
  titulo: string,
  duracion: number,
  intuicion: string,
  analogia: string,
  pasos: string[],
  definicion: string,
  formula: string | undefined,
  ejemplos: string[],
  errores: string[],
  aplicaciones: string[],
  retoEnunciado: string,
  retoTipo: 'problema_resuelto' | 'ejercicio_contextualizado' | 'simulacion',
  retoPistas: string[],
  retoSolucion: { paso: number; descripcion: string; formulaUsada?: string; resultadoParcial?: string }[],
  retoVerificacion: string,
  palabrasClave: string[],
  quiz: QuizActiveRecall[]
) {
  return {
    id,
    titulo,
    duracionAproximada: duracion,
    explicacionFeynman: {
      intuicionInicial: intuicion,
      analogiaSimple: analogia,
      pasoAPasoIntuitivo: pasos,
    },
    conceptoTecnico: {
      definicionFormal: definicion,
      formulaMatematica: formula,
      ejemplos,
      erroresComunes: errores,
      conexionAplicaciones: aplicaciones,
    },
    retoPractico: {
      tipo: retoTipo,
      enunciado: retoEnunciado,
      pistas: retoPistas,
      solucionPasoAPaso: retoSolucion,
      verificacionActiveRecall: retoVerificacion,
    },
    palabrasClave,
    quizActiveRecall: quiz,
  };
}

export const ComputacionCurso: CursoBase = {
  id: 'computacion-neuro',
  nombre: 'Computación Visual: Lógica y Código para Pensar',
  descripcion: 'Curso de programación desde lógica visual hasta algoritmos, priorizando el pensamiento computacional antes de la sintaxis.',
  nivelEducativo: 'Secundaria',
  competencias: [
    'Pensar lógicamente y resolver problemas',
    'Visualizar algoritmos antes de codificar',
    'Seleccionar estructuras de datos adecuadas',
    'Analizar complejidad de algoritmos',
    'Aplicar la programación a contextos reales',
  ],
  duracionEstimada: '15 meses',
  metodologia: {
    metodoFeynman: true,
    activeRecall: true,
    spacedRepetition: true,
    intuicionAntesFormula: true,
    estrategiasTransversales: [
      'Visualización de flujos de datos',
      'Pseudocódigo antes de sintaxis',
      'Diagramas de bloques y diagramas de flujo',
      'Autoevaluación con trazado de ejecución',
    ],
  },
  modulos: [
    {
      id: 'logica-programacion',
      titulo: 'Lógica y Programación: El Pensamiento Computacional',
      orden: 1,
      spacedReviewSchedule: ['día 1', 'día 3', 'día 10', 'día 25'],
      lecciones: [
        leccion(
          'pensamiento-computacional',
          'Pensamiento Computacional: Descomponer para Resolver',
          25,
          'El pensamiento computacional es como armar un rompecabezas: divides el problema en piezas pequeñas, buscas patrones, abstraes los esenciales y creas una receta paso a paso.',
          'Imagina que debes preparar una cena completa: primero desmenuzas la tarea (entrada, plato, postre), luego cada parte (comprar, cocinar, servir) y finalmente automatizas la receta.',
          ['Descomposición: dividir problema en subproblemas', 'Reconocimiento de patrones: encontrar similitudes', 'Abstracción: enfocarse en esenciales', 'Algoritmo: receta de pasos ordenados'],
          'El pensamiento computacional es una metodología para formular problemas y soluciones de manera que puedan ejecutarse en computadora.',
          undefined,
          ['Organizar una fiesta: lista invitados, menú, música, ambientación', 'Navegar con GPS: origen, destino, ruta', 'Cocinar: receta secuencial de pasos'],
          ['Confundir algoritmo con programa', 'No decomponer suficientemente', 'Olvidar validar casos extremos'],
          ['Resolución de problemas en ingeniería', 'Optimización de procesos', 'Automatización doméstica'],
          'Tienes que organizar 200 invitados en 5 mesas con capacidad variada. Diseña un algoritmo usando descomposición.',
          'ejercicio_contextualizado',
          ['Divide: asignar mesas, luego repartir invitados', 'Considera capacidad de cada mesa'],
          [{ paso: 1, descripcion: 'Ordena mesas por capacidad', resultadoParcial: 'M1(50), M2(40), M3(60)...' }, { paso: 2, descripcion: 'Asigna invitados mesa por mesa', resultadoParcial: 'Distribución uniforme' }, { paso: 3, descripcion: 'Verifica total = 200', resultadoParcial: 'Algoritmo completo' }],
          '¿Por qué dividir un problema en subproblemas facilita su resolución?',
          ['pensamiento', 'computacional', 'descomposición', 'abstracción', 'algoritmo'],
          [
            { pregunta: '¿Cuál es el primer paso del pensamiento computacional?', respuestaCorrecta: 'Descomposición del problema', explicacion: 'Dividir en subproblemas manejables.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué diferencia hay entre algoritmo y programa?', respuestaCorrecta: 'Algoritmo: receta abstracta; programa: implementación en código', explicacion: 'Algoritmo es idea, programa es código.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Qué es la abstracción en programación?', respuestaCorrecta: 'Enfocarse en esenciales ignorando detalles', explicacion: 'Ignoras detalles para resolver lo importante.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'variables-tipos-datos',
          'Variables y Tipos de Datos: Cajas con Nombre y Contenido',
          23,
          'Las variables son como cajas etiquetadas: cada caja tiene un nombre (etiqueta) y guarda algo (contenido) que puede cambiar. Una caja "edad" guarda números, "nombre" guarda texto.',
          'Imagina tu habitación: cada caja tiene una etiqueta (edad, nombre, altura) y dentro va su contenido. Puedes cambiar el contenido sin cambiar la etiqueta.',
          ['Variable: caja con nombre que almacena datos', 'Tipos primitivos: número, texto, booleano', 'Asignación: poner valor en variable', 'Declaración vs inicialización'],
          'Una variable es un espacio nombrado en memoria que almacena un valor de un tipo específico.',
          'n/a (sintaxis depende del lenguaje)',
          ['Python: edad = 25', 'JavaScript: let nombre = "Ana"', 'Java: int puntuaje = 100'],
          ['Confundir variable con tipo de dato', 'No inicializar antes de usar', 'Nombres de variable poco descriptivos'],
          ['Declaración de datos en apps', 'Validación de formularios', 'Operaciones matemáticas'],
          'En JavaScript, ¿qué diferencia hay entre let y const? Escribe código que declare una variable mutable y una constante.',
          'problema_resuelto',
          ['let = cambia; const = no cambia', 'Practica declaración e inicialización'],
          [{ paso: 1, descripcion: 'let edad = 25', resultadoParcial: 'Mutable: puede cambiar' }, { paso: 2, descripcion: 'const nombre = "Ana"', resultadoParcial: 'Constante: inmutable' }, { paso: 3, descripcion: 'edad = 26 (ok), nombre = "Luis" (error)', resultadoParcial: 'Verifica diferencia' }],
          '¿Por qué es importante nombrar las variables descriptivamente?',
          ['variable', 'tipo de dato', 'declaración', 'asignación', 'constante'],
          [
            { pregunta: '¿Qué es una variable?', respuestaCorrecta: 'Espacio nombrado que almacena un valor', explicacion: 'Variable = caja con nombre.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué tipo de dato es "true"?', respuestaCorrecta: 'Booleano', explicacion: 'Booleano = verdadero o falso.', tipoMemoria: 'factual' },
            { pregunta: '¿let vs const?', respuestaCorrecta: 'let mutable, const inmutable', explicacion: 'let cambia valor, const no.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'entradas-salidas-condicionales',
          'Entradas, Salidas y Condicionales: Si... Entonces...',
          24,
          'Un programa es como una conversación: primero pregunta algo (entrada), procesa la información, y da una respuesta (salida). Los condicionales son los "si...entonces..." que dirigen la conversación.',
          'Imagina un taxi: pregunta destino (entrada), calcula ruta (procesa), da opciones si hay tráfico (condicional), cobra tarifa (salida).',
          ['Entrada: pedir datos al usuario', 'Salida: mostrar resultados', 'Condicional: if (si hay X, haz Y)', 'Operadores: >, <, ==, !=, &&, ||'],
          'Las estructuras condicionales ejecutan código solo si se cumple una condición, usando operadores lógicos para comparar valores.',
          'if (condición) { acción } else { otra } | condición1 && condición2',
          ['if edad >= 18 → "Mayor"', 'if temperatura > 37 → "Fiebre"', 'if contraseña == "1234" && saldo > 0 → "Acceso"'],
          ['No usar paréntesis en condición', 'Confundir = con ==', 'Olvidar else para caso opuesto'],
          ['Login de usuarios', 'Validación de formularios', 'Detectores de temperatura'],
          'Diseña un programa que pida la temperatura y diga si hay fiebre (>37.5) o no. Incluye un mensaje para temperatura crítica (>40).',
          'ejercicio_contextualizado',
          ['Usa if-else para rangos', 'Considera caso normal, fiebre, crítico'],
          [{ paso: 1, descripcion: 'Pide temperatura (input)', resultadoParcial: 'temp = 38.2' }, { paso: 2, descripcion: 'if temp > 40 → crítico', formulaUsada: 'if-else anidado' }, { paso: 3, descripcion: 'else if temp > 37.5 → fiebre; else → normal', resultadoParcial: '3 casos cubiertos' }],
          '¿Por qué los condicionales son esenciales en cualquier programa?',
          ['entrada', 'salida', 'condicional', 'if', 'operador'],
          [
            { pregunta: '¿Para qué sirve una estructura if?', respuestaCorrecta: 'Ejecutar código si se cumple condición', explicacion: 'If ejecuta si condición verdadera.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué operador significa "y"?', respuestaCorrecta: '&&', explicacion: '&& = AND en lógica booleana.', tipoMemoria: 'factual' },
            { pregunta: '¿= vs ==?', respuestaCorrecta: '= asigna; == compara', explicacion: '= guarda valor, == compara.', tipoMemoria: 'factual' },
          ]
        ),
        leccion(
          'bucles-ciclos',
          'Bucles y Ciclos: Repetir sin Cansancio',
          22,
          'Un bucle es como ensayar un acto de teatro: repites la misma escena (código) hasta que sale perfecto. Mientras la condición se cumple, sigue repitiendo.',
          'Imagina que debes llenar una jarra de agua: cada vaso es una iteración. Repites hasta que la jarra esté llena (condición de parada).',
          ['Bucle while: "mientras sea X, repite"', 'Bucle for: "repite N veces"', 'Contador: controla iteraciones', 'Condición de parada: evita infinito'],
          'Un bucle repite un bloque de código mientras se cumple una condición, requiriendo una condición de parada para evitar bucles infinitos.',
          'for (i=0; i<limite; i++) { ... } | while (condición) { ... }',
          ['for i=1 to 10: imprime números', 'while dinero>0: compra productos', 'for nombre in lista: saluda cada uno'],
          ['Olvidar condición de parada', 'Contador que no se incrementa', 'Confundir for con while'],
          ['Automatización de tareas repetitivas', 'Procesamiento de listas', 'Simulaciones'],
          'Escribe un bucle que sume los números del 1 al 100 e imprima el resultado.',
          'problema_resuelto',
          ['Usa contador iniciando en 0', 'Acumula en variable suma'],
          [{ paso: 1, descripcion: 'suma = 0, i = 1', resultadoParcial: 'Inicializa' }, { paso: 2, descripcion: 'for i=1 to 100: suma += i', formulaUsada: 'suma += i' }, { paso: 3, descripcion: 'Imprime suma = 5050', resultadoParcial: 'Fórmula: n(n+1)/2 = 100×101/2' }],
          '¿Por qué es peligroso un bucle sin condición de parada?',
          ['bucle', 'while', 'for', 'contador', 'parada'],
          [
            { pregunta: '¿Qué tipo de bucle usa contador?', respuestaCorrecta: 'for', explicacion: 'For controla iteraciones con contador.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué es un bucle infinito?', respuestaCorrecta: 'Repetición sin condición de parada', explicacion: 'Loop que nunca termina.', tipoMemoria: 'conceptual' },
            { pregunta: '¿for vs while?', respuestaCorrecta: 'for: veces conocidas; while: condición desconocida', explicacion: 'For para conteos, while para condiciones.', tipoMemoria: 'conceptual' },
          ]
        ),
        leccion(
          'funciones-modularidad',
          'Funciones y Modularidad: Bloques de Recetas Reusables',
          28,
          'Una función es como una receta de cocina escrita una vez: cuando necesitas ese plato, solo digas "haz receta de pastel" y se ejecuta. No reescribes la receta cada vez.',
          'Imagina una licuadora: pones frutas y presionas el botón "licuar". Cada vez que necesites batido, usas "licuar" sin saber cómo funciona el motor internamente.',
          ['Función: bloque de código con nombre', 'Parámetros: entradas a la función', 'Retorno: salida de la función', 'Modularidad: división en bloques reusables'],
          'Una función es un bloque de código nombrado que realiza una tarea específica, puede recibir parámetros y devolver un resultado.',
          'función(args) → retorno',
          ['Math.sqrt(16) = 4', 'imprime("Hola")', 'calcularArea(5) = 78.5'],
          ['No pasar argumentos requeridos', 'Olvidar return', 'Nombrar mal la función'],
          ['Bibliotecas estándar', 'Testing unitario', 'Desarrollo ágil'],
          'Diseña una función "esPar(número)" que retorne true si es par, false si no. Luego usa un bucle para imprimir los pares del 1 al 20.',
          'problema_resuelto',
          ['Función con parámetro', 'Operador módulo %', 'Bucle para iterar'],
          [{ paso: 1, descripcion: 'function esPar(n) { return n % 2 == 0 }', resultadoParcial: 'Función definida' }, { paso: 2, descripcion: 'for i=1 to 20: if esPar(i) print i', formulaUsada: 'n % 2' }, { paso: 3, descripcion: 'Output: 2, 4, 6, 8, 10, 12, 14, 16, 18, 20', resultadoParcial: 'Todos pares identificados' }],
          '¿Por qué dividir código en funciones?',
          ['función', 'parámetro', 'retorno', 'modularidad', 'reusable'],
          [
            { pregunta: '¿Qué son los parámetros de una función?', respuestaCorrecta: 'Entradas que recibe la función', explicacion: 'Parámetros: datos que recibe función.', tipoMemoria: 'factual' },
            { pregunta: '¿Qué significa "modularidad"?', respuestaCorrecta: 'Dividir programa en bloques independientes', explicacion: 'Código separado en módulos.', tipoMemoria: 'conceptual' },
            { pregunta: '¿Para qué sirve return?', respuestaCorrecta: 'Devolver valor al llamador', explicacion: 'Return entrega resultado.', tipoMemoria: 'factual' },
          ]
        ),
      ],
      evaluacionFinal: [
        { pregunta: '¿Qué es la descomposición en pensamiento computacional?', respuestaCorrecta: 'Dividir problema en subproblemas', explicacion: 'Descomposición: fragmentar para resolver.', tipoMemoria: 'factual' },
        { pregunta: '¿let vs const en JavaScript?', respuestaCorrecta: 'let mutable, const inmutable', explicacion: 'Let cambia, const no.', tipoMemoria: 'factual' },
        { pregunta: '¿Por qué usar funciones?', respuestaCorrecta: 'Reusar código y modular', explicacion: 'Funciones = bloques reusables.', tipoMemoria: 'factual' },
      ],
    },
  ],
};
