/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlataformaNeuroRouteImport } from './routes/plataforma-neuro'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiChatEnglishRouteImport } from './routes/api/chat-english'
import { Route as ApiExtractQuestionsRouteImport } from './routes/api/extract-questions'
import { Route as ApiGenerarVideoRouteImport } from './routes/api/generar-video'
import { Route as ApiGenerarVideoActionJobIdRouteImport } from './routes/api/generar-video.$action.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaNeuroRoute = PlataformaNeuroRouteImport.update({
  id: '/plataforma-neuro',
  path: '/plataforma-neuro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatEnglishRoute = ApiChatEnglishRouteImport.update({
  id: '/api/chat-english',
  path: '/api/chat-english',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractQuestionsRoute = ApiExtractQuestionsRouteImport.update({
  id: '/api/extract-questions',
  path: '/api/extract-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerarVideoRoute = ApiGenerarVideoRouteImport.update({
  id: '/api/generar-video',
  path: '/api/generar-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerarVideoActionJobIdRoute =
  ApiGenerarVideoActionJobIdRouteImport.update({
    id: '/$action/$jobId',
    path: '/$action/$jobId',
    getParentRoute: () => ApiGenerarVideoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plataforma-neuro': typeof PlataformaNeuroRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-english': typeof ApiChatEnglishRoute
  '/api/extract-questions': typeof ApiExtractQuestionsRoute
  '/api/generar-video': typeof ApiGenerarVideoRouteWithChildren
  '/api/generar-video/$action/$jobId': typeof ApiGenerarVideoActionJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plataforma-neuro': typeof PlataformaNeuroRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-english': typeof ApiChatEnglishRoute
  '/api/extract-questions': typeof ApiExtractQuestionsRoute
  '/api/generar-video': typeof ApiGenerarVideoRouteWithChildren
  '/api/generar-video/$action/$jobId': typeof ApiGenerarVideoActionJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plataforma-neuro': typeof PlataformaNeuroRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-english': typeof ApiChatEnglishRoute
  '/api/extract-questions': typeof ApiExtractQuestionsRoute
  '/api/generar-video': typeof ApiGenerarVideoRouteWithChildren
  '/api/generar-video/$action/$jobId': typeof ApiGenerarVideoActionJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plataforma-neuro'
    | '/api/chat'
    | '/api/chat-english'
    | '/api/extract-questions'
    | '/api/generar-video'
    | '/api/generar-video/$action/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plataforma-neuro'
    | '/api/chat'
    | '/api/chat-english'
    | '/api/extract-questions'
    | '/api/generar-video'
    | '/api/generar-video/$action/$jobId'
  id:
    | '__root__'
    | '/'
    | '/plataforma-neuro'
    | '/api/chat'
    | '/api/chat-english'
    | '/api/extract-questions'
    | '/api/generar-video'
    | '/api/generar-video/$action/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlataformaNeuroRoute: typeof PlataformaNeuroRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatEnglishRoute: typeof ApiChatEnglishRoute
  ApiExtractQuestionsRoute: typeof ApiExtractQuestionsRoute
  ApiGenerarVideoRoute: typeof ApiGenerarVideoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma-neuro': {
      id: '/plataforma-neuro'
      path: '/plataforma-neuro'
      fullPath: '/plataforma-neuro'
      preLoaderRoute: typeof PlataformaNeuroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-english': {
      id: '/api/chat-english'
      path: '/api/chat-english'
      fullPath: '/api/chat-english'
      preLoaderRoute: typeof ApiChatEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-questions': {
      id: '/api/extract-questions'
      path: '/api/extract-questions'
      fullPath: '/api/extract-questions'
      preLoaderRoute: typeof ApiExtractQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generar-video': {
      id: '/api/generar-video'
      path: '/api/generar-video'
      fullPath: '/api/generar-video'
      preLoaderRoute: typeof ApiGenerarVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generar-video/$action/$jobId': {
      id: '/api/generar-video/$action/$jobId'
      path: '/$action/$jobId'
      fullPath: '/api/generar-video/$action/$jobId'
      preLoaderRoute: typeof ApiGenerarVideoActionJobIdRouteImport
      parentRoute: typeof ApiGenerarVideoRoute
    }
  }
}

interface ApiGenerarVideoRouteChildren {
  ApiGenerarVideoActionJobIdRoute: typeof ApiGenerarVideoActionJobIdRoute
}

const ApiGenerarVideoRouteChildren: ApiGenerarVideoRouteChildren = {
  ApiGenerarVideoActionJobIdRoute: ApiGenerarVideoActionJobIdRoute,
}

const ApiGenerarVideoRouteWithChildren = ApiGenerarVideoRoute._addFileChildren(
  ApiGenerarVideoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlataformaNeuroRoute: PlataformaNeuroRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatEnglishRoute: ApiChatEnglishRoute,
  ApiExtractQuestionsRoute: ApiExtractQuestionsRoute,
  ApiGenerarVideoRoute: ApiGenerarVideoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
